//go:build !noasm && arm64
// AUTO-GENERATED BY GOAT -- DO NOT EDIT

package arm64_goat

import "unsafe"

//go:noescape
func lsh512_neon_init(ctx, algtype unsafe.Pointer)

//go:noescape
func lsh512_neon_update(ctx, data, databitlen unsafe.Pointer)

//go:noescape
func lsh512_neon_final(ctx, hashval unsafe.Pointer)
