//go:build arm64 && !purego && (!gccgo || go1.18)
// +build arm64
// +build !purego
// +build !gccgo go1.18

// GENERATED BY goat
// EDITED BY RYUANERIN
// -- DO NOT EDIT

#include "textflag.h"

TEXT ·__lea_encrypt_4block(SB), NOSPLIT, $24
	MOVD ctx+0(FP), R0
	MOVD dst+8(FP), R1
	MOVD src+16(FP), R2

	WORD $0x91004008   // add	x8, x0, #16
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x4c400841   // ld4.4s	{ v1, v2, v3, v4 }, [x2]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x91005008   // add	x8, x0, #20
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca5   // eor.16b	v5, v5, v4
	WORD $0x4ea084a0   // add.4s	v0, v5, v0
	WORD $0x6f3d0405   // ushr.4s	v5, v0, #3
	WORD $0x6f3d5405   // sli.4s	v5, v0, #29
	WORD $0x91002008   // add	x8, x0, #8
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91003008   // add	x8, x0, #12
	WORD $0x4d40c906   // ld1r.4s	{ v6 }, [x8]
	WORD $0x6e231cc6   // eor.16b	v6, v6, v3
	WORD $0x4ea084c0   // add.4s	v0, v6, v0
	WORD $0x6f3b0406   // ushr.4s	v6, v0, #5
	WORD $0x6f3b5406   // sli.4s	v6, v0, #27
	WORD $0xaa0003e8   // mov	x8, x0
	WORD $0x4ddfc900   // ld1r.4s	{ v0 }, [x8], #4
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6e221ce7   // eor.16b	v7, v7, v2
	WORD $0x4ea084e0   // add.4s	v0, v7, v0
	WORD $0x6f290407   // ushr.4s	v7, v0, #23
	WORD $0x6f295407   // sli.4s	v7, v0, #9
	WORD $0x9100a008   // add	x8, x0, #40
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e251c00   // eor.16b	v0, v0, v5
	WORD $0x9100b008   // add	x8, x0, #44
	WORD $0x4d40c910   // ld1r.4s	{ v16 }, [x8]
	WORD $0x6e211e01   // eor.16b	v1, v16, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3d0401   // ushr.4s	v1, v0, #3
	WORD $0x6f3d5401   // sli.4s	v1, v0, #29
	WORD $0x91008008   // add	x8, x0, #32
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x91009008   // add	x8, x0, #36
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0x6e261c00   // eor.16b	v0, v0, v6
	WORD $0x6e251c42   // eor.16b	v2, v2, v5
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3b0402   // ushr.4s	v2, v0, #5
	WORD $0x6f3b5402   // sli.4s	v2, v0, #27
	WORD $0x91006008   // add	x8, x0, #24
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e271c00   // eor.16b	v0, v0, v7
	WORD $0x91007008   // add	x8, x0, #28
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0x6e261c63   // eor.16b	v3, v3, v6
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f290403   // ushr.4s	v3, v0, #23
	WORD $0x91010008   // add	x8, x0, #64
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6f295403   // sli.4s	v3, v0, #9
	WORD $0x6e211c80   // eor.16b	v0, v4, v1
	WORD $0x91011008   // add	x8, x0, #68
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6e271c84   // eor.16b	v4, v4, v7
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3d0404   // ushr.4s	v4, v0, #3
	WORD $0x6f3d5404   // sli.4s	v4, v0, #29
	WORD $0x9100e008   // add	x8, x0, #56
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x9100f008   // add	x8, x0, #60
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3b0401   // ushr.4s	v1, v0, #5
	WORD $0x6f3b5401   // sli.4s	v1, v0, #27
	WORD $0x9100c008   // add	x8, x0, #48
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x9100d008   // add	x8, x0, #52
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f290402   // ushr.4s	v2, v0, #23
	WORD $0x6f295402   // sli.4s	v2, v0, #9
	WORD $0x91016008   // add	x8, x0, #88
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x91017008   // add	x8, x0, #92
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3d0403   // ushr.4s	v3, v0, #3
	WORD $0x6f3d5403   // sli.4s	v3, v0, #29
	WORD $0x91014008   // add	x8, x0, #80
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x91015008   // add	x8, x0, #84
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3b0404   // ushr.4s	v4, v0, #5
	WORD $0x6f3b5404   // sli.4s	v4, v0, #27
	WORD $0x91012008   // add	x8, x0, #72
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91013008   // add	x8, x0, #76
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f290401   // ushr.4s	v1, v0, #23
	WORD $0x9101c008   // add	x8, x0, #112
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6f295401   // sli.4s	v1, v0, #9
	WORD $0x6e231ca0   // eor.16b	v0, v5, v3
	WORD $0x9101d008   // add	x8, x0, #116
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3d0402   // ushr.4s	v2, v0, #3
	WORD $0x6f3d5402   // sli.4s	v2, v0, #29
	WORD $0x9101a008   // add	x8, x0, #104
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x9101b008   // add	x8, x0, #108
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3b0403   // ushr.4s	v3, v0, #5
	WORD $0x6f3b5403   // sli.4s	v3, v0, #27
	WORD $0x91018008   // add	x8, x0, #96
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x91019008   // add	x8, x0, #100
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f290404   // ushr.4s	v4, v0, #23
	WORD $0x6f295404   // sli.4s	v4, v0, #9
	WORD $0x91022008   // add	x8, x0, #136
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91023008   // add	x8, x0, #140
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3d0401   // ushr.4s	v1, v0, #3
	WORD $0x6f3d5401   // sli.4s	v1, v0, #29
	WORD $0x91020008   // add	x8, x0, #128
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x91021008   // add	x8, x0, #132
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3b0402   // ushr.4s	v2, v0, #5
	WORD $0x6f3b5402   // sli.4s	v2, v0, #27
	WORD $0x9101e008   // add	x8, x0, #120
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x9101f008   // add	x8, x0, #124
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f290403   // ushr.4s	v3, v0, #23
	WORD $0x91028008   // add	x8, x0, #160
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6f295403   // sli.4s	v3, v0, #9
	WORD $0x6e211ca0   // eor.16b	v0, v5, v1
	WORD $0x91029008   // add	x8, x0, #164
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3d0404   // ushr.4s	v4, v0, #3
	WORD $0x6f3d5404   // sli.4s	v4, v0, #29
	WORD $0x91026008   // add	x8, x0, #152
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91027008   // add	x8, x0, #156
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3b0401   // ushr.4s	v1, v0, #5
	WORD $0x6f3b5401   // sli.4s	v1, v0, #27
	WORD $0x91024008   // add	x8, x0, #144
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x91025008   // add	x8, x0, #148
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f290402   // ushr.4s	v2, v0, #23
	WORD $0x6f295402   // sli.4s	v2, v0, #9
	WORD $0x9102e008   // add	x8, x0, #184
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x9102f008   // add	x8, x0, #188
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3d0403   // ushr.4s	v3, v0, #3
	WORD $0x6f3d5403   // sli.4s	v3, v0, #29
	WORD $0x9102c008   // add	x8, x0, #176
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x9102d008   // add	x8, x0, #180
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3b0404   // ushr.4s	v4, v0, #5
	WORD $0x6f3b5404   // sli.4s	v4, v0, #27
	WORD $0x9102a008   // add	x8, x0, #168
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x9102b008   // add	x8, x0, #172
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f290401   // ushr.4s	v1, v0, #23
	WORD $0x91034008   // add	x8, x0, #208
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6f295401   // sli.4s	v1, v0, #9
	WORD $0x6e231ca0   // eor.16b	v0, v5, v3
	WORD $0x91035008   // add	x8, x0, #212
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3d0402   // ushr.4s	v2, v0, #3
	WORD $0x6f3d5402   // sli.4s	v2, v0, #29
	WORD $0x91032008   // add	x8, x0, #200
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x91033008   // add	x8, x0, #204
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3b0403   // ushr.4s	v3, v0, #5
	WORD $0x6f3b5403   // sli.4s	v3, v0, #27
	WORD $0x91030008   // add	x8, x0, #192
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x91031008   // add	x8, x0, #196
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f290404   // ushr.4s	v4, v0, #23
	WORD $0x6f295404   // sli.4s	v4, v0, #9
	WORD $0x9103a008   // add	x8, x0, #232
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x9103b008   // add	x8, x0, #236
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3d0401   // ushr.4s	v1, v0, #3
	WORD $0x6f3d5401   // sli.4s	v1, v0, #29
	WORD $0x91038008   // add	x8, x0, #224
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x91039008   // add	x8, x0, #228
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3b0402   // ushr.4s	v2, v0, #5
	WORD $0x6f3b5402   // sli.4s	v2, v0, #27
	WORD $0x91036008   // add	x8, x0, #216
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x91037008   // add	x8, x0, #220
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f290403   // ushr.4s	v3, v0, #23
	WORD $0x91040008   // add	x8, x0, #256
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6f295403   // sli.4s	v3, v0, #9
	WORD $0x6e211ca0   // eor.16b	v0, v5, v1
	WORD $0x91041008   // add	x8, x0, #260
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3d0404   // ushr.4s	v4, v0, #3
	WORD $0x6f3d5404   // sli.4s	v4, v0, #29
	WORD $0x9103e008   // add	x8, x0, #248
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x9103f008   // add	x8, x0, #252
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3b0401   // ushr.4s	v1, v0, #5
	WORD $0x6f3b5401   // sli.4s	v1, v0, #27
	WORD $0x9103c008   // add	x8, x0, #240
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x9103d008   // add	x8, x0, #244
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f290402   // ushr.4s	v2, v0, #23
	WORD $0x6f295402   // sli.4s	v2, v0, #9
	WORD $0x91046008   // add	x8, x0, #280
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x91047008   // add	x8, x0, #284
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3d0403   // ushr.4s	v3, v0, #3
	WORD $0x6f3d5403   // sli.4s	v3, v0, #29
	WORD $0x91044008   // add	x8, x0, #272
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x91045008   // add	x8, x0, #276
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3b0404   // ushr.4s	v4, v0, #5
	WORD $0x6f3b5404   // sli.4s	v4, v0, #27
	WORD $0x91042008   // add	x8, x0, #264
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91043008   // add	x8, x0, #268
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f290401   // ushr.4s	v1, v0, #23
	WORD $0x9104c008   // add	x8, x0, #304
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6f295401   // sli.4s	v1, v0, #9
	WORD $0x6e231ca0   // eor.16b	v0, v5, v3
	WORD $0x9104d008   // add	x8, x0, #308
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3d0402   // ushr.4s	v2, v0, #3
	WORD $0x6f3d5402   // sli.4s	v2, v0, #29
	WORD $0x9104a008   // add	x8, x0, #296
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x9104b008   // add	x8, x0, #300
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3b0403   // ushr.4s	v3, v0, #5
	WORD $0x6f3b5403   // sli.4s	v3, v0, #27
	WORD $0x91048008   // add	x8, x0, #288
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x91049008   // add	x8, x0, #292
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f290404   // ushr.4s	v4, v0, #23
	WORD $0x6f295404   // sli.4s	v4, v0, #9
	WORD $0x91052008   // add	x8, x0, #328
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91053008   // add	x8, x0, #332
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3d0401   // ushr.4s	v1, v0, #3
	WORD $0x6f3d5401   // sli.4s	v1, v0, #29
	WORD $0x91050008   // add	x8, x0, #320
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x91051008   // add	x8, x0, #324
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3b0402   // ushr.4s	v2, v0, #5
	WORD $0x6f3b5402   // sli.4s	v2, v0, #27
	WORD $0x9104e008   // add	x8, x0, #312
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x9104f008   // add	x8, x0, #316
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f290403   // ushr.4s	v3, v0, #23
	WORD $0x91058008   // add	x8, x0, #352
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6f295403   // sli.4s	v3, v0, #9
	WORD $0x6e211ca0   // eor.16b	v0, v5, v1
	WORD $0x91059008   // add	x8, x0, #356
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3d0404   // ushr.4s	v4, v0, #3
	WORD $0x6f3d5404   // sli.4s	v4, v0, #29
	WORD $0x91056008   // add	x8, x0, #344
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91057008   // add	x8, x0, #348
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3b0401   // ushr.4s	v1, v0, #5
	WORD $0x6f3b5401   // sli.4s	v1, v0, #27
	WORD $0x91054008   // add	x8, x0, #336
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x91055008   // add	x8, x0, #340
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f290402   // ushr.4s	v2, v0, #23
	WORD $0x6f295402   // sli.4s	v2, v0, #9
	WORD $0x9105e008   // add	x8, x0, #376
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x9105f008   // add	x8, x0, #380
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3d0403   // ushr.4s	v3, v0, #3
	WORD $0x6f3d5403   // sli.4s	v3, v0, #29
	WORD $0x9105c008   // add	x8, x0, #368
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x9105d008   // add	x8, x0, #372
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3b0404   // ushr.4s	v4, v0, #5
	WORD $0x6f3b5404   // sli.4s	v4, v0, #27
	WORD $0x9105a008   // add	x8, x0, #360
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x9105b008   // add	x8, x0, #364
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f290401   // ushr.4s	v1, v0, #23
	WORD $0x91064008   // add	x8, x0, #400
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6f295401   // sli.4s	v1, v0, #9
	WORD $0x6e231ca0   // eor.16b	v0, v5, v3
	WORD $0x91065008   // add	x8, x0, #404
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3d0402   // ushr.4s	v2, v0, #3
	WORD $0x6f3d5402   // sli.4s	v2, v0, #29
	WORD $0x91062008   // add	x8, x0, #392
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x91063008   // add	x8, x0, #396
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3b0403   // ushr.4s	v3, v0, #5
	WORD $0x6f3b5403   // sli.4s	v3, v0, #27
	WORD $0x91060008   // add	x8, x0, #384
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x91061008   // add	x8, x0, #388
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f290404   // ushr.4s	v4, v0, #23
	WORD $0x6f295404   // sli.4s	v4, v0, #9
	WORD $0x9106a008   // add	x8, x0, #424
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x9106b008   // add	x8, x0, #428
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3d0401   // ushr.4s	v1, v0, #3
	WORD $0x6f3d5401   // sli.4s	v1, v0, #29
	WORD $0x91068008   // add	x8, x0, #416
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x91069008   // add	x8, x0, #420
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3b0402   // ushr.4s	v2, v0, #5
	WORD $0x6f3b5402   // sli.4s	v2, v0, #27
	WORD $0x91066008   // add	x8, x0, #408
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x91067008   // add	x8, x0, #412
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f290403   // ushr.4s	v3, v0, #23
	WORD $0x91070008   // add	x8, x0, #448
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6f295403   // sli.4s	v3, v0, #9
	WORD $0x6e211ca0   // eor.16b	v0, v5, v1
	WORD $0x91071008   // add	x8, x0, #452
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3d0404   // ushr.4s	v4, v0, #3
	WORD $0x6f3d5404   // sli.4s	v4, v0, #29
	WORD $0x9106e008   // add	x8, x0, #440
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x9106f008   // add	x8, x0, #444
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3b0401   // ushr.4s	v1, v0, #5
	WORD $0x6f3b5401   // sli.4s	v1, v0, #27
	WORD $0x9106c008   // add	x8, x0, #432
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x9106d008   // add	x8, x0, #436
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f290402   // ushr.4s	v2, v0, #23
	WORD $0x6f295402   // sli.4s	v2, v0, #9
	WORD $0x91076008   // add	x8, x0, #472
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x91077008   // add	x8, x0, #476
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3d0403   // ushr.4s	v3, v0, #3
	WORD $0x6f3d5403   // sli.4s	v3, v0, #29
	WORD $0x91074008   // add	x8, x0, #464
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x91075008   // add	x8, x0, #468
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f3b0404   // ushr.4s	v4, v0, #5
	WORD $0x6f3b5404   // sli.4s	v4, v0, #27
	WORD $0x91072008   // add	x8, x0, #456
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91073008   // add	x8, x0, #460
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f290401   // ushr.4s	v1, v0, #23
	WORD $0x9107c008   // add	x8, x0, #496
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6f295401   // sli.4s	v1, v0, #9
	WORD $0x6e231ca0   // eor.16b	v0, v5, v3
	WORD $0x9107d008   // add	x8, x0, #500
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3d0402   // ushr.4s	v2, v0, #3
	WORD $0x6f3d5402   // sli.4s	v2, v0, #29
	WORD $0x9107a008   // add	x8, x0, #488
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x9107b008   // add	x8, x0, #492
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3b0403   // ushr.4s	v3, v0, #5
	WORD $0x6f3b5403   // sli.4s	v3, v0, #27
	WORD $0x91078008   // add	x8, x0, #480
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x91079008   // add	x8, x0, #484
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e241ca4   // eor.16b	v4, v5, v4
	WORD $0x4ea08480   // add.4s	v0, v4, v0
	WORD $0x6f290404   // ushr.4s	v4, v0, #23
	WORD $0x6f295404   // sli.4s	v4, v0, #9
	WORD $0x91082008   // add	x8, x0, #520
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91083008   // add	x8, x0, #524
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e211ca1   // eor.16b	v1, v5, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3d0401   // ushr.4s	v1, v0, #3
	WORD $0x6f3d5401   // sli.4s	v1, v0, #29
	WORD $0x91080008   // add	x8, x0, #512
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x91081008   // add	x8, x0, #516
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231c00   // eor.16b	v0, v0, v3
	WORD $0x6e221ca2   // eor.16b	v2, v5, v2
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3b0402   // ushr.4s	v2, v0, #5
	WORD $0x6f3b5402   // sli.4s	v2, v0, #27
	WORD $0x9107e008   // add	x8, x0, #504
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x9107f008   // add	x8, x0, #508
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca3   // eor.16b	v3, v5, v3
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f290405   // ushr.4s	v5, v0, #23
	WORD $0x91088008   // add	x8, x0, #544
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0x6f295405   // sli.4s	v5, v0, #9
	WORD $0x6e211c60   // eor.16b	v0, v3, v1
	WORD $0x91089008   // add	x8, x0, #548
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0x6e241c63   // eor.16b	v3, v3, v4
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3d0404   // ushr.4s	v4, v0, #3
	WORD $0x6f3d5404   // sli.4s	v4, v0, #29
	WORD $0x91086008   // add	x8, x0, #536
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x91087008   // add	x8, x0, #540
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0x6e211c61   // eor.16b	v1, v3, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3b0406   // ushr.4s	v6, v0, #5
	WORD $0x6f3b5406   // sli.4s	v6, v0, #27
	WORD $0x91084008   // add	x8, x0, #528
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e251c00   // eor.16b	v0, v0, v5
	WORD $0x91085008   // add	x8, x0, #532
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e221c21   // eor.16b	v1, v1, v2
	WORD $0x4ea08427   // add.4s	v7, v1, v0
	WORD $0x6f2904e3   // ushr.4s	v3, v7, #23
	WORD $0x6f2954e3   // sli.4s	v3, v7, #9
	WORD $0x9108e008   // add	x8, x0, #568
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6e241ce7   // eor.16b	v7, v7, v4
	WORD $0x9108f008   // add	x8, x0, #572
	WORD $0x4d40c910   // ld1r.4s	{ v16 }, [x8]
	WORD $0x6e251e05   // eor.16b	v5, v16, v5
	WORD $0x4ea784a5   // add.4s	v5, v5, v7
	WORD $0x6f3d04a2   // ushr.4s	v2, v5, #3
	WORD $0x6f3d54a2   // sli.4s	v2, v5, #29
	WORD $0x9108c008   // add	x8, x0, #560
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x9108d008   // add	x8, x0, #564
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6e261ca5   // eor.16b	v5, v5, v6
	WORD $0x6e241ce4   // eor.16b	v4, v7, v4
	WORD $0x4ea58484   // add.4s	v4, v4, v5
	WORD $0x6f3b0481   // ushr.4s	v1, v4, #5
	WORD $0x6f3b5481   // sli.4s	v1, v4, #27
	WORD $0x9108a008   // add	x8, x0, #552
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6e231c84   // eor.16b	v4, v4, v3
	WORD $0x9108b008   // add	x8, x0, #556
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e261ca5   // eor.16b	v5, v5, v6
	WORD $0x4ea484a4   // add.4s	v4, v5, v4
	WORD $0x6f290480   // ushr.4s	v0, v4, #23
	WORD $0x6f295480   // sli.4s	v0, v4, #9
	WORD $0xb9430008   // ldr	w8, [x0, #768]
	WORD $0x7100651f   // cmp	w8, #25
	WORD $0x54001b63   // b.lo	LBB0_3
	WORD $0x91094009   // add	x9, x0, #592
	WORD $0x4d40c924   // ld1r.4s	{ v4 }, [x9]
	WORD $0x6e221c84   // eor.16b	v4, v4, v2
	WORD $0x91095009   // add	x9, x0, #596
	WORD $0x4d40c925   // ld1r.4s	{ v5 }, [x9]
	WORD $0x6e231ca5   // eor.16b	v5, v5, v3
	WORD $0x4ea484a4   // add.4s	v4, v5, v4
	WORD $0x6f3d0485   // ushr.4s	v5, v4, #3
	WORD $0x91092009   // add	x9, x0, #584
	WORD $0x4d40c926   // ld1r.4s	{ v6 }, [x9]
	WORD $0x6f3d5485   // sli.4s	v5, v4, #29
	WORD $0x6e211cc4   // eor.16b	v4, v6, v1
	WORD $0x91093009   // add	x9, x0, #588
	WORD $0x4d40c926   // ld1r.4s	{ v6 }, [x9]
	WORD $0x6e221cc6   // eor.16b	v6, v6, v2
	WORD $0x4ea484c4   // add.4s	v4, v6, v4
	WORD $0x6f3b0486   // ushr.4s	v6, v4, #5
	WORD $0x6f3b5486   // sli.4s	v6, v4, #27
	WORD $0x91090009   // add	x9, x0, #576
	WORD $0x4d40c924   // ld1r.4s	{ v4 }, [x9]
	WORD $0x6e201c84   // eor.16b	v4, v4, v0
	WORD $0x91091009   // add	x9, x0, #580
	WORD $0x4d40c927   // ld1r.4s	{ v7 }, [x9]
	WORD $0x6e211ce7   // eor.16b	v7, v7, v1
	WORD $0x4ea484e4   // add.4s	v4, v7, v4
	WORD $0x6f290487   // ushr.4s	v7, v4, #23
	WORD $0x6f295487   // sli.4s	v7, v4, #9
	WORD $0x9109a009   // add	x9, x0, #616
	WORD $0x4d40c924   // ld1r.4s	{ v4 }, [x9]
	WORD $0x6e251c84   // eor.16b	v4, v4, v5
	WORD $0x9109b009   // add	x9, x0, #620
	WORD $0x4d40c930   // ld1r.4s	{ v16 }, [x9]
	WORD $0x6e201e00   // eor.16b	v0, v16, v0
	WORD $0x4ea48400   // add.4s	v0, v0, v4
	WORD $0x6f3d0401   // ushr.4s	v1, v0, #3
	WORD $0x6f3d5401   // sli.4s	v1, v0, #29
	WORD $0x91098009   // add	x9, x0, #608
	WORD $0x4d40c920   // ld1r.4s	{ v0 }, [x9]
	WORD $0x6e261c00   // eor.16b	v0, v0, v6
	WORD $0x91099009   // add	x9, x0, #612
	WORD $0x4d40c922   // ld1r.4s	{ v2 }, [x9]
	WORD $0x6e251c42   // eor.16b	v2, v2, v5
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3b0402   // ushr.4s	v2, v0, #5
	WORD $0x6f3b5402   // sli.4s	v2, v0, #27
	WORD $0x91096009   // add	x9, x0, #600
	WORD $0x4d40c920   // ld1r.4s	{ v0 }, [x9]
	WORD $0x91097009   // add	x9, x0, #604
	WORD $0x4d40c923   // ld1r.4s	{ v3 }, [x9]
	WORD $0x6e271c00   // eor.16b	v0, v0, v7
	WORD $0x6e261c63   // eor.16b	v3, v3, v6
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f290404   // ushr.4s	v4, v0, #23
	WORD $0x6f295404   // sli.4s	v4, v0, #9
	WORD $0x910a0009   // add	x9, x0, #640
	WORD $0x4d40c920   // ld1r.4s	{ v0 }, [x9]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x910a1009   // add	x9, x0, #644
	WORD $0x4d40c923   // ld1r.4s	{ v3 }, [x9]
	WORD $0x6e271c63   // eor.16b	v3, v3, v7
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3d0405   // ushr.4s	v5, v0, #3
	WORD $0x9109e009   // add	x9, x0, #632
	WORD $0x4d40c923   // ld1r.4s	{ v3 }, [x9]
	WORD $0x6f3d5405   // sli.4s	v5, v0, #29
	WORD $0x6e221c60   // eor.16b	v0, v3, v2
	WORD $0x9109f009   // add	x9, x0, #636
	WORD $0x4d40c923   // ld1r.4s	{ v3 }, [x9]
	WORD $0x6e211c61   // eor.16b	v1, v3, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3b0406   // ushr.4s	v6, v0, #5
	WORD $0x6f3b5406   // sli.4s	v6, v0, #27
	WORD $0x9109c009   // add	x9, x0, #624
	WORD $0x4d40c920   // ld1r.4s	{ v0 }, [x9]
	WORD $0x6e241c00   // eor.16b	v0, v0, v4
	WORD $0x9109d009   // add	x9, x0, #628
	WORD $0x4d40c921   // ld1r.4s	{ v1 }, [x9]
	WORD $0x6e221c21   // eor.16b	v1, v1, v2
	WORD $0x4ea08427   // add.4s	v7, v1, v0
	WORD $0x6f2904e3   // ushr.4s	v3, v7, #23
	WORD $0x6f2954e3   // sli.4s	v3, v7, #9
	WORD $0x910a6009   // add	x9, x0, #664
	WORD $0x4d40c927   // ld1r.4s	{ v7 }, [x9]
	WORD $0x6e251ce7   // eor.16b	v7, v7, v5
	WORD $0x910a7009   // add	x9, x0, #668
	WORD $0x4d40c930   // ld1r.4s	{ v16 }, [x9]
	WORD $0x6e241e04   // eor.16b	v4, v16, v4
	WORD $0x4ea78484   // add.4s	v4, v4, v7
	WORD $0x6f3d0482   // ushr.4s	v2, v4, #3
	WORD $0x6f3d5482   // sli.4s	v2, v4, #29
	WORD $0x910a4009   // add	x9, x0, #656
	WORD $0x4d40c924   // ld1r.4s	{ v4 }, [x9]
	WORD $0x6e261c84   // eor.16b	v4, v4, v6
	WORD $0x910a5009   // add	x9, x0, #660
	WORD $0x4d40c927   // ld1r.4s	{ v7 }, [x9]
	WORD $0x6e251ce5   // eor.16b	v5, v7, v5
	WORD $0x4ea484a4   // add.4s	v4, v5, v4
	WORD $0x6f3b0481   // ushr.4s	v1, v4, #5
	WORD $0x6f3b5481   // sli.4s	v1, v4, #27
	WORD $0x910a2009   // add	x9, x0, #648
	WORD $0x4d40c924   // ld1r.4s	{ v4 }, [x9]
	WORD $0x910a3009   // add	x9, x0, #652
	WORD $0x4d40c925   // ld1r.4s	{ v5 }, [x9]
	WORD $0x6e231c84   // eor.16b	v4, v4, v3
	WORD $0x6e261ca5   // eor.16b	v5, v5, v6
	WORD $0x4ea484a4   // add.4s	v4, v5, v4
	WORD $0x6f290480   // ushr.4s	v0, v4, #23
	WORD $0x6f295480   // sli.4s	v0, v4, #9
	WORD $0x7100751f   // cmp	w8, #29
	WORD $0x54000da3   // b.lo	LBB0_3
	WORD $0x910ac008   // add	x8, x0, #688
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x910ad008   // add	x8, x0, #692
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e221c84   // eor.16b	v4, v4, v2
	WORD $0x6e231ca5   // eor.16b	v5, v5, v3
	WORD $0x4ea484a4   // add.4s	v4, v5, v4
	WORD $0x6f3d0485   // ushr.4s	v5, v4, #3
	WORD $0x6f3d5485   // sli.4s	v5, v4, #29
	WORD $0x910aa008   // add	x8, x0, #680
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6e211c84   // eor.16b	v4, v4, v1
	WORD $0x910ab008   // add	x8, x0, #684
	WORD $0x4d40c906   // ld1r.4s	{ v6 }, [x8]
	WORD $0x6e221cc6   // eor.16b	v6, v6, v2
	WORD $0x4ea484c4   // add.4s	v4, v6, v4
	WORD $0x6f3b0486   // ushr.4s	v6, v4, #5
	WORD $0x910a8008   // add	x8, x0, #672
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f3b5486   // sli.4s	v6, v4, #27
	WORD $0x6e201ce4   // eor.16b	v4, v7, v0
	WORD $0x910a9008   // add	x8, x0, #676
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6e211ce7   // eor.16b	v7, v7, v1
	WORD $0x4ea484e4   // add.4s	v4, v7, v4
	WORD $0x6f290487   // ushr.4s	v7, v4, #23
	WORD $0x6f295487   // sli.4s	v7, v4, #9
	WORD $0x910b2008   // add	x8, x0, #712
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6e251c84   // eor.16b	v4, v4, v5
	WORD $0x910b3008   // add	x8, x0, #716
	WORD $0x4d40c910   // ld1r.4s	{ v16 }, [x8]
	WORD $0x6e201e00   // eor.16b	v0, v16, v0
	WORD $0x4ea48400   // add.4s	v0, v0, v4
	WORD $0x6f3d0401   // ushr.4s	v1, v0, #3
	WORD $0x6f3d5401   // sli.4s	v1, v0, #29
	WORD $0x910b0008   // add	x8, x0, #704
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e261c00   // eor.16b	v0, v0, v6
	WORD $0x910b1008   // add	x8, x0, #708
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0x6e251c42   // eor.16b	v2, v2, v5
	WORD $0x4ea08440   // add.4s	v0, v2, v0
	WORD $0x6f3b0402   // ushr.4s	v2, v0, #5
	WORD $0x6f3b5402   // sli.4s	v2, v0, #27
	WORD $0x910ae008   // add	x8, x0, #696
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e271c00   // eor.16b	v0, v0, v7
	WORD $0x910af008   // add	x8, x0, #700
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0x6e261c63   // eor.16b	v3, v3, v6
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f290404   // ushr.4s	v4, v0, #23
	WORD $0x6f295404   // sli.4s	v4, v0, #9
	WORD $0x910b8008   // add	x8, x0, #736
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x910b9008   // add	x8, x0, #740
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0x6e211c00   // eor.16b	v0, v0, v1
	WORD $0x6e271c63   // eor.16b	v3, v3, v7
	WORD $0x4ea08460   // add.4s	v0, v3, v0
	WORD $0x6f3d0405   // ushr.4s	v5, v0, #3
	WORD $0x6f3d5405   // sli.4s	v5, v0, #29
	WORD $0x910b6008   // add	x8, x0, #728
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0x6e221c00   // eor.16b	v0, v0, v2
	WORD $0x910b7008   // add	x8, x0, #732
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0x6e211c61   // eor.16b	v1, v3, v1
	WORD $0x4ea08420   // add.4s	v0, v1, v0
	WORD $0x6f3b0406   // ushr.4s	v6, v0, #5
	WORD $0x910b4008   // add	x8, x0, #720
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6f3b5406   // sli.4s	v6, v0, #27
	WORD $0x6e241c20   // eor.16b	v0, v1, v4
	WORD $0x910b5008   // add	x8, x0, #724
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e221c21   // eor.16b	v1, v1, v2
	WORD $0x4ea08427   // add.4s	v7, v1, v0
	WORD $0x6f2904e3   // ushr.4s	v3, v7, #23
	WORD $0x6f2954e3   // sli.4s	v3, v7, #9
	WORD $0x910be008   // add	x8, x0, #760
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6e251ce7   // eor.16b	v7, v7, v5
	WORD $0x910bf008   // add	x8, x0, #764
	WORD $0x4d40c910   // ld1r.4s	{ v16 }, [x8]
	WORD $0x6e241e04   // eor.16b	v4, v16, v4
	WORD $0x4ea78484   // add.4s	v4, v4, v7
	WORD $0x6f3d0482   // ushr.4s	v2, v4, #3
	WORD $0x6f3d5482   // sli.4s	v2, v4, #29
	WORD $0x910bc008   // add	x8, x0, #752
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6e261c84   // eor.16b	v4, v4, v6
	WORD $0x910bd008   // add	x8, x0, #756
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6e251ce5   // eor.16b	v5, v7, v5
	WORD $0x4ea484a4   // add.4s	v4, v5, v4
	WORD $0x6f3b0481   // ushr.4s	v1, v4, #5
	WORD $0x6f3b5481   // sli.4s	v1, v4, #27
	WORD $0x910ba008   // add	x8, x0, #744
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6e231c84   // eor.16b	v4, v4, v3
	WORD $0x910bb008   // add	x8, x0, #748
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e261ca5   // eor.16b	v5, v5, v6
	WORD $0x4ea484a4   // add.4s	v4, v5, v4
	WORD $0x6f290480   // ushr.4s	v0, v4, #23
	WORD $0x6f295480   // sli.4s	v0, v4, #9
	WORD $0x4c000820   // st4.4s	{ v0, v1, v2, v3 }, [x1]
	RET                // ret

TEXT ·__lea_decrypt_4block(SB), NOSPLIT, $24
	MOVD ctx+0(FP), R0
	MOVD dst_base+8(FP), R1
	MOVD src_base+16(FP), R2

	WORD $0x4c400840   // ld4.4s	{ v0, v1, v2, v3 }, [x2]
	WORD $0xb9430008   // ldr	w8, [x0, #768]
	WORD $0x7100751f   // cmp	w8, #29
	WORD $0x54000dc3   // b.lo	LBB1_2
	WORD $0x6f370404   // ushr.4s	v4, v0, #9
	WORD $0x6f375404   // sli.4s	v4, v0, #23
	WORD $0x910ba008   // add	x8, x0, #744
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca5   // eor.16b	v5, v5, v3
	WORD $0x6ea58484   // sub.4s	v4, v4, v5
	WORD $0x910bb008   // add	x8, x0, #748
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c86   // eor.16b	v6, v4, v5
	WORD $0x6f250427   // ushr.4s	v7, v1, #27
	WORD $0x6f255427   // sli.4s	v7, v1, #5
	WORD $0x910bc008   // add	x8, x0, #752
	WORD $0x4d40c910   // ld1r.4s	{ v16 }, [x8]
	WORD $0xce054084   // eor3.16b	v4, v4, v5, v16
	WORD $0x6ea484e4   // sub.4s	v4, v7, v4
	WORD $0x910bd008   // add	x8, x0, #756
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c87   // eor.16b	v7, v4, v5
	WORD $0x6f230450   // ushr.4s	v16, v2, #29
	WORD $0x6f235450   // sli.4s	v16, v2, #3
	WORD $0x910be008   // add	x8, x0, #760
	WORD $0x4d40c911   // ld1r.4s	{ v17 }, [x8]
	WORD $0xce054484   // eor3.16b	v4, v4, v5, v17
	WORD $0x6ea48604   // sub.4s	v4, v16, v4
	WORD $0x910bf008   // add	x8, x0, #764
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c90   // eor.16b	v16, v4, v5
	WORD $0x6f370471   // ushr.4s	v17, v3, #9
	WORD $0x6f375471   // sli.4s	v17, v3, #23
	WORD $0x910b4008   // add	x8, x0, #720
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0xce050080   // eor3.16b	v0, v4, v5, v0
	WORD $0x910b5008   // add	x8, x0, #724
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea08620   // sub.4s	v0, v17, v0
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f2504c3   // ushr.4s	v3, v6, #27
	WORD $0x910b6008   // add	x8, x0, #728
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6f2554c3   // sli.4s	v3, v6, #5
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea08460   // sub.4s	v0, v3, v0
	WORD $0x910b7008   // add	x8, x0, #732
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f2304e4   // ushr.4s	v4, v7, #29
	WORD $0x6f2354e4   // sli.4s	v4, v7, #3
	WORD $0x910b8008   // add	x8, x0, #736
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea08480   // sub.4s	v0, v4, v0
	WORD $0x910b9008   // add	x8, x0, #740
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f370605   // ushr.4s	v5, v16, #9
	WORD $0x6f375605   // sli.4s	v5, v16, #23
	WORD $0x910ae008   // add	x8, x0, #696
	WORD $0x4d40c906   // ld1r.4s	{ v6 }, [x8]
	WORD $0xce011800   // eor3.16b	v0, v0, v1, v6
	WORD $0x6ea084a0   // sub.4s	v0, v5, v0
	WORD $0x910af008   // add	x8, x0, #700
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f250446   // ushr.4s	v6, v2, #27
	WORD $0x6f255446   // sli.4s	v6, v2, #5
	WORD $0x910b0008   // add	x8, x0, #704
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x910b1008   // add	x8, x0, #708
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c06   // eor.16b	v6, v0, v1
	WORD $0x6f230462   // ushr.4s	v2, v3, #29
	WORD $0x6f235462   // sli.4s	v2, v3, #3
	WORD $0x910b2008   // add	x8, x0, #712
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea08447   // sub.4s	v7, v2, v0
	WORD $0x910b3008   // add	x8, x0, #716
	WORD $0x4d40c910   // ld1r.4s	{ v16 }, [x8]
	WORD $0x6e301ce0   // eor.16b	v0, v7, v16
	WORD $0x6f370491   // ushr.4s	v17, v4, #9
	WORD $0x6f375491   // sli.4s	v17, v4, #23
	WORD $0x910a8008   // add	x8, x0, #672
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce1010e4   // eor3.16b	v4, v7, v16, v4
	WORD $0x910a9008   // add	x8, x0, #676
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6ea48624   // sub.4s	v4, v17, v4
	WORD $0x6e271c81   // eor.16b	v1, v4, v7
	WORD $0x6f2504b0   // ushr.4s	v16, v5, #27
	WORD $0x910aa008   // add	x8, x0, #680
	WORD $0x4d40c911   // ld1r.4s	{ v17 }, [x8]
	WORD $0x6f2554b0   // sli.4s	v16, v5, #5
	WORD $0xce074484   // eor3.16b	v4, v4, v7, v17
	WORD $0x6ea48604   // sub.4s	v4, v16, v4
	WORD $0x910ab008   // add	x8, x0, #684
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c82   // eor.16b	v2, v4, v5
	WORD $0x6f2304c7   // ushr.4s	v7, v6, #29
	WORD $0x6f2354c7   // sli.4s	v7, v6, #3
	WORD $0x910ac008   // add	x8, x0, #688
	WORD $0x4d40c906   // ld1r.4s	{ v6 }, [x8]
	WORD $0xce051884   // eor3.16b	v4, v4, v5, v6
	WORD $0x6ea484e4   // sub.4s	v4, v7, v4
	WORD $0x910ad008   // add	x8, x0, #692
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c83   // eor.16b	v3, v4, v5
	WORD $0x14000003   // b	LBB1_3
	WORD $0x7100651f   // cmp	w8, #25
	WORD $0x54000da3   // b.lo	LBB1_4
	WORD $0x6f370404   // ushr.4s	v4, v0, #9
	WORD $0x6f375404   // sli.4s	v4, v0, #23
	WORD $0x910a2008   // add	x8, x0, #648
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca5   // eor.16b	v5, v5, v3
	WORD $0x6ea58484   // sub.4s	v4, v4, v5
	WORD $0x910a3008   // add	x8, x0, #652
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c86   // eor.16b	v6, v4, v5
	WORD $0x6f250427   // ushr.4s	v7, v1, #27
	WORD $0x6f255427   // sli.4s	v7, v1, #5
	WORD $0x910a4008   // add	x8, x0, #656
	WORD $0x4d40c910   // ld1r.4s	{ v16 }, [x8]
	WORD $0xce054084   // eor3.16b	v4, v4, v5, v16
	WORD $0x6ea484e4   // sub.4s	v4, v7, v4
	WORD $0x910a5008   // add	x8, x0, #660
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c87   // eor.16b	v7, v4, v5
	WORD $0x6f230450   // ushr.4s	v16, v2, #29
	WORD $0x6f235450   // sli.4s	v16, v2, #3
	WORD $0x910a6008   // add	x8, x0, #664
	WORD $0x4d40c911   // ld1r.4s	{ v17 }, [x8]
	WORD $0xce054484   // eor3.16b	v4, v4, v5, v17
	WORD $0x6ea48604   // sub.4s	v4, v16, v4
	WORD $0x910a7008   // add	x8, x0, #668
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c90   // eor.16b	v16, v4, v5
	WORD $0x6f370471   // ushr.4s	v17, v3, #9
	WORD $0x6f375471   // sli.4s	v17, v3, #23
	WORD $0x9109c008   // add	x8, x0, #624
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0xce050080   // eor3.16b	v0, v4, v5, v0
	WORD $0x9109d008   // add	x8, x0, #628
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea08620   // sub.4s	v0, v17, v0
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f2504c3   // ushr.4s	v3, v6, #27
	WORD $0x9109e008   // add	x8, x0, #632
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6f2554c3   // sli.4s	v3, v6, #5
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea08460   // sub.4s	v0, v3, v0
	WORD $0x9109f008   // add	x8, x0, #636
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f2304e4   // ushr.4s	v4, v7, #29
	WORD $0x6f2354e4   // sli.4s	v4, v7, #3
	WORD $0x910a0008   // add	x8, x0, #640
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea08480   // sub.4s	v0, v4, v0
	WORD $0x910a1008   // add	x8, x0, #644
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f370605   // ushr.4s	v5, v16, #9
	WORD $0x6f375605   // sli.4s	v5, v16, #23
	WORD $0x91096008   // add	x8, x0, #600
	WORD $0x4d40c906   // ld1r.4s	{ v6 }, [x8]
	WORD $0xce011800   // eor3.16b	v0, v0, v1, v6
	WORD $0x6ea084a0   // sub.4s	v0, v5, v0
	WORD $0x91097008   // add	x8, x0, #604
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f250446   // ushr.4s	v6, v2, #27
	WORD $0x6f255446   // sli.4s	v6, v2, #5
	WORD $0x91098008   // add	x8, x0, #608
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91099008   // add	x8, x0, #612
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c06   // eor.16b	v6, v0, v1
	WORD $0x6f230462   // ushr.4s	v2, v3, #29
	WORD $0x6f235462   // sli.4s	v2, v3, #3
	WORD $0x9109a008   // add	x8, x0, #616
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea08447   // sub.4s	v7, v2, v0
	WORD $0x9109b008   // add	x8, x0, #620
	WORD $0x4d40c910   // ld1r.4s	{ v16 }, [x8]
	WORD $0x6e301ce0   // eor.16b	v0, v7, v16
	WORD $0x6f370491   // ushr.4s	v17, v4, #9
	WORD $0x6f375491   // sli.4s	v17, v4, #23
	WORD $0x91090008   // add	x8, x0, #576
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce1010e4   // eor3.16b	v4, v7, v16, v4
	WORD $0x91091008   // add	x8, x0, #580
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6ea48624   // sub.4s	v4, v17, v4
	WORD $0x6e271c81   // eor.16b	v1, v4, v7
	WORD $0x6f2504b0   // ushr.4s	v16, v5, #27
	WORD $0x91092008   // add	x8, x0, #584
	WORD $0x4d40c911   // ld1r.4s	{ v17 }, [x8]
	WORD $0x6f2554b0   // sli.4s	v16, v5, #5
	WORD $0xce074484   // eor3.16b	v4, v4, v7, v17
	WORD $0x6ea48604   // sub.4s	v4, v16, v4
	WORD $0x91093008   // add	x8, x0, #588
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c82   // eor.16b	v2, v4, v5
	WORD $0x6f2304c7   // ushr.4s	v7, v6, #29
	WORD $0x6f2354c7   // sli.4s	v7, v6, #3
	WORD $0x91094008   // add	x8, x0, #592
	WORD $0x4d40c906   // ld1r.4s	{ v6 }, [x8]
	WORD $0xce051884   // eor3.16b	v4, v4, v5, v6
	WORD $0x6ea484e4   // sub.4s	v4, v7, v4
	WORD $0x91095008   // add	x8, x0, #596
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c83   // eor.16b	v3, v4, v5
	WORD $0x6f370404   // ushr.4s	v4, v0, #9
	WORD $0x6f375404   // sli.4s	v4, v0, #23
	WORD $0x9108a008   // add	x8, x0, #552
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e231ca5   // eor.16b	v5, v5, v3
	WORD $0x6ea58484   // sub.4s	v4, v4, v5
	WORD $0x9108b008   // add	x8, x0, #556
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c86   // eor.16b	v6, v4, v5
	WORD $0x6f250427   // ushr.4s	v7, v1, #27
	WORD $0x6f255427   // sli.4s	v7, v1, #5
	WORD $0x9108c008   // add	x8, x0, #560
	WORD $0x4d40c910   // ld1r.4s	{ v16 }, [x8]
	WORD $0xce054084   // eor3.16b	v4, v4, v5, v16
	WORD $0x6ea484e4   // sub.4s	v4, v7, v4
	WORD $0x9108d008   // add	x8, x0, #564
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c87   // eor.16b	v7, v4, v5
	WORD $0x6f230450   // ushr.4s	v16, v2, #29
	WORD $0x6f235450   // sli.4s	v16, v2, #3
	WORD $0x9108e008   // add	x8, x0, #568
	WORD $0x4d40c911   // ld1r.4s	{ v17 }, [x8]
	WORD $0xce054484   // eor3.16b	v4, v4, v5, v17
	WORD $0x6ea48604   // sub.4s	v4, v16, v4
	WORD $0x9108f008   // add	x8, x0, #572
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0x6e251c90   // eor.16b	v16, v4, v5
	WORD $0x6f370471   // ushr.4s	v17, v3, #9
	WORD $0x6f375471   // sli.4s	v17, v3, #23
	WORD $0x91084008   // add	x8, x0, #528
	WORD $0x4d40c900   // ld1r.4s	{ v0 }, [x8]
	WORD $0xce050080   // eor3.16b	v0, v4, v5, v0
	WORD $0x91085008   // add	x8, x0, #532
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea08620   // sub.4s	v0, v17, v0
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f2504c3   // ushr.4s	v3, v6, #27
	WORD $0x91086008   // add	x8, x0, #536
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6f2554c3   // sli.4s	v3, v6, #5
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea08460   // sub.4s	v0, v3, v0
	WORD $0x91087008   // add	x8, x0, #540
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f2304e4   // ushr.4s	v4, v7, #29
	WORD $0x6f2354e4   // sli.4s	v4, v7, #3
	WORD $0x91088008   // add	x8, x0, #544
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea08480   // sub.4s	v0, v4, v0
	WORD $0x91089008   // add	x8, x0, #548
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f370605   // ushr.4s	v5, v16, #9
	WORD $0x6f375605   // sli.4s	v5, v16, #23
	WORD $0x9107e008   // add	x8, x0, #504
	WORD $0x4d40c906   // ld1r.4s	{ v6 }, [x8]
	WORD $0xce011800   // eor3.16b	v0, v0, v1, v6
	WORD $0x6ea084a0   // sub.4s	v0, v5, v0
	WORD $0x9107f008   // add	x8, x0, #508
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f250446   // ushr.4s	v6, v2, #27
	WORD $0x6f255446   // sli.4s	v6, v2, #5
	WORD $0x91080008   // add	x8, x0, #512
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91081008   // add	x8, x0, #516
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f230466   // ushr.4s	v6, v3, #29
	WORD $0x6f235466   // sli.4s	v6, v3, #3
	WORD $0x91082008   // add	x8, x0, #520
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91083008   // add	x8, x0, #524
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f370486   // ushr.4s	v6, v4, #9
	WORD $0x6f375486   // sli.4s	v6, v4, #23
	WORD $0x91078008   // add	x8, x0, #480
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x91079008   // add	x8, x0, #484
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2504a6   // ushr.4s	v6, v5, #27
	WORD $0x9107a008   // add	x8, x0, #488
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f2554a6   // sli.4s	v6, v5, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9107b008   // add	x8, x0, #492
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f230446   // ushr.4s	v6, v2, #29
	WORD $0x6f235446   // sli.4s	v6, v2, #3
	WORD $0x9107c008   // add	x8, x0, #496
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9107d008   // add	x8, x0, #500
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f370466   // ushr.4s	v6, v3, #9
	WORD $0x6f375466   // sli.4s	v6, v3, #23
	WORD $0x91072008   // add	x8, x0, #456
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91073008   // add	x8, x0, #460
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f250486   // ushr.4s	v6, v4, #27
	WORD $0x6f255486   // sli.4s	v6, v4, #5
	WORD $0x91074008   // add	x8, x0, #464
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91075008   // add	x8, x0, #468
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2304a6   // ushr.4s	v6, v5, #29
	WORD $0x6f2354a6   // sli.4s	v6, v5, #3
	WORD $0x91076008   // add	x8, x0, #472
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91077008   // add	x8, x0, #476
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f370446   // ushr.4s	v6, v2, #9
	WORD $0x6f375446   // sli.4s	v6, v2, #23
	WORD $0x9106c008   // add	x8, x0, #432
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x9106d008   // add	x8, x0, #436
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f250466   // ushr.4s	v6, v3, #27
	WORD $0x9106e008   // add	x8, x0, #440
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f255466   // sli.4s	v6, v3, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9106f008   // add	x8, x0, #444
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f230486   // ushr.4s	v6, v4, #29
	WORD $0x6f235486   // sli.4s	v6, v4, #3
	WORD $0x91070008   // add	x8, x0, #448
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91071008   // add	x8, x0, #452
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f3704a6   // ushr.4s	v6, v5, #9
	WORD $0x6f3754a6   // sli.4s	v6, v5, #23
	WORD $0x91066008   // add	x8, x0, #408
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91067008   // add	x8, x0, #412
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f250446   // ushr.4s	v6, v2, #27
	WORD $0x6f255446   // sli.4s	v6, v2, #5
	WORD $0x91068008   // add	x8, x0, #416
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91069008   // add	x8, x0, #420
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f230466   // ushr.4s	v6, v3, #29
	WORD $0x6f235466   // sli.4s	v6, v3, #3
	WORD $0x9106a008   // add	x8, x0, #424
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9106b008   // add	x8, x0, #428
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f370486   // ushr.4s	v6, v4, #9
	WORD $0x6f375486   // sli.4s	v6, v4, #23
	WORD $0x91060008   // add	x8, x0, #384
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x91061008   // add	x8, x0, #388
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2504a6   // ushr.4s	v6, v5, #27
	WORD $0x91062008   // add	x8, x0, #392
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f2554a6   // sli.4s	v6, v5, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91063008   // add	x8, x0, #396
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f230446   // ushr.4s	v6, v2, #29
	WORD $0x6f235446   // sli.4s	v6, v2, #3
	WORD $0x91064008   // add	x8, x0, #400
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91065008   // add	x8, x0, #404
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f370466   // ushr.4s	v6, v3, #9
	WORD $0x6f375466   // sli.4s	v6, v3, #23
	WORD $0x9105a008   // add	x8, x0, #360
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9105b008   // add	x8, x0, #364
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f250486   // ushr.4s	v6, v4, #27
	WORD $0x6f255486   // sli.4s	v6, v4, #5
	WORD $0x9105c008   // add	x8, x0, #368
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9105d008   // add	x8, x0, #372
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2304a6   // ushr.4s	v6, v5, #29
	WORD $0x6f2354a6   // sli.4s	v6, v5, #3
	WORD $0x9105e008   // add	x8, x0, #376
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9105f008   // add	x8, x0, #380
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f370446   // ushr.4s	v6, v2, #9
	WORD $0x6f375446   // sli.4s	v6, v2, #23
	WORD $0x91054008   // add	x8, x0, #336
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x91055008   // add	x8, x0, #340
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f250466   // ushr.4s	v6, v3, #27
	WORD $0x91056008   // add	x8, x0, #344
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f255466   // sli.4s	v6, v3, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91057008   // add	x8, x0, #348
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f230486   // ushr.4s	v6, v4, #29
	WORD $0x6f235486   // sli.4s	v6, v4, #3
	WORD $0x91058008   // add	x8, x0, #352
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91059008   // add	x8, x0, #356
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f3704a6   // ushr.4s	v6, v5, #9
	WORD $0x6f3754a6   // sli.4s	v6, v5, #23
	WORD $0x9104e008   // add	x8, x0, #312
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9104f008   // add	x8, x0, #316
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f250446   // ushr.4s	v6, v2, #27
	WORD $0x6f255446   // sli.4s	v6, v2, #5
	WORD $0x91050008   // add	x8, x0, #320
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91051008   // add	x8, x0, #324
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f230466   // ushr.4s	v6, v3, #29
	WORD $0x6f235466   // sli.4s	v6, v3, #3
	WORD $0x91052008   // add	x8, x0, #328
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91053008   // add	x8, x0, #332
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f370486   // ushr.4s	v6, v4, #9
	WORD $0x6f375486   // sli.4s	v6, v4, #23
	WORD $0x91048008   // add	x8, x0, #288
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x91049008   // add	x8, x0, #292
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2504a6   // ushr.4s	v6, v5, #27
	WORD $0x9104a008   // add	x8, x0, #296
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f2554a6   // sli.4s	v6, v5, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9104b008   // add	x8, x0, #300
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f230446   // ushr.4s	v6, v2, #29
	WORD $0x6f235446   // sli.4s	v6, v2, #3
	WORD $0x9104c008   // add	x8, x0, #304
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9104d008   // add	x8, x0, #308
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f370466   // ushr.4s	v6, v3, #9
	WORD $0x6f375466   // sli.4s	v6, v3, #23
	WORD $0x91042008   // add	x8, x0, #264
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91043008   // add	x8, x0, #268
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f250486   // ushr.4s	v6, v4, #27
	WORD $0x6f255486   // sli.4s	v6, v4, #5
	WORD $0x91044008   // add	x8, x0, #272
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91045008   // add	x8, x0, #276
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2304a6   // ushr.4s	v6, v5, #29
	WORD $0x6f2354a6   // sli.4s	v6, v5, #3
	WORD $0x91046008   // add	x8, x0, #280
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91047008   // add	x8, x0, #284
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f370446   // ushr.4s	v6, v2, #9
	WORD $0x6f375446   // sli.4s	v6, v2, #23
	WORD $0x9103c008   // add	x8, x0, #240
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x9103d008   // add	x8, x0, #244
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f250466   // ushr.4s	v6, v3, #27
	WORD $0x9103e008   // add	x8, x0, #248
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f255466   // sli.4s	v6, v3, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9103f008   // add	x8, x0, #252
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f230486   // ushr.4s	v6, v4, #29
	WORD $0x6f235486   // sli.4s	v6, v4, #3
	WORD $0x91040008   // add	x8, x0, #256
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91041008   // add	x8, x0, #260
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f3704a6   // ushr.4s	v6, v5, #9
	WORD $0x6f3754a6   // sli.4s	v6, v5, #23
	WORD $0x91036008   // add	x8, x0, #216
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91037008   // add	x8, x0, #220
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f250446   // ushr.4s	v6, v2, #27
	WORD $0x6f255446   // sli.4s	v6, v2, #5
	WORD $0x91038008   // add	x8, x0, #224
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91039008   // add	x8, x0, #228
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f230466   // ushr.4s	v6, v3, #29
	WORD $0x6f235466   // sli.4s	v6, v3, #3
	WORD $0x9103a008   // add	x8, x0, #232
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9103b008   // add	x8, x0, #236
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f370486   // ushr.4s	v6, v4, #9
	WORD $0x6f375486   // sli.4s	v6, v4, #23
	WORD $0x91030008   // add	x8, x0, #192
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x91031008   // add	x8, x0, #196
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2504a6   // ushr.4s	v6, v5, #27
	WORD $0x91032008   // add	x8, x0, #200
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f2554a6   // sli.4s	v6, v5, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91033008   // add	x8, x0, #204
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f230446   // ushr.4s	v6, v2, #29
	WORD $0x6f235446   // sli.4s	v6, v2, #3
	WORD $0x91034008   // add	x8, x0, #208
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91035008   // add	x8, x0, #212
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f370466   // ushr.4s	v6, v3, #9
	WORD $0x6f375466   // sli.4s	v6, v3, #23
	WORD $0x9102a008   // add	x8, x0, #168
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9102b008   // add	x8, x0, #172
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f250486   // ushr.4s	v6, v4, #27
	WORD $0x6f255486   // sli.4s	v6, v4, #5
	WORD $0x9102c008   // add	x8, x0, #176
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9102d008   // add	x8, x0, #180
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2304a6   // ushr.4s	v6, v5, #29
	WORD $0x6f2354a6   // sli.4s	v6, v5, #3
	WORD $0x9102e008   // add	x8, x0, #184
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9102f008   // add	x8, x0, #188
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f370446   // ushr.4s	v6, v2, #9
	WORD $0x6f375446   // sli.4s	v6, v2, #23
	WORD $0x91024008   // add	x8, x0, #144
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x91025008   // add	x8, x0, #148
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f250466   // ushr.4s	v6, v3, #27
	WORD $0x91026008   // add	x8, x0, #152
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f255466   // sli.4s	v6, v3, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91027008   // add	x8, x0, #156
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f230486   // ushr.4s	v6, v4, #29
	WORD $0x6f235486   // sli.4s	v6, v4, #3
	WORD $0x91028008   // add	x8, x0, #160
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91029008   // add	x8, x0, #164
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f3704a6   // ushr.4s	v6, v5, #9
	WORD $0x6f3754a6   // sli.4s	v6, v5, #23
	WORD $0x9101e008   // add	x8, x0, #120
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9101f008   // add	x8, x0, #124
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f250446   // ushr.4s	v6, v2, #27
	WORD $0x6f255446   // sli.4s	v6, v2, #5
	WORD $0x91020008   // add	x8, x0, #128
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91021008   // add	x8, x0, #132
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f230466   // ushr.4s	v6, v3, #29
	WORD $0x6f235466   // sli.4s	v6, v3, #3
	WORD $0x91022008   // add	x8, x0, #136
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91023008   // add	x8, x0, #140
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f370486   // ushr.4s	v6, v4, #9
	WORD $0x6f375486   // sli.4s	v6, v4, #23
	WORD $0x91018008   // add	x8, x0, #96
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x91019008   // add	x8, x0, #100
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2504a6   // ushr.4s	v6, v5, #27
	WORD $0x9101a008   // add	x8, x0, #104
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f2554a6   // sli.4s	v6, v5, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9101b008   // add	x8, x0, #108
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f230446   // ushr.4s	v6, v2, #29
	WORD $0x6f235446   // sli.4s	v6, v2, #3
	WORD $0x9101c008   // add	x8, x0, #112
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9101d008   // add	x8, x0, #116
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f370466   // ushr.4s	v6, v3, #9
	WORD $0x6f375466   // sli.4s	v6, v3, #23
	WORD $0x91012008   // add	x8, x0, #72
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91013008   // add	x8, x0, #76
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f250486   // ushr.4s	v6, v4, #27
	WORD $0x6f255486   // sli.4s	v6, v4, #5
	WORD $0x91014008   // add	x8, x0, #80
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91015008   // add	x8, x0, #84
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f2304a6   // ushr.4s	v6, v5, #29
	WORD $0x6f2354a6   // sli.4s	v6, v5, #3
	WORD $0x91016008   // add	x8, x0, #88
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91017008   // add	x8, x0, #92
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f370446   // ushr.4s	v6, v2, #9
	WORD $0x6f375446   // sli.4s	v6, v2, #23
	WORD $0x9100c008   // add	x8, x0, #48
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x9100d008   // add	x8, x0, #52
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f250466   // ushr.4s	v6, v3, #27
	WORD $0x9100e008   // add	x8, x0, #56
	WORD $0x4d40c907   // ld1r.4s	{ v7 }, [x8]
	WORD $0x6f255466   // sli.4s	v6, v3, #5
	WORD $0xce011c00   // eor3.16b	v0, v0, v1, v7
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9100f008   // add	x8, x0, #60
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c03   // eor.16b	v3, v0, v1
	WORD $0x6f230486   // ushr.4s	v6, v4, #29
	WORD $0x6f235486   // sli.4s	v6, v4, #3
	WORD $0x91010008   // add	x8, x0, #64
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91011008   // add	x8, x0, #68
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c04   // eor.16b	v4, v0, v1
	WORD $0x6f3704a6   // ushr.4s	v6, v5, #9
	WORD $0x6f3754a6   // sli.4s	v6, v5, #23
	WORD $0x91006008   // add	x8, x0, #24
	WORD $0x4d40c905   // ld1r.4s	{ v5 }, [x8]
	WORD $0xce011400   // eor3.16b	v0, v0, v1, v5
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91007008   // add	x8, x0, #28
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c05   // eor.16b	v5, v0, v1
	WORD $0x6f250446   // ushr.4s	v6, v2, #27
	WORD $0x6f255446   // sli.4s	v6, v2, #5
	WORD $0x91008008   // add	x8, x0, #32
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x91009008   // add	x8, x0, #36
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c02   // eor.16b	v2, v0, v1
	WORD $0x6f230466   // ushr.4s	v6, v3, #29
	WORD $0x6f235466   // sli.4s	v6, v3, #3
	WORD $0x9100a008   // add	x8, x0, #40
	WORD $0x4d40c903   // ld1r.4s	{ v3 }, [x8]
	WORD $0xce010c00   // eor3.16b	v0, v0, v1, v3
	WORD $0x6ea084c0   // sub.4s	v0, v6, v0
	WORD $0x9100b008   // add	x8, x0, #44
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c10   // eor.16b	v16, v0, v1
	WORD $0x6f370483   // ushr.4s	v3, v4, #9
	WORD $0x6f375483   // sli.4s	v3, v4, #23
	WORD $0xaa0003e8   // mov	x8, x0
	WORD $0x4ddfc904   // ld1r.4s	{ v4 }, [x8], #4
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6ea08460   // sub.4s	v0, v3, v0
	WORD $0x6e211c11   // eor.16b	v17, v0, v1
	WORD $0x6f2504a3   // ushr.4s	v3, v5, #27
	WORD $0x91002008   // add	x8, x0, #8
	WORD $0x4d40c904   // ld1r.4s	{ v4 }, [x8]
	WORD $0x6f2554a3   // sli.4s	v3, v5, #5
	WORD $0xce011000   // eor3.16b	v0, v0, v1, v4
	WORD $0x6ea08460   // sub.4s	v0, v3, v0
	WORD $0x91003008   // add	x8, x0, #12
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c12   // eor.16b	v18, v0, v1
	WORD $0x6f230443   // ushr.4s	v3, v2, #29
	WORD $0x6f235443   // sli.4s	v3, v2, #3
	WORD $0x91004008   // add	x8, x0, #16
	WORD $0x4d40c902   // ld1r.4s	{ v2 }, [x8]
	WORD $0xce010800   // eor3.16b	v0, v0, v1, v2
	WORD $0x6ea08460   // sub.4s	v0, v3, v0
	WORD $0x91005008   // add	x8, x0, #20
	WORD $0x4d40c901   // ld1r.4s	{ v1 }, [x8]
	WORD $0x6e211c13   // eor.16b	v19, v0, v1
	WORD $0x4c000830   // st4.4s	{ v16, v17, v18, v19 }, [x1]
	RET                // ret
