//go:build arm64 && gc && !purego
// AUTO-GENERATED BY GOAT -- DO NOT EDIT

package lea

import "unsafe"

//go:noescape
func lea_encrypt_4block(ct, pt, rk unsafe.Pointer, round uint64)

//go:noescape
func lea_decrypt_4block(pt, ct, rk unsafe.Pointer, round uint64)
