// Code generated by command: go run main.go -out ../cipher_amd64.s -stubs ../cipher_amd64_stubs.go. DO NOT EDIT.

package lsh256

func lsh256InitSSE2(ctx *lsh256ContextAsmData)

func lsh256UpdateSSE2(ctx *lsh256ContextAsmData, data []byte, remain_msg_byte int) int

func lsh256FinalSSE2(ctx *lsh256ContextAsmData, hashval []byte)
