//go:build arm64 && !purego
// +build arm64,!purego

// GENERATED BY goat
// EDITED BY RYUANERIN
// -- DO NOT EDIT

#include "textflag.h"

TEXT ·__initEncKey_NEON(SB), NOSPLIT, $0-24
	MOVD	rk+0(FP), R0
	MOVD	key+8(FP), R1
	MOVD	keylen+16(FP), R2

										// ; %bb.0:
	WORD	$0xa9bc5ff8					//     stp	x24, x23, [sp, #-64]!           ; 16-byte Folded Spill
	WORD	$0xa90157f6					//     stp	x22, x21, [sp, #16]             ; 16-byte Folded Spill
	WORD	$0xa9024ff4					//     stp	x20, x19, [sp, #32]             ; 16-byte Folded Spill
	WORD	$0xa9037bfd					//     stp	x29, x30, [sp, #48]             ; 16-byte Folded Spill
	WORD	$0x9100c3fd					//     add	x29, sp, #48
	WORD	$0x32089fe8					//     mov	w8, #-16711936                  ; =0xff00ff00
	WORD	$0x29402829					//     ldp	w9, w10, [x1]
	WORD	$0x5ac00930					//     rev	w16, w9
	WORD	$0x5ac0094e					//     rev	w14, w10
	WORD	$0x29412829					//     ldp	w9, w10, [x1, #8]
	WORD	$0x5ac00923					//     rev	w3, w9
	WORD	$0x5ac0094f					//     rev	w15, w10
	WORD	$0x1e270200					//     fmov	s0, w16
	WORD	$0x4e0c1dc0					//     mov.s	v0[1], w14
	WORD	$0xb2797be9					//     mov	x9, #274877906816               ; =0x3fffffff80
	WORD	$0x8b090044					//     add	x4, x2, x9
	WORD	$0xd3669489					//     lsl	x9, x4, #26
	WORD	$0x9360fd29					//     asr	x9, x9, #32
	MOVD	$·krk(SB), R17				//     adrp	x17, _KRK@PAGE
										//     add	x17, x17, _KRK@PAGEOFF
	WORD	$0x8b091229					//     add	x9, x17, x9, lsl #4
	WORD	$0x29402d2a					//     ldp	w10, w11, [x9]
	WORD	$0x4a10014c					//     eor	w12, w10, w16
	WORD	$0x4a0e016d					//     eor	w13, w11, w14
	WORD	$0x2941252a					//     ldp	w10, w9, [x9, #8]
	WORD	$0x4a030145					//     eor	w5, w10, w3
	WORD	$0x4a0901e6					//     eor	w6, w15, w9
	WORD	$0x53187d8a					//     lsr	w10, w12, #24
	WORD	$0x4e141c60					//     mov.s	v0[2], w3
	MOVD	$·s1(SB), R9				//     adrp	x9, _S1@PAGE
										//     add	x9, x9, _S1@PAGEOFF
	WORD	$0xb86a592b					//     ldr	w11, [x9, w10, uxtw #2]
	WORD	$0x4e1c1de0					//     mov.s	v0[3], w15
	WORD	$0x53105d87					//     ubfx	w7, w12, #16, #8
	MOVD	$·s2(SB), R10				//     adrp	x10, _S2@PAGE
										//     add	x10, x10, _S2@PAGEOFF
	WORD	$0xb8675947					//     ldr	w7, [x10, w7, uxtw #2]
	WORD	$0x4a0b00e7					//     eor	w7, w7, w11
	WORD	$0x53083d93					//     ubfx	w19, w12, #8, #8
	MOVD	$·x1(SB), R11				//     adrp	x11, _X1@PAGE
										//     add	x11, x11, _X1@PAGEOFF
	WORD	$0xb8735973					//     ldr	w19, [x11, w19, uxtw #2]
	WORD	$0x12001d94					//     and	w20, w12, #0xff
	MOVD	$·x2(SB), R12				//     adrp	x12, _X2@PAGE
										//     add	x12, x12, _X2@PAGEOFF
	WORD	$0xb8745994					//     ldr	w20, [x12, w20, uxtw #2]
	WORD	$0x4a140273					//     eor	w19, w19, w20
	WORD	$0x4a1300e7					//     eor	w7, w7, w19
	WORD	$0x53187db3					//     lsr	w19, w13, #24
	WORD	$0xb8735933					//     ldr	w19, [x9, w19, uxtw #2]
	WORD	$0x53105db4					//     ubfx	w20, w13, #16, #8
	WORD	$0xb8745954					//     ldr	w20, [x10, w20, uxtw #2]
	WORD	$0x53083db5					//     ubfx	w21, w13, #8, #8
	WORD	$0xb8755975					//     ldr	w21, [x11, w21, uxtw #2]
	WORD	$0x12001dad					//     and	w13, w13, #0xff
	WORD	$0xb86d598d					//     ldr	w13, [x12, w13, uxtw #2]
	WORD	$0x4a130293					//     eor	w19, w20, w19
	WORD	$0x4a0d02ad					//     eor	w13, w21, w13
	WORD	$0x4a0d0273					//     eor	w19, w19, w13
	WORD	$0x53187cad					//     lsr	w13, w5, #24
	WORD	$0xb86d592d					//     ldr	w13, [x9, w13, uxtw #2]
	WORD	$0x53105cb4					//     ubfx	w20, w5, #16, #8
	WORD	$0xb8745954					//     ldr	w20, [x10, w20, uxtw #2]
	WORD	$0x53083cb5					//     ubfx	w21, w5, #8, #8
	WORD	$0xb8755975					//     ldr	w21, [x11, w21, uxtw #2]
	WORD	$0x4a0d028d					//     eor	w13, w20, w13
	WORD	$0x12001ca5					//     and	w5, w5, #0xff
	WORD	$0xb8655985					//     ldr	w5, [x12, w5, uxtw #2]
	WORD	$0x4a0502a5					//     eor	w5, w21, w5
	WORD	$0x4a0501a5					//     eor	w5, w13, w5
	WORD	$0x53187ccd					//     lsr	w13, w6, #24
	WORD	$0xb86d5934					//     ldr	w20, [x9, w13, uxtw #2]
	WORD	$0x53105ccd					//     ubfx	w13, w6, #16, #8
	WORD	$0xb86d5955					//     ldr	w21, [x10, w13, uxtw #2]
	WORD	$0x32009fed					//     mov	w13, #16711935                  ; =0xff00ff
	WORD	$0x4a1402b4					//     eor	w20, w21, w20
	WORD	$0x53083cd5					//     ubfx	w21, w6, #8, #8
	WORD	$0xb8755975					//     ldr	w21, [x11, w21, uxtw #2]
	WORD	$0x12001cc6					//     and	w6, w6, #0xff
	WORD	$0xb8665986					//     ldr	w6, [x12, w6, uxtw #2]
	WORD	$0x4a0602a6					//     eor	w6, w21, w6
	WORD	$0x4a060294					//     eor	w20, w20, w6
	WORD	$0x4a050273					//     eor	w19, w19, w5
	WORD	$0x4a050285					//     eor	w5, w20, w5
	WORD	$0x4a070266					//     eor	w6, w19, w7
	WORD	$0x4a130293					//     eor	w19, w20, w19
	WORD	$0x4a0600b4					//     eor	w20, w5, w6
	WORD	$0x4a0700a5					//     eor	w5, w5, w7
	WORD	$0x13944294					//     ror	w20, w20, #16
	WORD	$0x5ac008a5					//     rev	w5, w5
	WORD	$0x5ac00a67					//     rev	w7, w19
	WORD	$0x4ac54293					//     eor	w19, w20, w5, ror #16
	WORD	$0x4a070294					//     eor	w20, w20, w7
	WORD	$0x4a060275					//     eor	w21, w19, w6
	WORD	$0xf102045f					//     cmp	x2, #129
	BLO		LBB0_3						//     b.lo	LBB0_3
										// ; %bb.1:
	WORD	$0x29425825					//     ldp	w5, w22, [x1, #16]
	WORD	$0x5ac008a5					//     rev	w5, w5
	WORD	$0x5ac00ad6					//     rev	w22, w22
	WORD	$0xf103045f					//     cmp	x2, #193
	BLO		LBB0_4						//     b.lo	LBB0_4
										// ; %bb.2:
	WORD	$0x29436037					//     ldp	w23, w24, [x1, #24]
	WORD	$0x5ac00ae1					//     rev	w1, w23
	WORD	$0x5ac00b17					//     rev	w23, w24
	B		LBB0_5						//     b	LBB0_5
LBB0_3:									// LBB0_3:
	WORD	$0x52800017					//     mov	w23, #0                         ; =0x0
	WORD	$0x52800001					//     mov	w1, #0                          ; =0x0
	WORD	$0x52800016					//     mov	w22, #0                         ; =0x0
	WORD	$0x52800005					//     mov	w5, #0                          ; =0x0
	B		LBB0_5						//     b	LBB0_5
LBB0_4:									// LBB0_4:
	WORD	$0x52800017					//     mov	w23, #0                         ; =0x0
	WORD	$0x52800001					//     mov	w1, #0                          ; =0x0
LBB0_5:									// LBB0_5
	WORD	$0xd346fc98					//     lsr	x24, x4, #6
	WORD	$0x4a1500a5					//     eor	w5, w5, w21
	WORD	$0x4a1600c4					//     eor	w4, w6, w22
	WORD	$0x4a140086					//     eor	w6, w4, w20
	WORD	$0x4a010281					//     eor	w1, w20, w1
	WORD	$0x4a150021					//     eor	w1, w1, w21
	WORD	$0x4a1700e4					//     eor	w4, w7, w23
	WORD	$0x4a130084					//     eor	w4, w4, w19
	WORD	$0x71000b1f					//     cmp	w24, #2
	WORD	$0x1a9807e7					//     csinc	w7, wzr, w24, eq
	WORD	$0x8b27d233					//     add	x19, x17, w7, sxtw #4
	WORD	$0x29405674					//     ldp	w20, w21, [x19]
	WORD	$0x4a1400b4					//     eor	w20, w5, w20
	WORD	$0x4a0602b5					//     eor	w21, w21, w6
	WORD	$0x29414e76					//     ldp	w22, w19, [x19, #8]
	WORD	$0x53187e97					//     lsr	w23, w20, #24
	WORD	$0xb8775977					//     ldr	w23, [x11, w23, uxtw #2]
	WORD	$0x53105e98					//     ubfx	w24, w20, #16, #8
	WORD	$0xb8785998					//     ldr	w24, [x12, w24, uxtw #2]
	WORD	$0x4a170317					//     eor	w23, w24, w23
	WORD	$0x53083e98					//     ubfx	w24, w20, #8, #8
	WORD	$0xb8785938					//     ldr	w24, [x9, w24, uxtw #2]
	WORD	$0x12001e94					//     and	w20, w20, #0xff
	WORD	$0xb8745954					//     ldr	w20, [x10, w20, uxtw #2]
	WORD	$0x4a140314					//     eor	w20, w24, w20
	WORD	$0x4a1402f4					//     eor	w20, w23, w20
	WORD	$0x53187eb7					//     lsr	w23, w21, #24
	WORD	$0xb8775977					//     ldr	w23, [x11, w23, uxtw #2]
	WORD	$0x53105eb8					//     ubfx	w24, w21, #16, #8
	WORD	$0xb8785998					//     ldr	w24, [x12, w24, uxtw #2]
	WORD	$0x4a170317					//     eor	w23, w24, w23
	WORD	$0x53083eb8					//     ubfx	w24, w21, #8, #8
	WORD	$0xb8785938					//     ldr	w24, [x9, w24, uxtw #2]
	WORD	$0x4a0102d6					//     eor	w22, w22, w1
	WORD	$0x12001eb5					//     and	w21, w21, #0xff
	WORD	$0xb8755955					//     ldr	w21, [x10, w21, uxtw #2]
	WORD	$0x4a150315					//     eor	w21, w24, w21
	WORD	$0x4a1502f5					//     eor	w21, w23, w21
	WORD	$0x53187ed7					//     lsr	w23, w22, #24
	WORD	$0xb8775977					//     ldr	w23, [x11, w23, uxtw #2]
	WORD	$0x53105ed8					//     ubfx	w24, w22, #16, #8
	WORD	$0xb8785998					//     ldr	w24, [x12, w24, uxtw #2]
	WORD	$0x4a040273					//     eor	w19, w19, w4
	WORD	$0x4a170317					//     eor	w23, w24, w23
	WORD	$0x53083ed8					//     ubfx	w24, w22, #8, #8
	WORD	$0xb8785938					//     ldr	w24, [x9, w24, uxtw #2]
	WORD	$0x12001ed6					//     and	w22, w22, #0xff
	WORD	$0xb8765956					//     ldr	w22, [x10, w22, uxtw #2]
	WORD	$0x4a160316					//     eor	w22, w24, w22
	WORD	$0x53187e78					//     lsr	w24, w19, #24
	WORD	$0xb8785978					//     ldr	w24, [x11, w24, uxtw #2]
	WORD	$0x4a1602f6					//     eor	w22, w23, w22
	WORD	$0x53105e77					//     ubfx	w23, w19, #16, #8
	WORD	$0xb8775997					//     ldr	w23, [x12, w23, uxtw #2]
	WORD	$0x4a1802f7					//     eor	w23, w23, w24
	WORD	$0x53083e78					//     ubfx	w24, w19, #8, #8
	WORD	$0xb8785938					//     ldr	w24, [x9, w24, uxtw #2]
	WORD	$0x12001e73					//     and	w19, w19, #0xff
	WORD	$0xb8735953					//     ldr	w19, [x10, w19, uxtw #2]
	WORD	$0x4a130313					//     eor	w19, w24, w19
	WORD	$0x4a1302f3					//     eor	w19, w23, w19
	WORD	$0x4a1602b5					//     eor	w21, w21, w22
	WORD	$0x4a160276					//     eor	w22, w19, w22
	WORD	$0x4a1402b7					//     eor	w23, w21, w20
	WORD	$0x4a150273					//     eor	w19, w19, w21
	WORD	$0x4a1702d5					//     eor	w21, w22, w23
	WORD	$0x4a1402d4					//     eor	w20, w22, w20
	WORD	$0x0a132116					//     and	w22, w8, w19, lsl #8
	WORD	$0x0a5321b3					//     and	w19, w13, w19, lsr #8
	WORD	$0x2a1302d3					//     orr	w19, w22, w19
	WORD	$0x139742f6					//     ror	w22, w23, #16
	WORD	$0x5ac00a94					//     rev	w20, w20
	WORD	$0x4a150294					//     eor	w20, w20, w21
	WORD	$0x4a150275					//     eor	w21, w19, w21
	WORD	$0x4a160297					//     eor	w23, w20, w22
	WORD	$0x4a1002f0					//     eor	w16, w23, w16
	WORD	$0x4a0e02ce					//     eor	w14, w22, w14
	WORD	$0x4a1501ce					//     eor	w14, w14, w21
	WORD	$0x4a0302e3					//     eor	w3, w23, w3
	WORD	$0x4a150063					//     eor	w3, w3, w21
	WORD	$0x4a0f028f					//     eor	w15, w20, w15
	WORD	$0x4a1301ef					//     eor	w15, w15, w19
	WORD	$0x1e270201					//     fmov	s1, w16
	WORD	$0x4e0c1dc1					//     mov.s	v1[1], w14
	WORD	$0x4e141c61					//     mov.s	v1[2], w3
	WORD	$0x4e1c1de1					//     mov.s	v1[3], w15
	WORD	$0x710008ff					//     cmp	w7, #2
	WORD	$0x1a8707e7					//     csinc	w7, wzr, w7, eq
	WORD	$0x8b27d231					//     add	x17, x17, w7, sxtw #4
	WORD	$0x29404e27					//     ldp	w7, w19, [x17]
	WORD	$0x4a070210					//     eor	w16, w16, w7
	WORD	$0x4a1301ce					//     eor	w14, w14, w19
	WORD	$0x29414627					//     ldp	w7, w17, [x17, #8]
	WORD	$0x4a070063					//     eor	w3, w3, w7
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53187e11					//     lsr	w17, w16, #24
	WORD	$0xb8715931					//     ldr	w17, [x9, w17, uxtw #2]
	WORD	$0x53105e07					//     ubfx	w7, w16, #16, #8
	WORD	$0xb8675947					//     ldr	w7, [x10, w7, uxtw #2]
	WORD	$0x53083e13					//     ubfx	w19, w16, #8, #8
	WORD	$0xb8735973					//     ldr	w19, [x11, w19, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705990					//     ldr	w16, [x12, w16, uxtw #2]
	WORD	$0x4a1100f1					//     eor	w17, w7, w17
	WORD	$0x4a100270					//     eor	w16, w19, w16
	WORD	$0x4a100230					//     eor	w16, w17, w16
	WORD	$0x53187dd1					//     lsr	w17, w14, #24
	WORD	$0xb8715931					//     ldr	w17, [x9, w17, uxtw #2]
	WORD	$0x53105dc7					//     ubfx	w7, w14, #16, #8
	WORD	$0xb8675947					//     ldr	w7, [x10, w7, uxtw #2]
	WORD	$0x53083dd3					//     ubfx	w19, w14, #8, #8
	WORD	$0xb8735973					//     ldr	w19, [x11, w19, uxtw #2]
	WORD	$0x4a1100f1					//     eor	w17, w7, w17
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e598e					//     ldr	w14, [x12, w14, uxtw #2]
	WORD	$0x4a0e026e					//     eor	w14, w19, w14
	WORD	$0x4a0e022e					//     eor	w14, w17, w14
	WORD	$0x53187c71					//     lsr	w17, w3, #24
	WORD	$0xb8715931					//     ldr	w17, [x9, w17, uxtw #2]
	WORD	$0x53105c67					//     ubfx	w7, w3, #16, #8
	WORD	$0xb8675947					//     ldr	w7, [x10, w7, uxtw #2]
	WORD	$0x53083c73					//     ubfx	w19, w3, #8, #8
	WORD	$0xb8735973					//     ldr	w19, [x11, w19, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635983					//     ldr	w3, [x12, w3, uxtw #2]
	WORD	$0x4a1100f1					//     eor	w17, w7, w17
	WORD	$0x4a030263					//     eor	w3, w19, w3
	WORD	$0x4a030231					//     eor	w17, w17, w3
	WORD	$0x53187de3					//     lsr	w3, w15, #24
	WORD	$0xb8635929					//     ldr	w9, [x9, w3, uxtw #2]
	WORD	$0x53105de3					//     ubfx	w3, w15, #16, #8
	WORD	$0xb863594a					//     ldr	w10, [x10, w3, uxtw #2]
	WORD	$0x53083de3					//     ubfx	w3, w15, #8, #8
	WORD	$0xb863596b					//     ldr	w11, [x11, w3, uxtw #2]
	WORD	$0x4a090149					//     eor	w9, w10, w9
	WORD	$0x12001dea					//     and	w10, w15, #0xff
	WORD	$0xb86a598a					//     ldr	w10, [x12, w10, uxtw #2]
	WORD	$0x4a0a016a					//     eor	w10, w11, w10
	WORD	$0x4a0a0129					//     eor	w9, w9, w10
	WORD	$0x4a1101ca					//     eor	w10, w14, w17
	WORD	$0x4a11012b					//     eor	w11, w9, w17
	WORD	$0x4a10014c					//     eor	w12, w10, w16
	WORD	$0x4a0a0129					//     eor	w9, w9, w10
	WORD	$0x4a0c016a					//     eor	w10, w11, w12
	WORD	$0x4a10016b					//     eor	w11, w11, w16
	WORD	$0x0a0b2108					//     and	w8, w8, w11, lsl #8
	WORD	$0x0a4b21ab					//     and	w11, w13, w11, lsr #8
	WORD	$0x2a0b0108					//     orr	w8, w8, w11
	WORD	$0x138a414a					//     ror	w10, w10, #16
	WORD	$0x5ac00929					//     rev	w9, w9
	WORD	$0x4a0a0108					//     eor	w8, w8, w10
	WORD	$0x4a09014a					//     eor	w10, w10, w9
	WORD	$0x4a0c010b					//     eor	w11, w8, w12
	WORD	$0x4a090108					//     eor	w8, w8, w9
	WORD	$0x4a0a0169					//     eor	w9, w11, w10
	WORD	$0x4a0c014a					//     eor	w10, w10, w12
	WORD	$0x4a05016c					//     eor	w12, w11, w5
	WORD	$0x1e270162					//     fmov	s2, w11
	WORD	$0x4e0c1d42					//     mov.s	v2[1], w10
	WORD	$0x4e141d22					//     mov.s	v2[2], w9
	WORD	$0x4e1c1d02					//     mov.s	v2[3], w8
	WORD	$0x4a06014a					//     eor	w10, w10, w6
	WORD	$0x1e270183					//     fmov	s3, w12
	WORD	$0x4e0c1d43					//     mov.s	v3[1], w10
	WORD	$0x4a010129					//     eor	w9, w9, w1
	WORD	$0x4e141d23					//     mov.s	v3[2], w9
	WORD	$0x4a040108					//     eor	w8, w8, w4
	WORD	$0x4e1c1d03					//     mov.s	v3[3], w8
	WORD	$0x6e016024					//     ext.16b	v4, v1, v1, #12
	WORD	$0x6f2d0425					//     ushr.4s	v5, v1, #19
	WORD	$0x4f2d5486					//     shl.4s	v6, v4, #13
	WORD	$0x4ea51cc5					//     orr.16b	v5, v6, v5
	WORD	$0x6e036066					//     ext.16b	v6, v3, v3, #12
	WORD	$0x6f2d0467					//     ushr.4s	v7, v3, #19
	WORD	$0x4f2d54d0					//     shl.4s	v16, v6, #13
	WORD	$0x4ea71e07					//     orr.16b	v7, v16, v7
	WORD	$0x6e026050					//     ext.16b	v16, v2, v2, #12
	WORD	$0x6f2d0451					//     ushr.4s	v17, v2, #19
	WORD	$0x4f2d5612					//     shl.4s	v18, v16, #13
	WORD	$0x4eb11e51					//     orr.16b	v17, v18, v17
	WORD	$0x6e006012					//     ext.16b	v18, v0, v0, #12
	WORD	$0x6f2d0413					//     ushr.4s	v19, v0, #19
	WORD	$0x4f2d5654					//     shl.4s	v20, v18, #13
	WORD	$0x4eb31e93					//     orr.16b	v19, v20, v19
	WORD	$0x6f210434					//     ushr.4s	v20, v1, #31
	WORD	$0x4ea48484					//     add.4s	v4, v4, v4
	WORD	$0x4eb41c84					//     orr.16b	v4, v4, v20
	WORD	$0x6f210474					//     ushr.4s	v20, v3, #31
	WORD	$0x4ea684c6					//     add.4s	v6, v6, v6
	WORD	$0x4eb41cc6					//     orr.16b	v6, v6, v20
	WORD	$0x6f210454					//     ushr.4s	v20, v2, #31
	WORD	$0x4eb08610					//     add.4s	v16, v16, v16
	WORD	$0x4eb41e10					//     orr.16b	v16, v16, v20
	WORD	$0x6f210414					//     ushr.4s	v20, v0, #31
	WORD	$0x4eb28652					//     add.4s	v18, v18, v18
	WORD	$0x4eb41e52					//     orr.16b	v18, v18, v20
	WORD	$0x6e201ca5					//     eor.16b	v5, v5, v0
	WORD	$0x6e211ce7					//     eor.16b	v7, v7, v1
	WORD	$0x6e231e31					//     eor.16b	v17, v17, v3
	WORD	$0x6e331c53					//     eor.16b	v19, v2, v19
	WORD	$0x6e201c84					//     eor.16b	v4, v4, v0
	WORD	$0x6e211cc6					//     eor.16b	v6, v6, v1
	WORD	$0x6e231e10					//     eor.16b	v16, v16, v3
	WORD	$0x6e321c52					//     eor.16b	v18, v2, v18
	WORD	$0xad001c05					//     stp	q5, q7, [x0]
	WORD	$0x6f3d0425					//     ushr.4s	v5, v1, #3
	WORD	$0xad014c11					//     stp	q17, q19, [x0, #32]
	WORD	$0xad021804					//     stp	q4, q6, [x0, #64]
	WORD	$0xad034810					//     stp	q16, q18, [x0, #96]
	WORD	$0x6e0540a5					//     ext.16b	v5, v5, v5, #8
	WORD	$0x6e012024					//     ext.16b	v4, v1, v1, #4
	WORD	$0x4f3d5486					//     shl.4s	v6, v4, #29
	WORD	$0x4ea51cc5					//     orr.16b	v5, v6, v5
	WORD	$0x6e201ca5					//     eor.16b	v5, v5, v0
	WORD	$0x6f3d0466					//     ushr.4s	v6, v3, #3
	WORD	$0x6e0640c7					//     ext.16b	v7, v6, v6, #8
	WORD	$0x6e032066					//     ext.16b	v6, v3, v3, #4
	WORD	$0x4f3d54d0					//     shl.4s	v16, v6, #29
	WORD	$0x4ea71e07					//     orr.16b	v7, v16, v7
	WORD	$0x6e211ce7					//     eor.16b	v7, v7, v1
	WORD	$0xad041c05					//     stp	q5, q7, [x0, #128]
	WORD	$0x6f3d0445					//     ushr.4s	v5, v2, #3
	WORD	$0x6e0540a5					//     ext.16b	v5, v5, v5, #8
	WORD	$0x6e022047					//     ext.16b	v7, v2, v2, #4
	WORD	$0x4f3d54f0					//     shl.4s	v16, v7, #29
	WORD	$0x4ea51e10					//     orr.16b	v16, v16, v5
	WORD	$0x6f3d0405					//     ushr.4s	v5, v0, #3
	WORD	$0x6e0540b1					//     ext.16b	v17, v5, v5, #8
	WORD	$0x6e002005					//     ext.16b	v5, v0, v0, #4
	WORD	$0x4f3d54b2					//     shl.4s	v18, v5, #29
	WORD	$0x4eb11e51					//     orr.16b	v17, v18, v17
	WORD	$0x6e231e10					//     eor.16b	v16, v16, v3
	WORD	$0x6e311c51					//     eor.16b	v17, v2, v17
	WORD	$0xad054410					//     stp	q16, q17, [x0, #160]
	WORD	$0x4f3f5430					//     shl.4s	v16, v1, #31
	WORD	$0x6f3f0491					//     ushr.4s	v17, v4, #1
	WORD	$0x4eb11e10					//     orr.16b	v16, v16, v17
	WORD	$0x6e201e10					//     eor.16b	v16, v16, v0
	WORD	$0x3d803010					//     str	q16, [x0, #192]
	WORD	$0x7100445f					//     cmp	w2, #17
	BLO		LBB0_8						//     b.lo	LBB0_8
										// ; %bb.6:
	WORD	$0x6f3f04c6					//     ushr.4s	v6, v6, #1
	WORD	$0x4f3f5470					//     shl.4s	v16, v3, #31
	WORD	$0x4ea61e06					//     orr.16b	v6, v16, v6
	WORD	$0x6e211cc6					//     eor.16b	v6, v6, v1
	WORD	$0x6f3f04e7					//     ushr.4s	v7, v7, #1
	WORD	$0x4f3f5450					//     shl.4s	v16, v2, #31
	WORD	$0x4ea71e07					//     orr.16b	v7, v16, v7
	WORD	$0x6e231ce3					//     eor.16b	v3, v7, v3
	WORD	$0xad068c06					//     stp	q6, q3, [x0, #208]
	WORD	$0x7100645f					//     cmp	w2, #25
	BLO		LBB0_8						//     b.lo	LBB0_8
										// ; %bb.7:
	WORD	$0x6f3f04a3					//     ushr.4s	v3, v5, #1
	WORD	$0x4f3f5405					//     shl.4s	v5, v0, #31
	WORD	$0x4ea31ca3					//     orr.16b	v3, v5, v3
	WORD	$0x6e231c42					//     eor.16b	v2, v2, v3
	WORD	$0x6f330483					//     ushr.4s	v3, v4, #13
	WORD	$0x4f335421					//     shl.4s	v1, v1, #19
	WORD	$0x4ea31c21					//     orr.16b	v1, v1, v3
	WORD	$0x6e201c20					//     eor.16b	v0, v1, v0
	WORD	$0xad078002					//     stp	q2, q0, [x0, #240]
LBB0_8:									// LBB0_8:
	WORD	$0xa9437bfd					//     ldp	x29, x30, [sp, #48]             ; 16-byte Folded Reload
	WORD	$0xa9424ff4					//     ldp	x20, x19, [sp, #32]             ; 16-byte Folded Reload
	WORD	$0xa94157f6					//     ldp	x22, x21, [sp, #16]             ; 16-byte Folded Reload
	WORD	$0xa8c45ff8					//     ldp	x24, x23, [sp], #64             ; 16-byte Folded Reload
	RET									//     ret

TEXT ·__initDecKey_NEON(SB), NOSPLIT, $0-24
	MOVD	rk+0(FP), R0
	MOVD	key+8(FP), R1
	MOVD	keyBits+16(FP), R2

										// ; %bb.0:
	WORD	$0x32089fe8					//     mov	w8, #-16711936                  ; =0xff00ff00
	WORD	$0x32009fe9					//     mov	w9, #16711935                   ; =0xff00ff
	WORD	$0xd345fc4a					//     lsr	x10, x2, #5
	WORD	$0xd2c0040b					//     mov	x11, #137438953472              ; =0x2000000000
	WORD	$0x8b0a896b					//     add	x11, x11, x10, lsl #34
	WORD	$0x8b8b780c					//     add	x12, x0, x11, asr #30
	WORD	$0xb940018a					//     ldr	w10, [x12]
	WORD	$0x3dc00000					//     ldr	q0, [x0]
	WORD	$0xb900000a					//     str	w10, [x0]
	WORD	$0xb940058a					//     ldr	w10, [x12, #4]
	WORD	$0xb900040a					//     str	w10, [x0, #4]
	WORD	$0xb940098a					//     ldr	w10, [x12, #8]
	WORD	$0xb900080a					//     str	w10, [x0, #8]
	WORD	$0xb9400d8a					//     ldr	w10, [x12, #12]
	WORD	$0xb9000c0a					//     str	w10, [x0, #12]
	WORD	$0x3d800180					//     str	q0, [x12]
	WORD	$0xd280002a					//     mov	x10, #1                         ; =0x1
	WORD	$0xf2c0010a					//     movk	x10, #8, lsl #32
	WORD	$0xeb0a017f					//     cmp	x11, x10
	BLT		LBB1_4						//     b.lt	LBB1_4
										// ; %bb.1:
	WORD	$0xd280000a					//     mov	x10, #0                         ; =0x0
	WORD	$0x9360fd6b					//     asr	x11, x11, #32
	WORD	$0xd37ef56b					//     lsl	x11, x11, #2
LBB1_2:									// LBB1_2:                                 ; =>This Inner Loop Header: Depth=1
	WORD	$0x8b0a000c					//     add	x12, x0, x10
	WORD	$0x29423d8e					//     ldp	w14, w15, [x12, #16]
	WORD	$0x53185dd0					//     lsl	w16, w14, #8
	WORD	$0x8b0b000d					//     add	x13, x0, x11
	WORD	$0x4a4e2210					//     eor	w16, w16, w14, lsr #8
	WORD	$0x4a0e4210					//     eor	w16, w16, w14, lsl #16
	WORD	$0x4a4e4210					//     eor	w16, w16, w14, lsr #16
	WORD	$0x4a0e6210					//     eor	w16, w16, w14, lsl #24
	WORD	$0x4a4e620e					//     eor	w14, w16, w14, lsr #24
	WORD	$0x53185df0					//     lsl	w16, w15, #8
	WORD	$0x4a4f2210					//     eor	w16, w16, w15, lsr #8
	WORD	$0x4a0f4210					//     eor	w16, w16, w15, lsl #16
	WORD	$0x4a4f4210					//     eor	w16, w16, w15, lsr #16
	WORD	$0x4a0f6210					//     eor	w16, w16, w15, lsl #24
	WORD	$0x4a4f620f					//     eor	w15, w16, w15, lsr #24
	WORD	$0x29434590					//     ldp	w16, w17, [x12, #24]
	WORD	$0x53185e01					//     lsl	w1, w16, #8
	WORD	$0x4a502021					//     eor	w1, w1, w16, lsr #8
	WORD	$0x4a104021					//     eor	w1, w1, w16, lsl #16
	WORD	$0x4a504021					//     eor	w1, w1, w16, lsr #16
	WORD	$0x4a106021					//     eor	w1, w1, w16, lsl #24
	WORD	$0x4a506030					//     eor	w16, w1, w16, lsr #24
	WORD	$0x53185e21					//     lsl	w1, w17, #8
	WORD	$0x4a512021					//     eor	w1, w1, w17, lsr #8
	WORD	$0x4a114021					//     eor	w1, w1, w17, lsl #16
	WORD	$0x4a514021					//     eor	w1, w1, w17, lsr #16
	WORD	$0x4a116021					//     eor	w1, w1, w17, lsl #24
	WORD	$0x4a516031					//     eor	w17, w1, w17, lsr #24
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x4a100230					//     eor	w16, w17, w16
	WORD	$0x4a0e01e1					//     eor	w1, w15, w14
	WORD	$0x4a0f022f					//     eor	w15, w17, w15
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0e020e					//     eor	w14, w16, w14
	WORD	$0x0a0e2110					//     and	w16, w8, w14, lsl #8
	WORD	$0x0a4e212e					//     and	w14, w9, w14, lsr #8
	WORD	$0x2a0e020e					//     orr	w14, w16, w14
	WORD	$0x13914230					//     ror	w16, w17, #16
	WORD	$0x5ac009ef					//     rev	w15, w15
	WORD	$0x4a1001ce					//     eor	w14, w14, w16
	WORD	$0x4a0f0210					//     eor	w16, w16, w15
	WORD	$0x4a0101d1					//     eor	w17, w14, w1
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x4a10022f					//     eor	w15, w17, w16
	WORD	$0x4a010210					//     eor	w16, w16, w1
	WORD	$0x297e09a1					//     ldp	w1, w2, [x13, #-16]
	WORD	$0x53185c43					//     lsl	w3, w2, #8
	WORD	$0x4a422063					//     eor	w3, w3, w2, lsr #8
	WORD	$0x4a024063					//     eor	w3, w3, w2, lsl #16
	WORD	$0x4a424063					//     eor	w3, w3, w2, lsr #16
	WORD	$0x4a026063					//     eor	w3, w3, w2, lsl #24
	WORD	$0x4a426062					//     eor	w2, w3, w2, lsr #24
	WORD	$0x297f11a3					//     ldp	w3, w4, [x13, #-8]
	WORD	$0x53185c65					//     lsl	w5, w3, #8
	WORD	$0x4a4320a5					//     eor	w5, w5, w3, lsr #8
	WORD	$0x4a0340a5					//     eor	w5, w5, w3, lsl #16
	WORD	$0x4a4340a5					//     eor	w5, w5, w3, lsr #16
	WORD	$0x4a0360a5					//     eor	w5, w5, w3, lsl #24
	WORD	$0x4a4360a3					//     eor	w3, w5, w3, lsr #24
	WORD	$0x53185c85					//     lsl	w5, w4, #8
	WORD	$0x4a4420a5					//     eor	w5, w5, w4, lsr #8
	WORD	$0x4a0440a5					//     eor	w5, w5, w4, lsl #16
	WORD	$0x4a4440a5					//     eor	w5, w5, w4, lsr #16
	WORD	$0x4a030042					//     eor	w2, w2, w3
	WORD	$0x4a0460a5					//     eor	w5, w5, w4, lsl #24
	WORD	$0x4a4460a4					//     eor	w4, w5, w4, lsr #24
	WORD	$0x4a030083					//     eor	w3, w4, w3
	WORD	$0x53185c25					//     lsl	w5, w1, #8
	WORD	$0x4a4120a5					//     eor	w5, w5, w1, lsr #8
	WORD	$0x4a0140a5					//     eor	w5, w5, w1, lsl #16
	WORD	$0x4a4140a5					//     eor	w5, w5, w1, lsr #16
	WORD	$0x4a0160a5					//     eor	w5, w5, w1, lsl #24
	WORD	$0x4a4160a1					//     eor	w1, w5, w1, lsr #24
	WORD	$0x4a010045					//     eor	w5, w2, w1
	WORD	$0x4a020082					//     eor	w2, w4, w2
	WORD	$0x4a050064					//     eor	w4, w3, w5
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x0a012103					//     and	w3, w8, w1, lsl #8
	WORD	$0x0a412121					//     and	w1, w9, w1, lsr #8
	WORD	$0x2a010061					//     orr	w1, w3, w1
	WORD	$0x5ac00842					//     rev	w2, w2
	WORD	$0x13844083					//     ror	w3, w4, #16
	WORD	$0x4a030021					//     eor	w1, w1, w3
	WORD	$0x4a020063					//     eor	w3, w3, w2
	WORD	$0x4a050024					//     eor	w4, w1, w5
	WORD	$0x4a020021					//     eor	w1, w1, w2
	WORD	$0x4a030082					//     eor	w2, w4, w3
	WORD	$0x4a050063					//     eor	w3, w3, w5
	WORD	$0x29020d84					//     stp	w4, w3, [x12, #16]
	WORD	$0x29030582					//     stp	w2, w1, [x12, #24]
	WORD	$0x293e41b1					//     stp	w17, w16, [x13, #-16]
	WORD	$0x293f39af					//     stp	w15, w14, [x13, #-8]
	WORD	$0x9100818e					//     add	x14, x12, #32
	WORD	$0xd100416b					//     sub	x11, x11, #16
	WORD	$0x9100414a					//     add	x10, x10, #16
	WORD	$0x8b0b000c					//     add	x12, x0, x11
	WORD	$0xd100418d					//     sub	x13, x12, #16
	WORD	$0xeb0d01df					//     cmp	x14, x13
	BLO		LBB1_2						//     b.lo	LBB1_2
										// ; %bb.3:
	WORD	$0x8b0a0000					//     add	x0, x0, x10
	WORD	$0x9100400a					//     add	x10, x0, #16
	B		LBB1_5						//     b	LBB1_5
LBB1_4:									// LBB1_4:
	WORD	$0x9100400a					//     add	x10, x0, #16
	WORD	$0xd100418d					//     sub	x13, x12, #16
LBB1_5:									// LBB1_5:
	WORD	$0xa9bf7bfd					//     stp	x29, x30, [sp, #-16]!           ; 16-byte Folded Spill
	WORD	$0x910003fd					//     mov	x29, sp
	WORD	$0x2942b80b					//     ldp	w11, w14, [x0, #20]
	WORD	$0x53185d6f					//     lsl	w15, w11, #8
	WORD	$0xb940014a					//     ldr	w10, [x10]
	WORD	$0x4a4b21ef					//     eor	w15, w15, w11, lsr #8
	WORD	$0x4a0b41ef					//     eor	w15, w15, w11, lsl #16
	WORD	$0x4a4b41ef					//     eor	w15, w15, w11, lsr #16
	WORD	$0x4a0b61ef					//     eor	w15, w15, w11, lsl #24
	WORD	$0x4a4b61eb					//     eor	w11, w15, w11, lsr #24
	WORD	$0x53185dcf					//     lsl	w15, w14, #8
	WORD	$0x4a4e21ef					//     eor	w15, w15, w14, lsr #8
	WORD	$0x4a0e41ef					//     eor	w15, w15, w14, lsl #16
	WORD	$0x4a4e41ef					//     eor	w15, w15, w14, lsr #16
	WORD	$0x4a0e61ef					//     eor	w15, w15, w14, lsl #24
	WORD	$0x4a4e61ee					//     eor	w14, w15, w14, lsr #24
	WORD	$0xb9401c0f					//     ldr	w15, [x0, #28]
	WORD	$0x53185df0					//     lsl	w16, w15, #8
	WORD	$0x4a4f2210					//     eor	w16, w16, w15, lsr #8
	WORD	$0x4a0f4210					//     eor	w16, w16, w15, lsl #16
	WORD	$0x4a4f4210					//     eor	w16, w16, w15, lsr #16
	WORD	$0x4a0f6210					//     eor	w16, w16, w15, lsl #24
	WORD	$0x4a4f620f					//     eor	w15, w16, w15, lsr #24
	WORD	$0x53185d50					//     lsl	w16, w10, #8
	WORD	$0x4a4a2210					//     eor	w16, w16, w10, lsr #8
	WORD	$0x4a0a4210					//     eor	w16, w16, w10, lsl #16
	WORD	$0x4a4a4210					//     eor	w16, w16, w10, lsr #16
	WORD	$0x4a0a6210					//     eor	w16, w16, w10, lsl #24
	WORD	$0x4a0e016b					//     eor	w11, w11, w14
	WORD	$0x4a0e01ee					//     eor	w14, w15, w14
	WORD	$0x4a4a620a					//     eor	w10, w16, w10, lsr #24
	WORD	$0x4a0a0170					//     eor	w16, w11, w10
	WORD	$0x4a0b01eb					//     eor	w11, w15, w11
	WORD	$0x4a1001cf					//     eor	w15, w14, w16
	WORD	$0x4a0a01ca					//     eor	w10, w14, w10
	WORD	$0x0a0a2108					//     and	w8, w8, w10, lsl #8
	WORD	$0x0a4a2129					//     and	w9, w9, w10, lsr #8
	WORD	$0x2a090108					//     orr	w8, w8, w9
	WORD	$0x5ac00969					//     rev	w9, w11
	WORD	$0x138f41ea					//     ror	w10, w15, #16
	WORD	$0x4a0a0108					//     eor	w8, w8, w10
	WORD	$0x4a09014a					//     eor	w10, w10, w9
	WORD	$0x4a10010b					//     eor	w11, w8, w16
	WORD	$0x4a090108					//     eor	w8, w8, w9
	WORD	$0x4a0a0169					//     eor	w9, w11, w10
	WORD	$0xb90001ab					//     str	w11, [x13]
	WORD	$0x4a10014a					//     eor	w10, w10, w16
	WORD	$0x293ea58a					//     stp	w10, w9, [x12, #-12]
	WORD	$0xb81fc188					//     stur	w8, [x12, #-4]
	WORD	$0xa8c17bfd					//     ldp	x29, x30, [sp], #16             ; 16-byte Folded Reload
	RET									//     ret


TEXT ·__process_NEON(SB), NOSPLIT, $0-32
	MOVD	dst+0(FP), R0
	MOVD	src+8(FP), R1
	MOVD	rk+16(FP), R2
	MOVD	rounds+24(FP), R3

										// ; %bb.0:
	WORD	$0xa9bf7bfd					//     stp	x29, x30, [sp, #-16]!           ; 16-byte Folded Spill
	WORD	$0x910003fd					//     mov	x29, sp
	WORD	$0x32089fec					//     mov	w12, #-16711936                 ; =0xff00ff00
	WORD	$0x32009fed					//     mov	w13, #16711935                  ; =0xff00ff
	WORD	$0x29402428					//     ldp	w8, w9, [x1]
	WORD	$0x5ac00910					//     rev	w16, w8
	WORD	$0x5ac00931					//     rev	w17, w9
	WORD	$0x29412828					//     ldp	w8, w10, [x1, #8]
	WORD	$0x5ac0090f					//     rev	w15, w8
	MOVD	$·s1(SB), R9				//     adrp	x9, _S1@PAGE
										//     add	x9, x9, _S1@PAGEOFF
	MOVD	$·s2(SB), R8				//     adrp	x8, _S2@PAGE
										//     add	x8, x8, _S2@PAGEOFF
	WORD	$0x5ac0094e					//     rev	w14, w10
	MOVD	$·x1(SB), R11				//     adrp	x11, _X1@PAGE
										//     add	x11, x11, _X1@PAGEOFF
	MOVD	$·x2(SB), R10				//     adrp	x10, _X2@PAGE
										//     add	x10, x10, _X2@PAGEOFF
	WORD	$0xf100347f					//     cmp	x3, #13
	BLO		LBB2_4						//     b.lo	LBB2_4
										// ; %bb.1:
	WORD	$0x29401041					//     ldp	w1, w4, [x2]
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x4a110091					//     eor	w17, w4, w17
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x29411444					//     ldp	w4, w5, [x2, #8]
	WORD	$0x4a0f008f					//     eor	w15, w4, w15
	WORD	$0x4a0e00ae					//     eor	w14, w5, w14
	WORD	$0x53105e04					//     ubfx	w4, w16, #16, #8
	WORD	$0xb8645904					//     ldr	w4, [x8, w4, uxtw #2]
	WORD	$0x53083e05					//     ubfx	w5, w16, #8, #8
	WORD	$0xb8655965					//     ldr	w5, [x11, w5, uxtw #2]
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705950					//     ldr	w16, [x10, w16, uxtw #2]
	WORD	$0x4a1000b0					//     eor	w16, w5, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187e21					//     lsr	w1, w17, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e24					//     ubfx	w4, w17, #16, #8
	WORD	$0xb8645904					//     ldr	w4, [x8, w4, uxtw #2]
	WORD	$0x53083e25					//     ubfx	w5, w17, #8, #8
	WORD	$0xb8655965					//     ldr	w5, [x11, w5, uxtw #2]
	WORD	$0x12001e31					//     and	w17, w17, #0xff
	WORD	$0xb8715951					//     ldr	w17, [x10, w17, uxtw #2]
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a1100b1					//     eor	w17, w5, w17
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x53187de1					//     lsr	w1, w15, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105de4					//     ubfx	w4, w15, #16, #8
	WORD	$0xb8645904					//     ldr	w4, [x8, w4, uxtw #2]
	WORD	$0x53083de5					//     ubfx	w5, w15, #8, #8
	WORD	$0xb8655965					//     ldr	w5, [x11, w5, uxtw #2]
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x12001def					//     and	w15, w15, #0xff
	WORD	$0xb86f594f					//     ldr	w15, [x10, w15, uxtw #2]
	WORD	$0x4a0f00af					//     eor	w15, w5, w15
	WORD	$0x4a0f002f					//     eor	w15, w1, w15
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105dc4					//     ubfx	w4, w14, #16, #8
	WORD	$0xb8645904					//     ldr	w4, [x8, w4, uxtw #2]
	WORD	$0x53083dc5					//     ubfx	w5, w14, #8, #8
	WORD	$0xb8655965					//     ldr	w5, [x11, w5, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e594e					//     ldr	w14, [x10, w14, uxtw #2]
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a0e00ae					//     eor	w14, w5, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a0f0231					//     eor	w17, w17, w15
	WORD	$0x4a0f01cf					//     eor	w15, w14, w15
	WORD	$0x4a100221					//     eor	w1, w17, w16
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a0101f1					//     eor	w17, w15, w1
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x0a0f2190					//     and	w16, w12, w15, lsl #8
	WORD	$0x0a4f21af					//     and	w15, w13, w15, lsr #8
	WORD	$0x2a0f020f					//     orr	w15, w16, w15
	WORD	$0x13914230					//     ror	w16, w17, #16
	WORD	$0x5ac009ce					//     rev	w14, w14
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x4a0e0210					//     eor	w16, w16, w14
	WORD	$0x29421051					//     ldp	w17, w4, [x2, #16]
	WORD	$0x4a010084					//     eor	w4, w4, w1
	WORD	$0x4a100084					//     eor	w4, w4, w16
	WORD	$0x29431845					//     ldp	w5, w6, [x2, #24]
	WORD	$0x4a050210					//     eor	w16, w16, w5
	WORD	$0x4a0101e1					//     eor	w1, w15, w1
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x4a010210					//     eor	w16, w16, w1
	WORD	$0x53187e21					//     lsr	w1, w17, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x4a0e00ce					//     eor	w14, w6, w14
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x53105e2f					//     ubfx	w15, w17, #16, #8
	WORD	$0xb86f594f					//     ldr	w15, [x10, w15, uxtw #2]
	WORD	$0x4a0101ef					//     eor	w15, w15, w1
	WORD	$0x53083e21					//     ubfx	w1, w17, #8, #8
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x12001e31					//     and	w17, w17, #0xff
	WORD	$0xb8715911					//     ldr	w17, [x8, w17, uxtw #2]
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53187c91					//     lsr	w17, w4, #24
	WORD	$0xb8715971					//     ldr	w17, [x11, w17, uxtw #2]
	WORD	$0x53105c81					//     ubfx	w1, w4, #16, #8
	WORD	$0xb8615941					//     ldr	w1, [x10, w1, uxtw #2]
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x53083c81					//     ubfx	w1, w4, #8, #8
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x12001c84					//     and	w4, w4, #0xff
	WORD	$0xb8645904					//     ldr	w4, [x8, w4, uxtw #2]
	WORD	$0x4a040021					//     eor	w1, w1, w4
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105e04					//     ubfx	w4, w16, #16, #8
	WORD	$0xb8645944					//     ldr	w4, [x10, w4, uxtw #2]
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x53083e04					//     ubfx	w4, w16, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705910					//     ldr	w16, [x8, w16, uxtw #2]
	WORD	$0x4a100090					//     eor	w16, w4, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105dc4					//     ubfx	w4, w14, #16, #8
	WORD	$0xb8645944					//     ldr	w4, [x10, w4, uxtw #2]
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x53083dc4					//     ubfx	w4, w14, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e590e					//     ldr	w14, [x8, w14, uxtw #2]
	WORD	$0x4a0e008e					//     eor	w14, w4, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a100231					//     eor	w17, w17, w16
	WORD	$0x4a1001d0					//     eor	w16, w14, w16
	WORD	$0x4a0f0221					//     eor	w1, w17, w15
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0f020f					//     eor	w15, w16, w15
	WORD	$0x0a0e2190					//     and	w16, w12, w14, lsl #8
	WORD	$0x0a4e21ae					//     and	w14, w13, w14, lsr #8
	WORD	$0x2a0e020e					//     orr	w14, w16, w14
	WORD	$0x13814021					//     ror	w1, w1, #16
	WORD	$0x5ac009ef					//     rev	w15, w15
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a1101d1					//     eor	w17, w14, w17
	WORD	$0x4a0101f0					//     eor	w16, w15, w1
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x4a10022f					//     eor	w15, w17, w16
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0xf1003c7f					//     cmp	x3, #15
	BLO		LBB2_3						//     b.lo	LBB2_3
										// ; %bb.2:
	WORD	$0x29440c41					//     ldp	w1, w3, [x2, #32]
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x4a110071					//     eor	w17, w3, w17
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x29451043					//     ldp	w3, w4, [x2, #40]
	WORD	$0x4a0f006f					//     eor	w15, w3, w15
	WORD	$0x4a0e008e					//     eor	w14, w4, w14
	WORD	$0x53105e03					//     ubfx	w3, w16, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083e04					//     ubfx	w4, w16, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705950					//     ldr	w16, [x10, w16, uxtw #2]
	WORD	$0x4a100090					//     eor	w16, w4, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187e21					//     lsr	w1, w17, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e23					//     ubfx	w3, w17, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083e24					//     ubfx	w4, w17, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x12001e31					//     and	w17, w17, #0xff
	WORD	$0xb8715951					//     ldr	w17, [x10, w17, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x4a110091					//     eor	w17, w4, w17
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x53187de1					//     lsr	w1, w15, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105de3					//     ubfx	w3, w15, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083de4					//     ubfx	w4, w15, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x12001def					//     and	w15, w15, #0xff
	WORD	$0xb86f594f					//     ldr	w15, [x10, w15, uxtw #2]
	WORD	$0x4a0f008f					//     eor	w15, w4, w15
	WORD	$0x4a0f002f					//     eor	w15, w1, w15
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105dc3					//     ubfx	w3, w14, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083dc4					//     ubfx	w4, w14, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e594e					//     ldr	w14, [x10, w14, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x4a0e008e					//     eor	w14, w4, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a0f0231					//     eor	w17, w17, w15
	WORD	$0x4a0f01cf					//     eor	w15, w14, w15
	WORD	$0x4a100221					//     eor	w1, w17, w16
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a0101f1					//     eor	w17, w15, w1
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x0a0f2190					//     and	w16, w12, w15, lsl #8
	WORD	$0x0a4f21af					//     and	w15, w13, w15, lsr #8
	WORD	$0x2a0f020f					//     orr	w15, w16, w15
	WORD	$0x13914230					//     ror	w16, w17, #16
	WORD	$0x5ac009ce					//     rev	w14, w14
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x4a0e0210					//     eor	w16, w16, w14
	WORD	$0x29460c51					//     ldp	w17, w3, [x2, #48]
	WORD	$0x4a010063					//     eor	w3, w3, w1
	WORD	$0x4a100063					//     eor	w3, w3, w16
	WORD	$0x29471444					//     ldp	w4, w5, [x2, #56]
	WORD	$0x4a040210					//     eor	w16, w16, w4
	WORD	$0x4a0101e1					//     eor	w1, w15, w1
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x4a010210					//     eor	w16, w16, w1
	WORD	$0x53187e21					//     lsr	w1, w17, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x4a0e00ae					//     eor	w14, w5, w14
	WORD	$0x53105e24					//     ubfx	w4, w17, #16, #8
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x91010042					//     add	x2, x2, #64
	WORD	$0xb864594f					//     ldr	w15, [x10, w4, uxtw #2]
	WORD	$0x53083e24					//     ubfx	w4, w17, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x12001e31					//     and	w17, w17, #0xff
	WORD	$0xb8715911					//     ldr	w17, [x8, w17, uxtw #2]
	WORD	$0x4a0101ef					//     eor	w15, w15, w1
	WORD	$0x4a110091					//     eor	w17, w4, w17
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53187c71					//     lsr	w17, w3, #24
	WORD	$0xb8715971					//     ldr	w17, [x11, w17, uxtw #2]
	WORD	$0x53105c61					//     ubfx	w1, w3, #16, #8
	WORD	$0xb8615941					//     ldr	w1, [x10, w1, uxtw #2]
	WORD	$0x53083c64					//     ubfx	w4, w3, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x12001c61					//     and	w1, w3, #0xff
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105e03					//     ubfx	w3, w16, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x53083e04					//     ubfx	w4, w16, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705910					//     ldr	w16, [x8, w16, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x4a100090					//     eor	w16, w4, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105dc3					//     ubfx	w3, w14, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x53083dc4					//     ubfx	w4, w14, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e590e					//     ldr	w14, [x8, w14, uxtw #2]
	WORD	$0x4a0e008e					//     eor	w14, w4, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a100231					//     eor	w17, w17, w16
	WORD	$0x4a1001d0					//     eor	w16, w14, w16
	WORD	$0x4a0f0221					//     eor	w1, w17, w15
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0f020f					//     eor	w15, w16, w15
	WORD	$0x0a0e2190					//     and	w16, w12, w14, lsl #8
	WORD	$0x0a4e21ae					//     and	w14, w13, w14, lsr #8
	WORD	$0x2a0e020e					//     orr	w14, w16, w14
	WORD	$0x13814021					//     ror	w1, w1, #16
	WORD	$0x5ac009ef					//     rev	w15, w15
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a1101d1					//     eor	w17, w14, w17
	WORD	$0x4a0101f0					//     eor	w16, w15, w1
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x4a10022f					//     eor	w15, w17, w16
	WORD	$0x4a010231					//     eor	w17, w17, w1
	B		LBB2_4						//     b	LBB2_4
LBB2_3:									// LBB2_3:
	WORD	$0x91008042					//     add	x2, x2, #32
LBB2_4:									// LBB2_4:
	WORD	$0x29400c41					//     ldp	w1, w3, [x2]
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x4a110071					//     eor	w17, w3, w17
	WORD	$0x29410c41					//     ldp	w1, w3, [x2, #8]
	WORD	$0x4a0f002f					//     eor	w15, w1, w15
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e03					//     ubfx	w3, w16, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083e03					//     ubfx	w3, w16, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705950					//     ldr	w16, [x10, w16, uxtw #2]
	WORD	$0x4a100070					//     eor	w16, w3, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187e21					//     lsr	w1, w17, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e23					//     ubfx	w3, w17, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083e23					//     ubfx	w3, w17, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001e31					//     and	w17, w17, #0xff
	WORD	$0xb8715951					//     ldr	w17, [x10, w17, uxtw #2]
	WORD	$0x4a110071					//     eor	w17, w3, w17
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x53187de1					//     lsr	w1, w15, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105de3					//     ubfx	w3, w15, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083de3					//     ubfx	w3, w15, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001def					//     and	w15, w15, #0xff
	WORD	$0xb86f594f					//     ldr	w15, [x10, w15, uxtw #2]
	WORD	$0x4a0f006f					//     eor	w15, w3, w15
	WORD	$0x4a0f002f					//     eor	w15, w1, w15
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105dc3					//     ubfx	w3, w14, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083dc3					//     ubfx	w3, w14, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e594e					//     ldr	w14, [x10, w14, uxtw #2]
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a0f0231					//     eor	w17, w17, w15
	WORD	$0x4a0f01cf					//     eor	w15, w14, w15
	WORD	$0x4a100221					//     eor	w1, w17, w16
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a0101f1					//     eor	w17, w15, w1
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x0a0f2190					//     and	w16, w12, w15, lsl #8
	WORD	$0x0a4f21af					//     and	w15, w13, w15, lsr #8
	WORD	$0x13914231					//     ror	w17, w17, #16
	WORD	$0x2a0f020f					//     orr	w15, w16, w15
	WORD	$0x5ac009ce					//     rev	w14, w14
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a0e0230					//     eor	w16, w17, w14
	WORD	$0x4a0101f1					//     eor	w17, w15, w1
	WORD	$0x29421043					//     ldp	w3, w4, [x2, #16]
	WORD	$0x4a030223					//     eor	w3, w17, w3
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a100021					//     eor	w1, w1, w16
	WORD	$0x29431444					//     ldp	w4, w5, [x2, #24]
	WORD	$0x4a040210					//     eor	w16, w16, w4
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x4a0e00ae					//     eor	w14, w5, w14
	WORD	$0x53187c71					//     lsr	w17, w3, #24
	WORD	$0xb8715971					//     ldr	w17, [x11, w17, uxtw #2]
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x53105c6f					//     ubfx	w15, w3, #16, #8
	WORD	$0xb86f594f					//     ldr	w15, [x10, w15, uxtw #2]
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53083c71					//     ubfx	w17, w3, #8, #8
	WORD	$0xb8715931					//     ldr	w17, [x9, w17, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a030231					//     eor	w17, w17, w3
	WORD	$0x53187c23					//     lsr	w3, w1, #24
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x53105c24					//     ubfx	w4, w1, #16, #8
	WORD	$0xb8645944					//     ldr	w4, [x10, w4, uxtw #2]
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a030091					//     eor	w17, w4, w3
	WORD	$0x53083c23					//     ubfx	w3, w1, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001c21					//     and	w1, w1, #0xff
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53187e03					//     lsr	w3, w16, #24
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x53105e01					//     ubfx	w1, w16, #16, #8
	WORD	$0xb8615941					//     ldr	w1, [x10, w1, uxtw #2]
	WORD	$0x4a030021					//     eor	w1, w1, w3
	WORD	$0x53083e03					//     ubfx	w3, w16, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705910					//     ldr	w16, [x8, w16, uxtw #2]
	WORD	$0x4a100070					//     eor	w16, w3, w16
	WORD	$0x53187dc3					//     lsr	w3, w14, #24
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x53105dc4					//     ubfx	w4, w14, #16, #8
	WORD	$0xb8645944					//     ldr	w4, [x10, w4, uxtw #2]
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x4a030081					//     eor	w1, w4, w3
	WORD	$0x53083dc3					//     ubfx	w3, w14, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e590e					//     ldr	w14, [x8, w14, uxtw #2]
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a100231					//     eor	w17, w17, w16
	WORD	$0x4a1001d0					//     eor	w16, w14, w16
	WORD	$0x4a0f0221					//     eor	w1, w17, w15
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0f020f					//     eor	w15, w16, w15
	WORD	$0x0a0e2190					//     and	w16, w12, w14, lsl #8
	WORD	$0x0a4e21ae					//     and	w14, w13, w14, lsr #8
	WORD	$0x2a0e020e					//     orr	w14, w16, w14
	WORD	$0x13814030					//     ror	w16, w1, #16
	WORD	$0x5ac009ef					//     rev	w15, w15
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a1101d1					//     eor	w17, w14, w17
	WORD	$0x4a1001e1					//     eor	w1, w15, w16
	WORD	$0x29441043					//     ldp	w3, w4, [x2, #32]
	WORD	$0x4a030023					//     eor	w3, w1, w3
	WORD	$0x4a100090					//     eor	w16, w4, w16
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x29451444					//     ldp	w4, w5, [x2, #40]
	WORD	$0x4a040021					//     eor	w1, w1, w4
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x4a0501ef					//     eor	w15, w15, w5
	WORD	$0x4a0e01ee					//     eor	w14, w15, w14
	WORD	$0x53187c6f					//     lsr	w15, w3, #24
	WORD	$0xb86f592f					//     ldr	w15, [x9, w15, uxtw #2]
	WORD	$0x53105c61					//     ubfx	w1, w3, #16, #8
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x53083c64					//     ubfx	w4, w3, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a0f002f					//     eor	w15, w1, w15
	WORD	$0x4a030081					//     eor	w1, w4, w3
	WORD	$0x4a0101ef					//     eor	w15, w15, w1
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e03					//     ubfx	w3, w16, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083e04					//     ubfx	w4, w16, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705950					//     ldr	w16, [x10, w16, uxtw #2]
	WORD	$0x4a100090					//     eor	w16, w4, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187e21					//     lsr	w1, w17, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e23					//     ubfx	w3, w17, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083e24					//     ubfx	w4, w17, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x12001e31					//     and	w17, w17, #0xff
	WORD	$0xb8715951					//     ldr	w17, [x10, w17, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x4a110091					//     eor	w17, w4, w17
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105dc3					//     ubfx	w3, w14, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083dc4					//     ubfx	w4, w14, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e594e					//     ldr	w14, [x10, w14, uxtw #2]
	WORD	$0x4a0e008e					//     eor	w14, w4, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x4a1101d1					//     eor	w17, w14, w17
	WORD	$0x4a0f0201					//     eor	w1, w16, w15
	WORD	$0x4a1001ce					//     eor	w14, w14, w16
	WORD	$0x4a010230					//     eor	w16, w17, w1
	WORD	$0x4a0f022f					//     eor	w15, w17, w15
	WORD	$0x0a0f2191					//     and	w17, w12, w15, lsl #8
	WORD	$0x0a4f21af					//     and	w15, w13, w15, lsr #8
	WORD	$0x2a0f022f					//     orr	w15, w17, w15
	WORD	$0x13904210					//     ror	w16, w16, #16
	WORD	$0x5ac009ce					//     rev	w14, w14
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x4a0e0210					//     eor	w16, w16, w14
	WORD	$0x4a0101f1					//     eor	w17, w15, w1
	WORD	$0x29461043					//     ldp	w3, w4, [x2, #48]
	WORD	$0x4a030223					//     eor	w3, w17, w3
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a100021					//     eor	w1, w1, w16
	WORD	$0x29471444					//     ldp	w4, w5, [x2, #56]
	WORD	$0x4a040210					//     eor	w16, w16, w4
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x4a0e00ae					//     eor	w14, w5, w14
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x53187c6f					//     lsr	w15, w3, #24
	WORD	$0xb86f596f					//     ldr	w15, [x11, w15, uxtw #2]
	WORD	$0x53105c71					//     ubfx	w17, w3, #16, #8
	WORD	$0xb8715951					//     ldr	w17, [x10, w17, uxtw #2]
	WORD	$0x4a0f022f					//     eor	w15, w17, w15
	WORD	$0x53083c71					//     ubfx	w17, w3, #8, #8
	WORD	$0xb8715931					//     ldr	w17, [x9, w17, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a030231					//     eor	w17, w17, w3
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53187c31					//     lsr	w17, w1, #24
	WORD	$0xb8715971					//     ldr	w17, [x11, w17, uxtw #2]
	WORD	$0x53105c23					//     ubfx	w3, w1, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a110071					//     eor	w17, w3, w17
	WORD	$0x53083c23					//     ubfx	w3, w1, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001c21					//     and	w1, w1, #0xff
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105e03					//     ubfx	w3, w16, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083e03					//     ubfx	w3, w16, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705910					//     ldr	w16, [x8, w16, uxtw #2]
	WORD	$0x4a100070					//     eor	w16, w3, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105dc3					//     ubfx	w3, w14, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083dc3					//     ubfx	w3, w14, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e590e					//     ldr	w14, [x8, w14, uxtw #2]
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a100231					//     eor	w17, w17, w16
	WORD	$0x4a1001d0					//     eor	w16, w14, w16
	WORD	$0x4a0f0221					//     eor	w1, w17, w15
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0f020f					//     eor	w15, w16, w15
	WORD	$0x0a0e2190					//     and	w16, w12, w14, lsl #8
	WORD	$0x0a4e21ae					//     and	w14, w13, w14, lsr #8
	WORD	$0x13814021					//     ror	w1, w1, #16
	WORD	$0x2a0e020e					//     orr	w14, w16, w14
	WORD	$0x5ac009ef					//     rev	w15, w15
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a1101d0					//     eor	w16, w14, w17
	WORD	$0x4a0101f1					//     eor	w17, w15, w1
	WORD	$0x29481043					//     ldp	w3, w4, [x2, #64]
	WORD	$0x4a030223					//     eor	w3, w17, w3
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a100021					//     eor	w1, w1, w16
	WORD	$0x29491444					//     ldp	w4, w5, [x2, #72]
	WORD	$0x4a040231					//     eor	w17, w17, w4
	WORD	$0x4a100230					//     eor	w16, w17, w16
	WORD	$0x4a0501ef					//     eor	w15, w15, w5
	WORD	$0x53187c71					//     lsr	w17, w3, #24
	WORD	$0xb8715931					//     ldr	w17, [x9, w17, uxtw #2]
	WORD	$0x4a0e01ee					//     eor	w14, w15, w14
	WORD	$0x53105c6f					//     ubfx	w15, w3, #16, #8
	WORD	$0xb86f590f					//     ldr	w15, [x8, w15, uxtw #2]
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53083c71					//     ubfx	w17, w3, #8, #8
	WORD	$0xb8715971					//     ldr	w17, [x11, w17, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a030231					//     eor	w17, w17, w3
	WORD	$0x53187c23					//     lsr	w3, w1, #24
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x53105c24					//     ubfx	w4, w1, #16, #8
	WORD	$0xb8645904					//     ldr	w4, [x8, w4, uxtw #2]
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a030091					//     eor	w17, w4, w3
	WORD	$0x53083c23					//     ubfx	w3, w1, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001c21					//     and	w1, w1, #0xff
	WORD	$0xb8615941					//     ldr	w1, [x10, w1, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53187e03					//     lsr	w3, w16, #24
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x53105e01					//     ubfx	w1, w16, #16, #8
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x4a030021					//     eor	w1, w1, w3
	WORD	$0x53083e03					//     ubfx	w3, w16, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705950					//     ldr	w16, [x10, w16, uxtw #2]
	WORD	$0x4a100070					//     eor	w16, w3, w16
	WORD	$0x53187dc3					//     lsr	w3, w14, #24
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x53105dc4					//     ubfx	w4, w14, #16, #8
	WORD	$0xb8645904					//     ldr	w4, [x8, w4, uxtw #2]
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x4a030081					//     eor	w1, w4, w3
	WORD	$0x53083dc3					//     ubfx	w3, w14, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e594e					//     ldr	w14, [x10, w14, uxtw #2]
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a100231					//     eor	w17, w17, w16
	WORD	$0x4a1001d0					//     eor	w16, w14, w16
	WORD	$0x4a0f0221					//     eor	w1, w17, w15
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0f020f					//     eor	w15, w16, w15
	WORD	$0x0a0f2190					//     and	w16, w12, w15, lsl #8
	WORD	$0x0a4f21af					//     and	w15, w13, w15, lsr #8
	WORD	$0x2a0f020f					//     orr	w15, w16, w15
	WORD	$0x13914230					//     ror	w16, w17, #16
	WORD	$0x5ac009ce					//     rev	w14, w14
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x4a0e0210					//     eor	w16, w16, w14
	WORD	$0x4a0101f1					//     eor	w17, w15, w1
	WORD	$0x294a1043					//     ldp	w3, w4, [x2, #80]
	WORD	$0x4a030223					//     eor	w3, w17, w3
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a100021					//     eor	w1, w1, w16
	WORD	$0x294b1444					//     ldp	w4, w5, [x2, #88]
	WORD	$0x4a040210					//     eor	w16, w16, w4
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x4a0e00ae					//     eor	w14, w5, w14
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x53187c6f					//     lsr	w15, w3, #24
	WORD	$0xb86f596f					//     ldr	w15, [x11, w15, uxtw #2]
	WORD	$0x53105c71					//     ubfx	w17, w3, #16, #8
	WORD	$0xb8715951					//     ldr	w17, [x10, w17, uxtw #2]
	WORD	$0x53083c64					//     ubfx	w4, w3, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a0f022f					//     eor	w15, w17, w15
	WORD	$0x4a030091					//     eor	w17, w4, w3
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53187c31					//     lsr	w17, w1, #24
	WORD	$0xb8715971					//     ldr	w17, [x11, w17, uxtw #2]
	WORD	$0x53105c23					//     ubfx	w3, w1, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x53083c24					//     ubfx	w4, w1, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x4a110071					//     eor	w17, w3, w17
	WORD	$0x12001c21					//     and	w1, w1, #0xff
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105e03					//     ubfx	w3, w16, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x53083e04					//     ubfx	w4, w16, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705910					//     ldr	w16, [x8, w16, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x4a100090					//     eor	w16, w4, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105dc3					//     ubfx	w3, w14, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x53083dc4					//     ubfx	w4, w14, #8, #8
	WORD	$0xb8645924					//     ldr	w4, [x9, w4, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e590e					//     ldr	w14, [x8, w14, uxtw #2]
	WORD	$0x4a0e008e					//     eor	w14, w4, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a100231					//     eor	w17, w17, w16
	WORD	$0x4a1001d0					//     eor	w16, w14, w16
	WORD	$0x4a0f0221					//     eor	w1, w17, w15
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0f020f					//     eor	w15, w16, w15
	WORD	$0x0a0e2190					//     and	w16, w12, w14, lsl #8
	WORD	$0x0a4e21ae					//     and	w14, w13, w14, lsr #8
	WORD	$0x2a0e020e					//     orr	w14, w16, w14
	WORD	$0x13814030					//     ror	w16, w1, #16
	WORD	$0x5ac009ef					//     rev	w15, w15
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a1101d1					//     eor	w17, w14, w17
	WORD	$0x4a1001e1					//     eor	w1, w15, w16
	WORD	$0x294c1043					//     ldp	w3, w4, [x2, #96]
	WORD	$0x4a030023					//     eor	w3, w1, w3
	WORD	$0x4a100090					//     eor	w16, w4, w16
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x294d1444					//     ldp	w4, w5, [x2, #104]
	WORD	$0x4a040021					//     eor	w1, w1, w4
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x4a0501ef					//     eor	w15, w15, w5
	WORD	$0x4a0e01ee					//     eor	w14, w15, w14
	WORD	$0x53187c6f					//     lsr	w15, w3, #24
	WORD	$0xb86f592f					//     ldr	w15, [x9, w15, uxtw #2]
	WORD	$0x53105c61					//     ubfx	w1, w3, #16, #8
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x4a0f002f					//     eor	w15, w1, w15
	WORD	$0x53083c61					//     ubfx	w1, w3, #8, #8
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a030021					//     eor	w1, w1, w3
	WORD	$0x4a0101ef					//     eor	w15, w15, w1
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e03					//     ubfx	w3, w16, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083e03					//     ubfx	w3, w16, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705950					//     ldr	w16, [x10, w16, uxtw #2]
	WORD	$0x4a100070					//     eor	w16, w3, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187e21					//     lsr	w1, w17, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e23					//     ubfx	w3, w17, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083e23					//     ubfx	w3, w17, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001e31					//     and	w17, w17, #0xff
	WORD	$0xb8715951					//     ldr	w17, [x10, w17, uxtw #2]
	WORD	$0x4a110071					//     eor	w17, w3, w17
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105dc3					//     ubfx	w3, w14, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083dc3					//     ubfx	w3, w14, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e594e					//     ldr	w14, [x10, w14, uxtw #2]
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x4a1101d1					//     eor	w17, w14, w17
	WORD	$0x4a0f0201					//     eor	w1, w16, w15
	WORD	$0x4a1001ce					//     eor	w14, w14, w16
	WORD	$0x4a010230					//     eor	w16, w17, w1
	WORD	$0x4a0f022f					//     eor	w15, w17, w15
	WORD	$0x0a0f2191					//     and	w17, w12, w15, lsl #8
	WORD	$0x0a4f21af					//     and	w15, w13, w15, lsr #8
	WORD	$0x13904210					//     ror	w16, w16, #16
	WORD	$0x2a0f022f					//     orr	w15, w17, w15
	WORD	$0x5ac009ce					//     rev	w14, w14
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x4a0e0210					//     eor	w16, w16, w14
	WORD	$0x4a0101f1					//     eor	w17, w15, w1
	WORD	$0x294e1043					//     ldp	w3, w4, [x2, #112]
	WORD	$0x4a030223					//     eor	w3, w17, w3
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a100021					//     eor	w1, w1, w16
	WORD	$0x294f1444					//     ldp	w4, w5, [x2, #120]
	WORD	$0x4a040210					//     eor	w16, w16, w4
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x4a0e00ae					//     eor	w14, w5, w14
	WORD	$0x53187c71					//     lsr	w17, w3, #24
	WORD	$0xb8715971					//     ldr	w17, [x11, w17, uxtw #2]
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x53105c6f					//     ubfx	w15, w3, #16, #8
	WORD	$0xb86f594f					//     ldr	w15, [x10, w15, uxtw #2]
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53083c71					//     ubfx	w17, w3, #8, #8
	WORD	$0xb8715931					//     ldr	w17, [x9, w17, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a030231					//     eor	w17, w17, w3
	WORD	$0x53187c23					//     lsr	w3, w1, #24
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x53105c24					//     ubfx	w4, w1, #16, #8
	WORD	$0xb8645944					//     ldr	w4, [x10, w4, uxtw #2]
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a030091					//     eor	w17, w4, w3
	WORD	$0x53083c23					//     ubfx	w3, w1, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001c21					//     and	w1, w1, #0xff
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53187e03					//     lsr	w3, w16, #24
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x53105e01					//     ubfx	w1, w16, #16, #8
	WORD	$0xb8615941					//     ldr	w1, [x10, w1, uxtw #2]
	WORD	$0x4a030021					//     eor	w1, w1, w3
	WORD	$0x53083e03					//     ubfx	w3, w16, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705910					//     ldr	w16, [x8, w16, uxtw #2]
	WORD	$0x4a100070					//     eor	w16, w3, w16
	WORD	$0x53187dc3					//     lsr	w3, w14, #24
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x53105dc4					//     ubfx	w4, w14, #16, #8
	WORD	$0xb8645944					//     ldr	w4, [x10, w4, uxtw #2]
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x4a030081					//     eor	w1, w4, w3
	WORD	$0x53083dc3					//     ubfx	w3, w14, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e590e					//     ldr	w14, [x8, w14, uxtw #2]
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a100231					//     eor	w17, w17, w16
	WORD	$0x4a1001d0					//     eor	w16, w14, w16
	WORD	$0x4a0f0221					//     eor	w1, w17, w15
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0f020f					//     eor	w15, w16, w15
	WORD	$0x0a0e2190					//     and	w16, w12, w14, lsl #8
	WORD	$0x0a4e21ae					//     and	w14, w13, w14, lsr #8
	WORD	$0x2a0e020e					//     orr	w14, w16, w14
	WORD	$0x13814030					//     ror	w16, w1, #16
	WORD	$0x5ac009ef					//     rev	w15, w15
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a1101d1					//     eor	w17, w14, w17
	WORD	$0x4a1001e1					//     eor	w1, w15, w16
	WORD	$0x29501043					//     ldp	w3, w4, [x2, #128]
	WORD	$0x4a030023					//     eor	w3, w1, w3
	WORD	$0x4a100090					//     eor	w16, w4, w16
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x29511444					//     ldp	w4, w5, [x2, #136]
	WORD	$0x4a040021					//     eor	w1, w1, w4
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x4a0501ef					//     eor	w15, w15, w5
	WORD	$0x4a0e01ee					//     eor	w14, w15, w14
	WORD	$0x53187c6f					//     lsr	w15, w3, #24
	WORD	$0xb86f592f					//     ldr	w15, [x9, w15, uxtw #2]
	WORD	$0x53105c61					//     ubfx	w1, w3, #16, #8
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x53083c64					//     ubfx	w4, w3, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a0f002f					//     eor	w15, w1, w15
	WORD	$0x4a030081					//     eor	w1, w4, w3
	WORD	$0x4a0101ef					//     eor	w15, w15, w1
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e03					//     ubfx	w3, w16, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083e04					//     ubfx	w4, w16, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705950					//     ldr	w16, [x10, w16, uxtw #2]
	WORD	$0x4a100090					//     eor	w16, w4, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187e21					//     lsr	w1, w17, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105e23					//     ubfx	w3, w17, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083e24					//     ubfx	w4, w17, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x12001e31					//     and	w17, w17, #0xff
	WORD	$0xb8715951					//     ldr	w17, [x10, w17, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x4a110091					//     eor	w17, w4, w17
	WORD	$0x4a110031					//     eor	w17, w1, w17
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x53105dc3					//     ubfx	w3, w14, #16, #8
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x53083dc4					//     ubfx	w4, w14, #8, #8
	WORD	$0xb8645964					//     ldr	w4, [x11, w4, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e594e					//     ldr	w14, [x10, w14, uxtw #2]
	WORD	$0x4a0e008e					//     eor	w14, w4, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x4a1101d1					//     eor	w17, w14, w17
	WORD	$0x4a0f0201					//     eor	w1, w16, w15
	WORD	$0x4a1001ce					//     eor	w14, w14, w16
	WORD	$0x4a010230					//     eor	w16, w17, w1
	WORD	$0x4a0f022f					//     eor	w15, w17, w15
	WORD	$0x0a0f2191					//     and	w17, w12, w15, lsl #8
	WORD	$0x0a4f21af					//     and	w15, w13, w15, lsr #8
	WORD	$0x2a0f022f					//     orr	w15, w17, w15
	WORD	$0x13904210					//     ror	w16, w16, #16
	WORD	$0x5ac009ce					//     rev	w14, w14
	WORD	$0x4a1001ef					//     eor	w15, w15, w16
	WORD	$0x4a0e0210					//     eor	w16, w16, w14
	WORD	$0x4a0101f1					//     eor	w17, w15, w1
	WORD	$0x29521043					//     ldp	w3, w4, [x2, #144]
	WORD	$0x4a030223					//     eor	w3, w17, w3
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x4a100021					//     eor	w1, w1, w16
	WORD	$0x29531444					//     ldp	w4, w5, [x2, #152]
	WORD	$0x4a040210					//     eor	w16, w16, w4
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x4a0e00ae					//     eor	w14, w5, w14
	WORD	$0x4a0f01ce					//     eor	w14, w14, w15
	WORD	$0x53187c6f					//     lsr	w15, w3, #24
	WORD	$0xb86f596f					//     ldr	w15, [x11, w15, uxtw #2]
	WORD	$0x53105c71					//     ubfx	w17, w3, #16, #8
	WORD	$0xb8715951					//     ldr	w17, [x10, w17, uxtw #2]
	WORD	$0x4a0f022f					//     eor	w15, w17, w15
	WORD	$0x53083c71					//     ubfx	w17, w3, #8, #8
	WORD	$0xb8715931					//     ldr	w17, [x9, w17, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635903					//     ldr	w3, [x8, w3, uxtw #2]
	WORD	$0x4a030231					//     eor	w17, w17, w3
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53187c31					//     lsr	w17, w1, #24
	WORD	$0xb8715971					//     ldr	w17, [x11, w17, uxtw #2]
	WORD	$0x53105c23					//     ubfx	w3, w1, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a110071					//     eor	w17, w3, w17
	WORD	$0x53083c23					//     ubfx	w3, w1, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001c21					//     and	w1, w1, #0xff
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x53187e01					//     lsr	w1, w16, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105e03					//     ubfx	w3, w16, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083e03					//     ubfx	w3, w16, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705910					//     ldr	w16, [x8, w16, uxtw #2]
	WORD	$0x4a100070					//     eor	w16, w3, w16
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x53187dc1					//     lsr	w1, w14, #24
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x53105dc3					//     ubfx	w3, w14, #16, #8
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53083dc3					//     ubfx	w3, w14, #8, #8
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e590e					//     ldr	w14, [x8, w14, uxtw #2]
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a100231					//     eor	w17, w17, w16
	WORD	$0x4a1001d0					//     eor	w16, w14, w16
	WORD	$0x4a0f0221					//     eor	w1, w17, w15
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0f020f					//     eor	w15, w16, w15
	WORD	$0x0a0e2190					//     and	w16, w12, w14, lsl #8
	WORD	$0x0a4e21ae					//     and	w14, w13, w14, lsr #8
	WORD	$0x13814021					//     ror	w1, w1, #16
	WORD	$0x2a0e020e					//     orr	w14, w16, w14
	WORD	$0x5ac009ef					//     rev	w15, w15
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a0101f0					//     eor	w16, w15, w1
	WORD	$0x29541043					//     ldp	w3, w4, [x2, #160]
	WORD	$0x4a030203					//     eor	w3, w16, w3
	WORD	$0x4a010081					//     eor	w1, w4, w1
	WORD	$0x29551444					//     ldp	w4, w5, [x2, #168]
	WORD	$0x4a040210					//     eor	w16, w16, w4
	WORD	$0x4a1101d1					//     eor	w17, w14, w17
	WORD	$0x4a110021					//     eor	w1, w1, w17
	WORD	$0x4a110210					//     eor	w16, w16, w17
	WORD	$0x4a0501ef					//     eor	w15, w15, w5
	WORD	$0x53187c71					//     lsr	w17, w3, #24
	WORD	$0xb8715931					//     ldr	w17, [x9, w17, uxtw #2]
	WORD	$0x4a0e01ee					//     eor	w14, w15, w14
	WORD	$0x53105c6f					//     ubfx	w15, w3, #16, #8
	WORD	$0xb86f590f					//     ldr	w15, [x8, w15, uxtw #2]
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x53083c71					//     ubfx	w17, w3, #8, #8
	WORD	$0xb8715971					//     ldr	w17, [x11, w17, uxtw #2]
	WORD	$0x12001c63					//     and	w3, w3, #0xff
	WORD	$0xb8635943					//     ldr	w3, [x10, w3, uxtw #2]
	WORD	$0x4a030231					//     eor	w17, w17, w3
	WORD	$0x53187c23					//     lsr	w3, w1, #24
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x53105c24					//     ubfx	w4, w1, #16, #8
	WORD	$0xb8645904					//     ldr	w4, [x8, w4, uxtw #2]
	WORD	$0x4a1101ef					//     eor	w15, w15, w17
	WORD	$0x4a030091					//     eor	w17, w4, w3
	WORD	$0x53083c23					//     ubfx	w3, w1, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001c21					//     and	w1, w1, #0xff
	WORD	$0xb8615941					//     ldr	w1, [x10, w1, uxtw #2]
	WORD	$0x4a010061					//     eor	w1, w3, w1
	WORD	$0x53187e03					//     lsr	w3, w16, #24
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x53105e01					//     ubfx	w1, w16, #16, #8
	WORD	$0xb8615901					//     ldr	w1, [x8, w1, uxtw #2]
	WORD	$0x4a030021					//     eor	w1, w1, w3
	WORD	$0x53083e03					//     ubfx	w3, w16, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705950					//     ldr	w16, [x10, w16, uxtw #2]
	WORD	$0x4a100070					//     eor	w16, w3, w16
	WORD	$0x53187dc3					//     lsr	w3, w14, #24
	WORD	$0xb8635923					//     ldr	w3, [x9, w3, uxtw #2]
	WORD	$0x53105dc4					//     ubfx	w4, w14, #16, #8
	WORD	$0xb8645904					//     ldr	w4, [x8, w4, uxtw #2]
	WORD	$0x4a100030					//     eor	w16, w1, w16
	WORD	$0x4a030081					//     eor	w1, w4, w3
	WORD	$0x53083dc3					//     ubfx	w3, w14, #8, #8
	WORD	$0xb8635963					//     ldr	w3, [x11, w3, uxtw #2]
	WORD	$0x12001dce					//     and	w14, w14, #0xff
	WORD	$0xb86e594e					//     ldr	w14, [x10, w14, uxtw #2]
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x4a0e002e					//     eor	w14, w1, w14
	WORD	$0x4a100231					//     eor	w17, w17, w16
	WORD	$0x4a1001d0					//     eor	w16, w14, w16
	WORD	$0x4a0f0221					//     eor	w1, w17, w15
	WORD	$0x4a1101ce					//     eor	w14, w14, w17
	WORD	$0x4a010211					//     eor	w17, w16, w1
	WORD	$0x4a0f020f					//     eor	w15, w16, w15
	WORD	$0x0a0f218c					//     and	w12, w12, w15, lsl #8
	WORD	$0x0a4f21ad					//     and	w13, w13, w15, lsr #8
	WORD	$0x2a0d018c					//     orr	w12, w12, w13
	WORD	$0x53107e2d					//     lsr	w13, w17, #16
	WORD	$0x5ac009ce					//     rev	w14, w14
	WORD	$0x4a0d018c					//     eor	w12, w12, w13
	WORD	$0x4a0e01ad					//     eor	w13, w13, w14
	WORD	$0x4a01018f					//     eor	w15, w12, w1
	WORD	$0x29564450					//     ldp	w16, w17, [x2, #176]
	WORD	$0x4a1001f0					//     eor	w16, w15, w16
	WORD	$0x4a010231					//     eor	w17, w17, w1
	WORD	$0x4a0d0231					//     eor	w17, w17, w13
	WORD	$0x29570c41					//     ldp	w1, w3, [x2, #184]
	WORD	$0x4a0101ad					//     eor	w13, w13, w1
	WORD	$0x53032a01					//     ubfx	w1, w16, #3, #8
	WORD	$0xb8615961					//     ldr	w1, [x11, w1, uxtw #2]
	WORD	$0x39000001					//     strb	w1, [x0]
	WORD	$0x53022601					//     ubfx	w1, w16, #2, #8
	WORD	$0xb8615941					//     ldr	w1, [x10, w1, uxtw #2]
	WORD	$0x53087c21					//     lsr	w1, w1, #8
	WORD	$0x39000401					//     strb	w1, [x0, #1]
	WORD	$0x53012201					//     ubfx	w1, w16, #1, #8
	WORD	$0xb8615921					//     ldr	w1, [x9, w1, uxtw #2]
	WORD	$0x39000801					//     strb	w1, [x0, #2]
	WORD	$0x12001e10					//     and	w16, w16, #0xff
	WORD	$0xb8705910					//     ldr	w16, [x8, w16, uxtw #2]
	WORD	$0x4a0f01ad					//     eor	w13, w13, w15
	WORD	$0x39000c10					//     strb	w16, [x0, #3]
	WORD	$0x53032a2f					//     ubfx	w15, w17, #3, #8
	WORD	$0xb86f596f					//     ldr	w15, [x11, w15, uxtw #2]
	WORD	$0x3900100f					//     strb	w15, [x0, #4]
	WORD	$0x5302262f					//     ubfx	w15, w17, #2, #8
	WORD	$0xb86f594f					//     ldr	w15, [x10, w15, uxtw #2]
	WORD	$0x53087def					//     lsr	w15, w15, #8
	WORD	$0x3900140f					//     strb	w15, [x0, #5]
	WORD	$0x5301222f					//     ubfx	w15, w17, #1, #8
	WORD	$0xb86f592f					//     ldr	w15, [x9, w15, uxtw #2]
	WORD	$0x3900180f					//     strb	w15, [x0, #6]
	WORD	$0x12001e2f					//     and	w15, w17, #0xff
	WORD	$0xb86f590f					//     ldr	w15, [x8, w15, uxtw #2]
	WORD	$0x4a0e006e					//     eor	w14, w3, w14
	WORD	$0x39001c0f					//     strb	w15, [x0, #7]
	WORD	$0x530329af					//     ubfx	w15, w13, #3, #8
	WORD	$0xb86f596f					//     ldr	w15, [x11, w15, uxtw #2]
	WORD	$0x3900200f					//     strb	w15, [x0, #8]
	WORD	$0x530225af					//     ubfx	w15, w13, #2, #8
	WORD	$0xb86f594f					//     ldr	w15, [x10, w15, uxtw #2]
	WORD	$0x53087def					//     lsr	w15, w15, #8
	WORD	$0x3900240f					//     strb	w15, [x0, #9]
	WORD	$0x530121af					//     ubfx	w15, w13, #1, #8
	WORD	$0xb86f592f					//     ldr	w15, [x9, w15, uxtw #2]
	WORD	$0x3900280f					//     strb	w15, [x0, #10]
	WORD	$0x12001dad					//     and	w13, w13, #0xff
	WORD	$0xb86d590d					//     ldr	w13, [x8, w13, uxtw #2]
	WORD	$0x4a0c01cc					//     eor	w12, w14, w12
	WORD	$0x39002c0d					//     strb	w13, [x0, #11]
	WORD	$0x5303298d					//     ubfx	w13, w12, #3, #8
	WORD	$0xb86d596b					//     ldr	w11, [x11, w13, uxtw #2]
	WORD	$0x3900300b					//     strb	w11, [x0, #12]
	WORD	$0x5302258b					//     ubfx	w11, w12, #2, #8
	WORD	$0xb86b594a					//     ldr	w10, [x10, w11, uxtw #2]
	WORD	$0x53087d4a					//     lsr	w10, w10, #8
	WORD	$0x3900340a					//     strb	w10, [x0, #13]
	WORD	$0x5301218a					//     ubfx	w10, w12, #1, #8
	WORD	$0xb86a5929					//     ldr	w9, [x9, w10, uxtw #2]
	WORD	$0x39003809					//     strb	w9, [x0, #14]
	WORD	$0x12001d89					//     and	w9, w12, #0xff
	WORD	$0xb8695908					//     ldr	w8, [x8, w9, uxtw #2]
	WORD	$0x39003c08					//     strb	w8, [x0, #15]
	WORD	$0x3dc00000					//     ldr	q0, [x0]
	WORD	$0x3dc03041					//     ldr	q1, [x2, #192]
	WORD	$0x6e200821					//     rev32.16b	v1, v1
	WORD	$0x6e201c20					//     eor.16b	v0, v1, v0
	WORD	$0x3d800000					//     str	q0, [x0]
	WORD	$0xa8c17bfd					//     ldp	x29, x30, [sp], #16             ; 16-byte Folded Reload
	RET									//     ret
