// Code generated by command: go run main.go -out ../../aria_amd64.s -stubs ../../aria_amd64_stubs.go -pkg aria. DO NOT EDIT.

//go:build amd64 && gc && !purego

package aria

func processFinSSE2(dst []byte, rk []byte, t []byte)
