// Code generated by command: go run main.go -out ../../lsh512_amd64.s -stubs ../../lsh512_amd64_stubs.go -pkg lsh512. DO NOT EDIT.

//go:build amd64 && gc && !purego

package lsh512

func lsh512InitSSE2(ctx *lsh512ContextAsmData)

func lsh512UpdateSSE2(ctx *lsh512ContextAsmData, data []byte)

func lsh512FinalSSE2(ctx *lsh512ContextAsmData, hashval []byte)

func lsh512UpdateSSSE3(ctx *lsh512ContextAsmData, data []byte)

func lsh512FinalSSSE3(ctx *lsh512ContextAsmData, hashval []byte)

func lsh512InitAVX2(ctx *lsh512ContextAsmData)

func lsh512UpdateAVX2(ctx *lsh512ContextAsmData, data []byte)

func lsh512FinalAVX2(ctx *lsh512ContextAsmData, hashval []byte)
