//go:build !noasm && arm64
// AUTO-GENERATED BY GOAT -- DO NOT EDIT

TEXT ·EncKeySetup(SB), $0-32
	MOVD mk+0(FP), R0
	MOVD rk+8(FP), R1
	MOVD keyBits+16(FP), R2
	WORD $0xa9ba6ffc        // stp	x28, x27, [sp, #-96]!           ; 16-byte Folded Spill
	WORD $0xa90167fa        // stp	x26, x25, [sp, #16]             ; 16-byte Folded Spill
	WORD $0xa9025ff8        // stp	x24, x23, [sp, #32]             ; 16-byte Folded Spill
	WORD $0xa90357f6        // stp	x22, x21, [sp, #48]             ; 16-byte Folded Spill
	WORD $0xa9044ff4        // stp	x20, x19, [sp, #64]             ; 16-byte Folded Spill
	WORD $0xa9057bfd        // stp	x29, x30, [sp, #80]             ; 16-byte Folded Spill
	WORD $0x910143fd        // add	x29, sp, #80
	WORD $0x32089fe8        // mov	w8, #-16711936                  ; =0xff00ff00
	WORD $0x29402829        // ldp	w9, w10, [x1]
	WORD $0x5ac0092f        // rev	w15, w9
	WORD $0x5ac0094d        // rev	w13, w10
	WORD $0x29412829        // ldp	w9, w10, [x1, #8]
	WORD $0x5ac00930        // rev	w16, w9
	WORD $0x5ac0094e        // rev	w14, w10
	WORD $0x1e2701e0        // fmov	s0, w15
	WORD $0x4e0c1da0        // mov.s	v0[1], w13
	WORD $0xb27c7be9        // mov	x9, #34359738352                ; =0x7fffffff0
	WORD $0x8b090043        // add	x3, x2, x9
	WORD $0xd3638869        // lsl	x9, x3, #29
	WORD $0x9360fd29        // asr	x9, x9, #32
	WORD $0x90000004        // adrp	x4, _KRK@PAGE
	WORD $0x91000084        // add	x4, x4, _KRK@PAGEOFF
	WORD $0x8b091089        // add	x9, x4, x9, lsl #4
	WORD $0x29402d2a        // ldp	w10, w11, [x9]
	WORD $0x4a0f0151        // eor	w17, w10, w15
	WORD $0x4a0d0165        // eor	w5, w11, w13
	WORD $0x2941252a        // ldp	w10, w9, [x9, #8]
	WORD $0x4a100146        // eor	w6, w10, w16
	WORD $0x4a0901c7        // eor	w7, w14, w9
	WORD $0x4e141e00        // mov.s	v0[2], w16
	WORD $0x90000009        // adrp	x9, _S1@PAGE
	WORD $0x91000129        // add	x9, x9, _S1@PAGEOFF
	WORD $0x53187e2a        // lsr	w10, w17, #24
	WORD $0xb86a592b        // ldr	w11, [x9, w10, uxtw #2]
	WORD $0x4e1c1dc0        // mov.s	v0[3], w14
	WORD $0x53105e2c        // ubfx	w12, w17, #16, #8
	WORD $0x9000000a        // adrp	x10, _S2@PAGE
	WORD $0x9100014a        // add	x10, x10, _S2@PAGEOFF
	WORD $0xb86c594c        // ldr	w12, [x10, w12, uxtw #2]
	WORD $0x4a0b0193        // eor	w19, w12, w11
	WORD $0x53083e2c        // ubfx	w12, w17, #8, #8
	WORD $0x9000000b        // adrp	x11, _X1@PAGE
	WORD $0x9100016b        // add	x11, x11, _X1@PAGEOFF
	WORD $0xb86c5974        // ldr	w20, [x11, w12, uxtw #2]
	WORD $0x9000000c        // adrp	x12, _X2@PAGE
	WORD $0x9100018c        // add	x12, x12, _X2@PAGEOFF
	WORD $0x12001e31        // and	w17, w17, #0xff
	WORD $0xb8715991        // ldr	w17, [x12, w17, uxtw #2]
	WORD $0x4a110291        // eor	w17, w20, w17
	WORD $0x4a110273        // eor	w19, w19, w17
	WORD $0x53187cb1        // lsr	w17, w5, #24
	WORD $0xb8715931        // ldr	w17, [x9, w17, uxtw #2]
	WORD $0x53105cb4        // ubfx	w20, w5, #16, #8
	WORD $0xb8745954        // ldr	w20, [x10, w20, uxtw #2]
	WORD $0x4a110291        // eor	w17, w20, w17
	WORD $0x53083cb4        // ubfx	w20, w5, #8, #8
	WORD $0xb8745974        // ldr	w20, [x11, w20, uxtw #2]
	WORD $0x12001ca5        // and	w5, w5, #0xff
	WORD $0xb8655985        // ldr	w5, [x12, w5, uxtw #2]
	WORD $0x4a050285        // eor	w5, w20, w5
	WORD $0x4a050225        // eor	w5, w17, w5
	WORD $0x53187cd1        // lsr	w17, w6, #24
	WORD $0xb8715931        // ldr	w17, [x9, w17, uxtw #2]
	WORD $0x53105cd4        // ubfx	w20, w6, #16, #8
	WORD $0xb8745954        // ldr	w20, [x10, w20, uxtw #2]
	WORD $0x4a110291        // eor	w17, w20, w17
	WORD $0x53083cd4        // ubfx	w20, w6, #8, #8
	WORD $0xb8745974        // ldr	w20, [x11, w20, uxtw #2]
	WORD $0x12001cc6        // and	w6, w6, #0xff
	WORD $0xb8665986        // ldr	w6, [x12, w6, uxtw #2]
	WORD $0x4a060286        // eor	w6, w20, w6
	WORD $0x4a060226        // eor	w6, w17, w6
	WORD $0x53187cf1        // lsr	w17, w7, #24
	WORD $0xb8715931        // ldr	w17, [x9, w17, uxtw #2]
	WORD $0x53105cf4        // ubfx	w20, w7, #16, #8
	WORD $0xb8745954        // ldr	w20, [x10, w20, uxtw #2]
	WORD $0x4a110294        // eor	w20, w20, w17
	WORD $0x53083cf1        // ubfx	w17, w7, #8, #8
	WORD $0xb8715975        // ldr	w21, [x11, w17, uxtw #2]
	WORD $0x12001cf1        // and	w17, w7, #0xff
	WORD $0xb8715987        // ldr	w7, [x12, w17, uxtw #2]
	WORD $0x32009ff1        // mov	w17, #16711935                  ; =0xff00ff
	WORD $0x4a0702a7        // eor	w7, w21, w7
	WORD $0x4a070287        // eor	w7, w20, w7
	WORD $0x4a0600a5        // eor	w5, w5, w6
	WORD $0x4a0600e6        // eor	w6, w7, w6
	WORD $0x4a1300b4        // eor	w20, w5, w19
	WORD $0x4a0500e5        // eor	w5, w7, w5
	WORD $0x4a1400c7        // eor	w7, w6, w20
	WORD $0x4a1300c6        // eor	w6, w6, w19
	WORD $0x5ac008c6        // rev	w6, w6
	WORD $0x138740f5        // ror	w21, w7, #16
	WORD $0x5ac008a7        // rev	w7, w5
	WORD $0x4a0702b3        // eor	w19, w21, w7
	WORD $0x4ac642a5        // eor	w5, w21, w6, ror #16
	WORD $0x4a1400a6        // eor	w6, w5, w20
	WORD $0x6f00e401        // movi.2d	v1, #0000000000000000
	WORD $0xf100445f        // cmp	x2, #17
	WORD $0x54000203        // b.lo	LBB0_4
	WORD $0x29425835        // ldp	w21, w22, [x1, #16]
	WORD $0x5ac00ab5        // rev	w21, w21
	WORD $0x5ac00ad6        // rev	w22, w22
	WORD $0x1e2702a1        // fmov	s1, w21
	WORD $0x4e0c1ec1        // mov.s	v1[1], w22
	WORD $0xf100645f        // cmp	x2, #25
	WORD $0x540000e3        // b.lo	LBB0_3
	WORD $0x29430435        // ldp	w21, w1, [x1, #24]
	WORD $0x5ac00ab5        // rev	w21, w21
	WORD $0x4e141ea1        // mov.s	v1[2], w21
	WORD $0x5ac00821        // rev	w1, w1
	WORD $0x4e1c1c21        // mov.s	v1[3], w1
	WORD $0x14000003        // b	LBB0_4
	WORD $0x6f00e402        // movi.2d	v2, #0000000000000000
	WORD $0x6e184441        // mov.d	v1[1], v2[1]
	WORD $0xd343fc75        // lsr	x21, x3, #3
	WORD $0x1e260021        // fmov	w1, s1
	WORD $0x0e0c3c36        // mov.s	w22, v1[1]
	WORD $0x4a060023        // eor	w3, w1, w6
	WORD $0x4a160281        // eor	w1, w20, w22
	WORD $0x4a130021        // eor	w1, w1, w19
	WORD $0x71000abf        // cmp	w21, #2
	WORD $0x1a9507f4        // csinc	w20, wzr, w21, eq
	WORD $0x8b34d095        // add	x21, x4, w20, sxtw #4
	WORD $0x29405eb6        // ldp	w22, w23, [x21]
	WORD $0x4a160076        // eor	w22, w3, w22
	WORD $0x53187ed8        // lsr	w24, w22, #24
	WORD $0xb8785978        // ldr	w24, [x11, w24, uxtw #2]
	WORD $0x4a170039        // eor	w25, w1, w23
	WORD $0x53105ed7        // ubfx	w23, w22, #16, #8
	WORD $0xb8775997        // ldr	w23, [x12, w23, uxtw #2]
	WORD $0x4a1802f7        // eor	w23, w23, w24
	WORD $0x53083ed8        // ubfx	w24, w22, #8, #8
	WORD $0xb8785938        // ldr	w24, [x9, w24, uxtw #2]
	WORD $0x12001ed6        // and	w22, w22, #0xff
	WORD $0xb8765956        // ldr	w22, [x10, w22, uxtw #2]
	WORD $0x4a160316        // eor	w22, w24, w22
	WORD $0x53187f38        // lsr	w24, w25, #24
	WORD $0xb8785978        // ldr	w24, [x11, w24, uxtw #2]
	WORD $0x53105f3a        // ubfx	w26, w25, #16, #8
	WORD $0xb87a599a        // ldr	w26, [x12, w26, uxtw #2]
	WORD $0x4a1602f7        // eor	w23, w23, w22
	WORD $0x4a180356        // eor	w22, w26, w24
	WORD $0x53083f38        // ubfx	w24, w25, #8, #8
	WORD $0xb8785938        // ldr	w24, [x9, w24, uxtw #2]
	WORD $0x29416eba        // ldp	w26, w27, [x21, #8]
	WORD $0x12001f35        // and	w21, w25, #0xff
	WORD $0xb8755955        // ldr	w21, [x10, w21, uxtw #2]
	WORD $0x4a150315        // eor	w21, w24, w21
	WORD $0x4a1502d8        // eor	w24, w22, w21
	WORD $0x71000a9f        // cmp	w20, #2
	WORD $0x1a9407f4        // csinc	w20, wzr, w20, eq
	WORD $0x8b34d096        // add	x22, x4, w20, sxtw #4
	WORD $0x294052c4        // ldp	w4, w20, [x22]
	WORD $0x29415ad5        // ldp	w21, w22, [x22, #8]
	WORD $0x1e270262        // fmov	s2, w19
	WORD $0x4e0c1ce2        // mov.s	v2[1], w7
	WORD $0x6e014021        // ext.16b	v1, v1, v1, #8
	WORD $0x2e211c41        // eor.8b	v1, v2, v1
	WORD $0x1e2700c2        // fmov	s2, w6
	WORD $0x4e0c1ca2        // mov.s	v2[1], w5
	WORD $0x2e221c21        // eor.8b	v1, v1, v2
	WORD $0x1e260025        // fmov	w5, s1
	WORD $0x4a1a00a5        // eor	w5, w5, w26
	WORD $0x0e0c3c26        // mov.s	w6, v1[1]
	WORD $0x4a060366        // eor	w6, w27, w6
	WORD $0x53187ca7        // lsr	w7, w5, #24
	WORD $0xb8675967        // ldr	w7, [x11, w7, uxtw #2]
	WORD $0x53105cb3        // ubfx	w19, w5, #16, #8
	WORD $0xb8735993        // ldr	w19, [x12, w19, uxtw #2]
	WORD $0x53083cb9        // ubfx	w25, w5, #8, #8
	WORD $0xb8795939        // ldr	w25, [x9, w25, uxtw #2]
	WORD $0x4a070267        // eor	w7, w19, w7
	WORD $0x12001ca5        // and	w5, w5, #0xff
	WORD $0xb8655945        // ldr	w5, [x10, w5, uxtw #2]
	WORD $0x4a050325        // eor	w5, w25, w5
	WORD $0x4a0500e5        // eor	w5, w7, w5
	WORD $0x53187cc7        // lsr	w7, w6, #24
	WORD $0xb8675967        // ldr	w7, [x11, w7, uxtw #2]
	WORD $0x53105cd3        // ubfx	w19, w6, #16, #8
	WORD $0xb8735993        // ldr	w19, [x12, w19, uxtw #2]
	WORD $0x53083cd9        // ubfx	w25, w6, #8, #8
	WORD $0xb8795939        // ldr	w25, [x9, w25, uxtw #2]
	WORD $0x12001cc6        // and	w6, w6, #0xff
	WORD $0xb8665946        // ldr	w6, [x10, w6, uxtw #2]
	WORD $0x4a070267        // eor	w7, w19, w7
	WORD $0x4a060326        // eor	w6, w25, w6
	WORD $0x4a0600e6        // eor	w6, w7, w6
	WORD $0x4a050307        // eor	w7, w24, w5
	WORD $0x4a0500c5        // eor	w5, w6, w5
	WORD $0x4a1700f3        // eor	w19, w7, w23
	WORD $0x4a0700c6        // eor	w6, w6, w7
	WORD $0x4a1300a7        // eor	w7, w5, w19
	WORD $0x4a1700a5        // eor	w5, w5, w23
	WORD $0x0a062117        // and	w23, w8, w6, lsl #8
	WORD $0x0a462226        // and	w6, w17, w6, lsr #8
	WORD $0x2a0602e6        // orr	w6, w23, w6
	WORD $0x13934273        // ror	w19, w19, #16
	WORD $0x5ac008a5        // rev	w5, w5
	WORD $0x4a0700a5        // eor	w5, w5, w7
	WORD $0x4a0700c7        // eor	w7, w6, w7
	WORD $0x4a1300b7        // eor	w23, w5, w19
	WORD $0x4a0f02ef        // eor	w15, w23, w15
	WORD $0x4a0d026d        // eor	w13, w19, w13
	WORD $0x4a0701ad        // eor	w13, w13, w7
	WORD $0x4a1002f0        // eor	w16, w23, w16
	WORD $0x4a070210        // eor	w16, w16, w7
	WORD $0x4a0e00ae        // eor	w14, w5, w14
	WORD $0x4a0601ce        // eor	w14, w14, w6
	WORD $0x4a0401e4        // eor	w4, w15, w4
	WORD $0x4a1401a5        // eor	w5, w13, w20
	WORD $0x4a150206        // eor	w6, w16, w21
	WORD $0x4a1601c7        // eor	w7, w14, w22
	WORD $0x53187c93        // lsr	w19, w4, #24
	WORD $0xb8735933        // ldr	w19, [x9, w19, uxtw #2]
	WORD $0x53105c94        // ubfx	w20, w4, #16, #8
	WORD $0xb8745954        // ldr	w20, [x10, w20, uxtw #2]
	WORD $0x4a130293        // eor	w19, w20, w19
	WORD $0x53083c94        // ubfx	w20, w4, #8, #8
	WORD $0xb8745974        // ldr	w20, [x11, w20, uxtw #2]
	WORD $0x12001c84        // and	w4, w4, #0xff
	WORD $0xb8645984        // ldr	w4, [x12, w4, uxtw #2]
	WORD $0x4a040284        // eor	w4, w20, w4
	WORD $0x4a040264        // eor	w4, w19, w4
	WORD $0x53187cb3        // lsr	w19, w5, #24
	WORD $0xb8735933        // ldr	w19, [x9, w19, uxtw #2]
	WORD $0x53105cb4        // ubfx	w20, w5, #16, #8
	WORD $0xb8745954        // ldr	w20, [x10, w20, uxtw #2]
	WORD $0x4a130293        // eor	w19, w20, w19
	WORD $0x53083cb4        // ubfx	w20, w5, #8, #8
	WORD $0xb8745974        // ldr	w20, [x11, w20, uxtw #2]
	WORD $0x12001ca5        // and	w5, w5, #0xff
	WORD $0xb8655985        // ldr	w5, [x12, w5, uxtw #2]
	WORD $0x4a050285        // eor	w5, w20, w5
	WORD $0x4a050265        // eor	w5, w19, w5
	WORD $0x53187cd3        // lsr	w19, w6, #24
	WORD $0xb8735933        // ldr	w19, [x9, w19, uxtw #2]
	WORD $0x53105cd4        // ubfx	w20, w6, #16, #8
	WORD $0xb8745954        // ldr	w20, [x10, w20, uxtw #2]
	WORD $0x4a130293        // eor	w19, w20, w19
	WORD $0x53083cd4        // ubfx	w20, w6, #8, #8
	WORD $0xb8745974        // ldr	w20, [x11, w20, uxtw #2]
	WORD $0x12001cc6        // and	w6, w6, #0xff
	WORD $0xb8665986        // ldr	w6, [x12, w6, uxtw #2]
	WORD $0x4a060286        // eor	w6, w20, w6
	WORD $0x4a060266        // eor	w6, w19, w6
	WORD $0x53187cf3        // lsr	w19, w7, #24
	WORD $0xb8735929        // ldr	w9, [x9, w19, uxtw #2]
	WORD $0x53105cf3        // ubfx	w19, w7, #16, #8
	WORD $0xb873594a        // ldr	w10, [x10, w19, uxtw #2]
	WORD $0x4a090149        // eor	w9, w10, w9
	WORD $0x53083cea        // ubfx	w10, w7, #8, #8
	WORD $0xb86a596a        // ldr	w10, [x11, w10, uxtw #2]
	WORD $0x12001ceb        // and	w11, w7, #0xff
	WORD $0xb86b598b        // ldr	w11, [x12, w11, uxtw #2]
	WORD $0x4a0b014a        // eor	w10, w10, w11
	WORD $0x4a0a0129        // eor	w9, w9, w10
	WORD $0x4a0600aa        // eor	w10, w5, w6
	WORD $0x4a06012b        // eor	w11, w9, w6
	WORD $0x4a04014c        // eor	w12, w10, w4
	WORD $0x4a0c0165        // eor	w5, w11, w12
	WORD $0x4a04016b        // eor	w11, w11, w4
	WORD $0x0a0b2108        // and	w8, w8, w11, lsl #8
	WORD $0x0a4b222b        // and	w11, w17, w11, lsr #8
	WORD $0x2a0b0108        // orr	w8, w8, w11
	WORD $0x138540ab        // ror	w11, w5, #16
	WORD $0x4a0b0108        // eor	w8, w8, w11
	WORD $0x4a0c0111        // eor	w17, w8, w12
	WORD $0x4a030224        // eor	w4, w17, w3
	WORD $0x1e270062        // fmov	s2, w3
	WORD $0x4e0c1c22        // mov.s	v2[1], w1
	WORD $0x6e180422        // mov.d	v2[1], v1[0]
	WORD $0x1e2701e3        // fmov	s3, w15
	WORD $0x4e0c1da3        // mov.s	v3[1], w13
	WORD $0x4e141e03        // mov.s	v3[2], w16
	WORD $0x4e1c1dc3        // mov.s	v3[3], w14
	WORD $0x4a0a0129        // eor	w9, w9, w10
	WORD $0x5ac00929        // rev	w9, w9
	WORD $0x4a09016a        // eor	w10, w11, w9
	WORD $0x4a01018b        // eor	w11, w12, w1
	WORD $0x4a0a016b        // eor	w11, w11, w10
	WORD $0x1e270144        // fmov	s4, w10
	WORD $0x4e0c1d24        // mov.s	v4[1], w9
	WORD $0x1e270225        // fmov	s5, w17
	WORD $0x4e0c1d05        // mov.s	v5[1], w8
	WORD $0x2e211c81        // eor.8b	v1, v4, v1
	WORD $0x2e251c24        // eor.8b	v4, v1, v5
	WORD $0x1e270081        // fmov	s1, w4
	WORD $0x4e0c1d61        // mov.s	v1[1], w11
	WORD $0x6e180481        // mov.d	v1[1], v4[0]
	WORD $0x6e026044        // ext.16b	v4, v2, v2, #12
	WORD $0x6f2d0445        // ushr.4s	v5, v2, #19
	WORD $0x4f2d5486        // shl.4s	v6, v4, #13
	WORD $0x4ea51cc5        // orr.16b	v5, v6, v5
	WORD $0x6e036066        // ext.16b	v6, v3, v3, #12
	WORD $0x6f2d0467        // ushr.4s	v7, v3, #19
	WORD $0x4f2d54d0        // shl.4s	v16, v6, #13
	WORD $0x4ea71e07        // orr.16b	v7, v16, v7
	WORD $0x6e016030        // ext.16b	v16, v1, v1, #12
	WORD $0x6f2d0431        // ushr.4s	v17, v1, #19
	WORD $0x4f2d5612        // shl.4s	v18, v16, #13
	WORD $0x4eb11e51        // orr.16b	v17, v18, v17
	WORD $0x6e006012        // ext.16b	v18, v0, v0, #12
	WORD $0x6f2d0413        // ushr.4s	v19, v0, #19
	WORD $0x4f2d5654        // shl.4s	v20, v18, #13
	WORD $0x4eb31e93        // orr.16b	v19, v20, v19
	WORD $0x6f210454        // ushr.4s	v20, v2, #31
	WORD $0x4ea48484        // add.4s	v4, v4, v4
	WORD $0x4eb41c84        // orr.16b	v4, v4, v20
	WORD $0x6f210474        // ushr.4s	v20, v3, #31
	WORD $0x4ea684c6        // add.4s	v6, v6, v6
	WORD $0x4eb41cc6        // orr.16b	v6, v6, v20
	WORD $0x6f210434        // ushr.4s	v20, v1, #31
	WORD $0x4eb08610        // add.4s	v16, v16, v16
	WORD $0x4eb41e10        // orr.16b	v16, v16, v20
	WORD $0x6f210414        // ushr.4s	v20, v0, #31
	WORD $0x4eb28652        // add.4s	v18, v18, v18
	WORD $0x4eb41e52        // orr.16b	v18, v18, v20
	WORD $0x6e201ca5        // eor.16b	v5, v5, v0
	WORD $0x6e221ce7        // eor.16b	v7, v7, v2
	WORD $0x6e231e31        // eor.16b	v17, v17, v3
	WORD $0x6e331c33        // eor.16b	v19, v1, v19
	WORD $0x6e201c84        // eor.16b	v4, v4, v0
	WORD $0x6e221cc6        // eor.16b	v6, v6, v2
	WORD $0x6e231e10        // eor.16b	v16, v16, v3
	WORD $0x6e321c32        // eor.16b	v18, v1, v18
	WORD $0xad001c05        // stp	q5, q7, [x0]
	WORD $0x6f3d0445        // ushr.4s	v5, v2, #3
	WORD $0xad014c11        // stp	q17, q19, [x0, #32]
	WORD $0xad021804        // stp	q4, q6, [x0, #64]
	WORD $0xad034810        // stp	q16, q18, [x0, #96]
	WORD $0x6e0540a5        // ext.16b	v5, v5, v5, #8
	WORD $0x6e022044        // ext.16b	v4, v2, v2, #4
	WORD $0x4f3d5486        // shl.4s	v6, v4, #29
	WORD $0x4ea51cc5        // orr.16b	v5, v6, v5
	WORD $0x6e201ca5        // eor.16b	v5, v5, v0
	WORD $0x6f3d0466        // ushr.4s	v6, v3, #3
	WORD $0x6e0640c7        // ext.16b	v7, v6, v6, #8
	WORD $0x6e032066        // ext.16b	v6, v3, v3, #4
	WORD $0x4f3d54d0        // shl.4s	v16, v6, #29
	WORD $0x4ea71e07        // orr.16b	v7, v16, v7
	WORD $0x6e221ce7        // eor.16b	v7, v7, v2
	WORD $0xad041c05        // stp	q5, q7, [x0, #128]
	WORD $0x6f3d0425        // ushr.4s	v5, v1, #3
	WORD $0x6e0540a5        // ext.16b	v5, v5, v5, #8
	WORD $0x6e012027        // ext.16b	v7, v1, v1, #4
	WORD $0x4f3d54f0        // shl.4s	v16, v7, #29
	WORD $0x4ea51e10        // orr.16b	v16, v16, v5
	WORD $0x6f3d0405        // ushr.4s	v5, v0, #3
	WORD $0x6e0540b1        // ext.16b	v17, v5, v5, #8
	WORD $0x6e002005        // ext.16b	v5, v0, v0, #4
	WORD $0x4f3d54b2        // shl.4s	v18, v5, #29
	WORD $0x4eb11e51        // orr.16b	v17, v18, v17
	WORD $0x6e231e10        // eor.16b	v16, v16, v3
	WORD $0x6e311c31        // eor.16b	v17, v1, v17
	WORD $0xad054410        // stp	q16, q17, [x0, #160]
	WORD $0x4f3f5450        // shl.4s	v16, v2, #31
	WORD $0x6f3f0491        // ushr.4s	v17, v4, #1
	WORD $0x4eb11e10        // orr.16b	v16, v16, v17
	WORD $0x6e201e10        // eor.16b	v16, v16, v0
	WORD $0x3d803010        // str	q16, [x0, #192]
	WORD $0xf100445f        // cmp	x2, #17
	WORD $0x540002a3        // b.lo	LBB0_7
	WORD $0x6f3f04c6        // ushr.4s	v6, v6, #1
	WORD $0x4f3f5470        // shl.4s	v16, v3, #31
	WORD $0x4ea61e06        // orr.16b	v6, v16, v6
	WORD $0x6e221cc6        // eor.16b	v6, v6, v2
	WORD $0x6f3f04e7        // ushr.4s	v7, v7, #1
	WORD $0x4f3f5430        // shl.4s	v16, v1, #31
	WORD $0x4ea71e07        // orr.16b	v7, v16, v7
	WORD $0x6e231ce3        // eor.16b	v3, v7, v3
	WORD $0xad068c06        // stp	q6, q3, [x0, #208]
	WORD $0xf100645f        // cmp	x2, #25
	WORD $0x54000143        // b.lo	LBB0_7
	WORD $0x6f3f04a3        // ushr.4s	v3, v5, #1
	WORD $0x4f3f5405        // shl.4s	v5, v0, #31
	WORD $0x4ea31ca3        // orr.16b	v3, v5, v3
	WORD $0x6e231c21        // eor.16b	v1, v1, v3
	WORD $0x6f330483        // ushr.4s	v3, v4, #13
	WORD $0x4f335442        // shl.4s	v2, v2, #19
	WORD $0x4ea31c42        // orr.16b	v2, v2, v3
	WORD $0x6e201c40        // eor.16b	v0, v2, v0
	WORD $0xad078001        // stp	q1, q0, [x0, #240]
	WORD $0xa9457bfd        // ldp	x29, x30, [sp, #80]             ; 16-byte Folded Reload
	WORD $0xa9444ff4        // ldp	x20, x19, [sp, #64]             ; 16-byte Folded Reload
	WORD $0xa94357f6        // ldp	x22, x21, [sp, #48]             ; 16-byte Folded Reload
	WORD $0xa9425ff8        // ldp	x24, x23, [sp, #32]             ; 16-byte Folded Reload
	WORD $0xa94167fa        // ldp	x26, x25, [sp, #16]             ; 16-byte Folded Reload
	WORD $0xa8c66ffc        // ldp	x28, x27, [sp], #96             ; 16-byte Folded Reload
	WORD $0xd65f03c0        // ret

TEXT ·DecKeySetup(SB), $0-32
	MOVD rk+0(FP), R0
	MOVD keyBits+8(FP), R1
	WORD $0x32089fe8       // mov	w8, #-16711936                  ; =0xff00ff00
	WORD $0x32009fe9       // mov	w9, #16711935                   ; =0xff00ff
	WORD $0x531e742b       // lsl	w11, w1, #2
	WORD $0x8b2bc80c       // add	x12, x0, w11, sxtw #2
	WORD $0x3dc00000       // ldr	q0, [x0]
	WORD $0x3dc00181       // ldr	q1, [x12]
	WORD $0x3d800001       // str	q1, [x0]
	WORD $0xaa0c03ed       // mov	x13, x12
	WORD $0x3c9f05a0       // str	q0, [x13], #-16
	WORD $0x71000c3f       // cmp	w1, #3
	WORD $0x54000d0b       // b.lt	LBB1_4
	WORD $0xd280000a       // mov	x10, #0                         ; =0x0
	WORD $0x93407d6b       // sxtw	x11, w11
	WORD $0xd37ef56b       // lsl	x11, x11, #2
	WORD $0x8b0a000c       // add	x12, x0, x10
	WORD $0x29423d8e       // ldp	w14, w15, [x12, #16]
	WORD $0x53185dd0       // lsl	w16, w14, #8
	WORD $0x8b0b000d       // add	x13, x0, x11
	WORD $0x4a4e2210       // eor	w16, w16, w14, lsr #8
	WORD $0x4a0e4210       // eor	w16, w16, w14, lsl #16
	WORD $0x4a4e4210       // eor	w16, w16, w14, lsr #16
	WORD $0x4a0e6210       // eor	w16, w16, w14, lsl #24
	WORD $0x4a4e620e       // eor	w14, w16, w14, lsr #24
	WORD $0x53185df0       // lsl	w16, w15, #8
	WORD $0x4a4f2210       // eor	w16, w16, w15, lsr #8
	WORD $0x4a0f4210       // eor	w16, w16, w15, lsl #16
	WORD $0x4a4f4210       // eor	w16, w16, w15, lsr #16
	WORD $0x4a0f6210       // eor	w16, w16, w15, lsl #24
	WORD $0x4a4f620f       // eor	w15, w16, w15, lsr #24
	WORD $0x29434590       // ldp	w16, w17, [x12, #24]
	WORD $0x53185e01       // lsl	w1, w16, #8
	WORD $0x4a502021       // eor	w1, w1, w16, lsr #8
	WORD $0x4a104021       // eor	w1, w1, w16, lsl #16
	WORD $0x4a504021       // eor	w1, w1, w16, lsr #16
	WORD $0x4a106021       // eor	w1, w1, w16, lsl #24
	WORD $0x4a506030       // eor	w16, w1, w16, lsr #24
	WORD $0x53185e21       // lsl	w1, w17, #8
	WORD $0x4a512021       // eor	w1, w1, w17, lsr #8
	WORD $0x4a114021       // eor	w1, w1, w17, lsl #16
	WORD $0x4a514021       // eor	w1, w1, w17, lsr #16
	WORD $0x4a116021       // eor	w1, w1, w17, lsl #24
	WORD $0x4a516031       // eor	w17, w1, w17, lsr #24
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x4a100230       // eor	w16, w17, w16
	WORD $0x4a0e01e1       // eor	w1, w15, w14
	WORD $0x4a0f022f       // eor	w15, w17, w15
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0e020e       // eor	w14, w16, w14
	WORD $0x0a0e2110       // and	w16, w8, w14, lsl #8
	WORD $0x0a4e212e       // and	w14, w9, w14, lsr #8
	WORD $0x2a0e020e       // orr	w14, w16, w14
	WORD $0x13914230       // ror	w16, w17, #16
	WORD $0x5ac009ef       // rev	w15, w15
	WORD $0x4a1001ce       // eor	w14, w14, w16
	WORD $0x4a0f0210       // eor	w16, w16, w15
	WORD $0x4a0101d1       // eor	w17, w14, w1
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x4a10022f       // eor	w15, w17, w16
	WORD $0x4a010210       // eor	w16, w16, w1
	WORD $0x297e09a1       // ldp	w1, w2, [x13, #-16]
	WORD $0x53185c43       // lsl	w3, w2, #8
	WORD $0x4a422063       // eor	w3, w3, w2, lsr #8
	WORD $0x4a024063       // eor	w3, w3, w2, lsl #16
	WORD $0x4a424063       // eor	w3, w3, w2, lsr #16
	WORD $0x4a026063       // eor	w3, w3, w2, lsl #24
	WORD $0x4a426062       // eor	w2, w3, w2, lsr #24
	WORD $0x297f11a3       // ldp	w3, w4, [x13, #-8]
	WORD $0x53185c65       // lsl	w5, w3, #8
	WORD $0x4a4320a5       // eor	w5, w5, w3, lsr #8
	WORD $0x4a0340a5       // eor	w5, w5, w3, lsl #16
	WORD $0x4a4340a5       // eor	w5, w5, w3, lsr #16
	WORD $0x4a0360a5       // eor	w5, w5, w3, lsl #24
	WORD $0x4a4360a3       // eor	w3, w5, w3, lsr #24
	WORD $0x53185c85       // lsl	w5, w4, #8
	WORD $0x4a4420a5       // eor	w5, w5, w4, lsr #8
	WORD $0x4a0440a5       // eor	w5, w5, w4, lsl #16
	WORD $0x4a4440a5       // eor	w5, w5, w4, lsr #16
	WORD $0x4a030042       // eor	w2, w2, w3
	WORD $0x4a0460a5       // eor	w5, w5, w4, lsl #24
	WORD $0x4a4460a4       // eor	w4, w5, w4, lsr #24
	WORD $0x4a030083       // eor	w3, w4, w3
	WORD $0x53185c25       // lsl	w5, w1, #8
	WORD $0x4a4120a5       // eor	w5, w5, w1, lsr #8
	WORD $0x4a0140a5       // eor	w5, w5, w1, lsl #16
	WORD $0x4a4140a5       // eor	w5, w5, w1, lsr #16
	WORD $0x4a0160a5       // eor	w5, w5, w1, lsl #24
	WORD $0x4a4160a1       // eor	w1, w5, w1, lsr #24
	WORD $0x4a010045       // eor	w5, w2, w1
	WORD $0x4a020082       // eor	w2, w4, w2
	WORD $0x4a050064       // eor	w4, w3, w5
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x0a012103       // and	w3, w8, w1, lsl #8
	WORD $0x0a412121       // and	w1, w9, w1, lsr #8
	WORD $0x2a010061       // orr	w1, w3, w1
	WORD $0x5ac00842       // rev	w2, w2
	WORD $0x13844083       // ror	w3, w4, #16
	WORD $0x4a030021       // eor	w1, w1, w3
	WORD $0x4a020063       // eor	w3, w3, w2
	WORD $0x4a050024       // eor	w4, w1, w5
	WORD $0x4a020021       // eor	w1, w1, w2
	WORD $0x4a030082       // eor	w2, w4, w3
	WORD $0x4a050063       // eor	w3, w3, w5
	WORD $0x29020d84       // stp	w4, w3, [x12, #16]
	WORD $0x29030582       // stp	w2, w1, [x12, #24]
	WORD $0x293e41b1       // stp	w17, w16, [x13, #-16]
	WORD $0x293f39af       // stp	w15, w14, [x13, #-8]
	WORD $0x9100818e       // add	x14, x12, #32
	WORD $0xd100416b       // sub	x11, x11, #16
	WORD $0x9100414a       // add	x10, x10, #16
	WORD $0x8b0b000c       // add	x12, x0, x11
	WORD $0xd100418d       // sub	x13, x12, #16
	WORD $0xeb0d01df       // cmp	x14, x13
	WORD $0x54fff3c3       // b.lo	LBB1_2
	WORD $0x8b0a0000       // add	x0, x0, x10
	WORD $0x9100400a       // add	x10, x0, #16
	WORD $0xa9bf7bfd       // stp	x29, x30, [sp, #-16]!           ; 16-byte Folded Spill
	WORD $0x910003fd       // mov	x29, sp
	WORD $0x2942b80b       // ldp	w11, w14, [x0, #20]
	WORD $0x53185d6f       // lsl	w15, w11, #8
	WORD $0xb940014a       // ldr	w10, [x10]
	WORD $0x4a4b21ef       // eor	w15, w15, w11, lsr #8
	WORD $0x4a0b41ef       // eor	w15, w15, w11, lsl #16
	WORD $0x4a4b41ef       // eor	w15, w15, w11, lsr #16
	WORD $0x4a0b61ef       // eor	w15, w15, w11, lsl #24
	WORD $0x4a4b61eb       // eor	w11, w15, w11, lsr #24
	WORD $0x53185dcf       // lsl	w15, w14, #8
	WORD $0x4a4e21ef       // eor	w15, w15, w14, lsr #8
	WORD $0x4a0e41ef       // eor	w15, w15, w14, lsl #16
	WORD $0x4a4e41ef       // eor	w15, w15, w14, lsr #16
	WORD $0x4a0e61ef       // eor	w15, w15, w14, lsl #24
	WORD $0x4a4e61ee       // eor	w14, w15, w14, lsr #24
	WORD $0xb9401c0f       // ldr	w15, [x0, #28]
	WORD $0x53185df0       // lsl	w16, w15, #8
	WORD $0x4a4f2210       // eor	w16, w16, w15, lsr #8
	WORD $0x4a0f4210       // eor	w16, w16, w15, lsl #16
	WORD $0x4a4f4210       // eor	w16, w16, w15, lsr #16
	WORD $0x4a0f6210       // eor	w16, w16, w15, lsl #24
	WORD $0x4a4f620f       // eor	w15, w16, w15, lsr #24
	WORD $0x53185d50       // lsl	w16, w10, #8
	WORD $0x4a4a2210       // eor	w16, w16, w10, lsr #8
	WORD $0x4a0a4210       // eor	w16, w16, w10, lsl #16
	WORD $0x4a4a4210       // eor	w16, w16, w10, lsr #16
	WORD $0x4a0a6210       // eor	w16, w16, w10, lsl #24
	WORD $0x4a0e016b       // eor	w11, w11, w14
	WORD $0x4a0e01ee       // eor	w14, w15, w14
	WORD $0x4a4a620a       // eor	w10, w16, w10, lsr #24
	WORD $0x4a0a0170       // eor	w16, w11, w10
	WORD $0x4a0b01eb       // eor	w11, w15, w11
	WORD $0x4a1001cf       // eor	w15, w14, w16
	WORD $0x4a0a01ca       // eor	w10, w14, w10
	WORD $0x0a0a2108       // and	w8, w8, w10, lsl #8
	WORD $0x0a4a2129       // and	w9, w9, w10, lsr #8
	WORD $0x2a090108       // orr	w8, w8, w9
	WORD $0x5ac00969       // rev	w9, w11
	WORD $0x138f41ea       // ror	w10, w15, #16
	WORD $0x4a0a0108       // eor	w8, w8, w10
	WORD $0x4a09014a       // eor	w10, w10, w9
	WORD $0x4a10010b       // eor	w11, w8, w16
	WORD $0x4a090108       // eor	w8, w8, w9
	WORD $0x4a0a0169       // eor	w9, w11, w10
	WORD $0xb90001ab       // str	w11, [x13]
	WORD $0x4a10014a       // eor	w10, w10, w16
	WORD $0x293ea58a       // stp	w10, w9, [x12, #-12]
	WORD $0xb81fc188       // stur	w8, [x12, #-4]
	WORD $0xa8c17bfd       // ldp	x29, x30, [sp], #16             ; 16-byte Folded Reload
	WORD $0xd65f03c0       // ret

TEXT ·Crypt(SB), $0-32
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	MOVD rk+16(FP), R2
	MOVD rounds+24(FP), R3
	WORD $0xa9bf7bfd       // stp	x29, x30, [sp, #-16]!           ; 16-byte Folded Spill
	WORD $0x910003fd       // mov	x29, sp
	WORD $0x32089fec       // mov	w12, #-16711936                 ; =0xff00ff00
	WORD $0x32009fed       // mov	w13, #16711935                  ; =0xff00ff
	WORD $0x29402428       // ldp	w8, w9, [x1]
	WORD $0x5ac00910       // rev	w16, w8
	WORD $0x5ac00931       // rev	w17, w9
	WORD $0x29412828       // ldp	w8, w10, [x1, #8]
	WORD $0x5ac0090f       // rev	w15, w8
	WORD $0x90000009       // adrp	x9, _S1@PAGE
	WORD $0x91000129       // add	x9, x9, _S1@PAGEOFF
	WORD $0x90000008       // adrp	x8, _S2@PAGE
	WORD $0x91000108       // add	x8, x8, _S2@PAGEOFF
	WORD $0x5ac0094e       // rev	w14, w10
	WORD $0x9000000b       // adrp	x11, _X1@PAGE
	WORD $0x9100016b       // add	x11, x11, _X1@PAGEOFF
	WORD $0x9000000a       // adrp	x10, _X2@PAGE
	WORD $0x9100014a       // add	x10, x10, _X2@PAGEOFF
	WORD $0xf100347f       // cmp	x3, #13
	WORD $0x54002243       // b.lo	LBB2_4
	WORD $0x29401041       // ldp	w1, w4, [x2]
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x4a110091       // eor	w17, w4, w17
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x29411444       // ldp	w4, w5, [x2, #8]
	WORD $0x4a0f008f       // eor	w15, w4, w15
	WORD $0x4a0e00ae       // eor	w14, w5, w14
	WORD $0x53105e04       // ubfx	w4, w16, #16, #8
	WORD $0xb8645904       // ldr	w4, [x8, w4, uxtw #2]
	WORD $0x53083e05       // ubfx	w5, w16, #8, #8
	WORD $0xb8655965       // ldr	w5, [x11, w5, uxtw #2]
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705950       // ldr	w16, [x10, w16, uxtw #2]
	WORD $0x4a1000b0       // eor	w16, w5, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187e21       // lsr	w1, w17, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e24       // ubfx	w4, w17, #16, #8
	WORD $0xb8645904       // ldr	w4, [x8, w4, uxtw #2]
	WORD $0x53083e25       // ubfx	w5, w17, #8, #8
	WORD $0xb8655965       // ldr	w5, [x11, w5, uxtw #2]
	WORD $0x12001e31       // and	w17, w17, #0xff
	WORD $0xb8715951       // ldr	w17, [x10, w17, uxtw #2]
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a1100b1       // eor	w17, w5, w17
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x53187de1       // lsr	w1, w15, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105de4       // ubfx	w4, w15, #16, #8
	WORD $0xb8645904       // ldr	w4, [x8, w4, uxtw #2]
	WORD $0x53083de5       // ubfx	w5, w15, #8, #8
	WORD $0xb8655965       // ldr	w5, [x11, w5, uxtw #2]
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x12001def       // and	w15, w15, #0xff
	WORD $0xb86f594f       // ldr	w15, [x10, w15, uxtw #2]
	WORD $0x4a0f00af       // eor	w15, w5, w15
	WORD $0x4a0f002f       // eor	w15, w1, w15
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105dc4       // ubfx	w4, w14, #16, #8
	WORD $0xb8645904       // ldr	w4, [x8, w4, uxtw #2]
	WORD $0x53083dc5       // ubfx	w5, w14, #8, #8
	WORD $0xb8655965       // ldr	w5, [x11, w5, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e594e       // ldr	w14, [x10, w14, uxtw #2]
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a0e00ae       // eor	w14, w5, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a0f0231       // eor	w17, w17, w15
	WORD $0x4a0f01cf       // eor	w15, w14, w15
	WORD $0x4a100221       // eor	w1, w17, w16
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a0101f1       // eor	w17, w15, w1
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x0a0f2190       // and	w16, w12, w15, lsl #8
	WORD $0x0a4f21af       // and	w15, w13, w15, lsr #8
	WORD $0x2a0f020f       // orr	w15, w16, w15
	WORD $0x13914230       // ror	w16, w17, #16
	WORD $0x5ac009ce       // rev	w14, w14
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x4a0e0210       // eor	w16, w16, w14
	WORD $0x29421051       // ldp	w17, w4, [x2, #16]
	WORD $0x4a010084       // eor	w4, w4, w1
	WORD $0x4a100084       // eor	w4, w4, w16
	WORD $0x29431845       // ldp	w5, w6, [x2, #24]
	WORD $0x4a050210       // eor	w16, w16, w5
	WORD $0x4a0101e1       // eor	w1, w15, w1
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x4a010210       // eor	w16, w16, w1
	WORD $0x53187e21       // lsr	w1, w17, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x4a0e00ce       // eor	w14, w6, w14
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x53105e2f       // ubfx	w15, w17, #16, #8
	WORD $0xb86f594f       // ldr	w15, [x10, w15, uxtw #2]
	WORD $0x4a0101ef       // eor	w15, w15, w1
	WORD $0x53083e21       // ubfx	w1, w17, #8, #8
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x12001e31       // and	w17, w17, #0xff
	WORD $0xb8715911       // ldr	w17, [x8, w17, uxtw #2]
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x53187c91       // lsr	w17, w4, #24
	WORD $0xb8715971       // ldr	w17, [x11, w17, uxtw #2]
	WORD $0x53105c81       // ubfx	w1, w4, #16, #8
	WORD $0xb8615941       // ldr	w1, [x10, w1, uxtw #2]
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x53083c81       // ubfx	w1, w4, #8, #8
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x12001c84       // and	w4, w4, #0xff
	WORD $0xb8645904       // ldr	w4, [x8, w4, uxtw #2]
	WORD $0x4a040021       // eor	w1, w1, w4
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105e04       // ubfx	w4, w16, #16, #8
	WORD $0xb8645944       // ldr	w4, [x10, w4, uxtw #2]
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x53083e04       // ubfx	w4, w16, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705910       // ldr	w16, [x8, w16, uxtw #2]
	WORD $0x4a100090       // eor	w16, w4, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105dc4       // ubfx	w4, w14, #16, #8
	WORD $0xb8645944       // ldr	w4, [x10, w4, uxtw #2]
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x53083dc4       // ubfx	w4, w14, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e590e       // ldr	w14, [x8, w14, uxtw #2]
	WORD $0x4a0e008e       // eor	w14, w4, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a100231       // eor	w17, w17, w16
	WORD $0x4a1001d0       // eor	w16, w14, w16
	WORD $0x4a0f0221       // eor	w1, w17, w15
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0f020f       // eor	w15, w16, w15
	WORD $0x0a0e2190       // and	w16, w12, w14, lsl #8
	WORD $0x0a4e21ae       // and	w14, w13, w14, lsr #8
	WORD $0x2a0e020e       // orr	w14, w16, w14
	WORD $0x13814021       // ror	w1, w1, #16
	WORD $0x5ac009ef       // rev	w15, w15
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a1101d1       // eor	w17, w14, w17
	WORD $0x4a0101f0       // eor	w16, w15, w1
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x4a10022f       // eor	w15, w17, w16
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0xf1003c7f       // cmp	x3, #15
	WORD $0x54001123       // b.lo	LBB2_3
	WORD $0x29440c41       // ldp	w1, w3, [x2, #32]
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x4a110071       // eor	w17, w3, w17
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x29451043       // ldp	w3, w4, [x2, #40]
	WORD $0x4a0f006f       // eor	w15, w3, w15
	WORD $0x4a0e008e       // eor	w14, w4, w14
	WORD $0x53105e03       // ubfx	w3, w16, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083e04       // ubfx	w4, w16, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705950       // ldr	w16, [x10, w16, uxtw #2]
	WORD $0x4a100090       // eor	w16, w4, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187e21       // lsr	w1, w17, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e23       // ubfx	w3, w17, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083e24       // ubfx	w4, w17, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x12001e31       // and	w17, w17, #0xff
	WORD $0xb8715951       // ldr	w17, [x10, w17, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x4a110091       // eor	w17, w4, w17
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x53187de1       // lsr	w1, w15, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105de3       // ubfx	w3, w15, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083de4       // ubfx	w4, w15, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x12001def       // and	w15, w15, #0xff
	WORD $0xb86f594f       // ldr	w15, [x10, w15, uxtw #2]
	WORD $0x4a0f008f       // eor	w15, w4, w15
	WORD $0x4a0f002f       // eor	w15, w1, w15
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105dc3       // ubfx	w3, w14, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083dc4       // ubfx	w4, w14, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e594e       // ldr	w14, [x10, w14, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x4a0e008e       // eor	w14, w4, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a0f0231       // eor	w17, w17, w15
	WORD $0x4a0f01cf       // eor	w15, w14, w15
	WORD $0x4a100221       // eor	w1, w17, w16
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a0101f1       // eor	w17, w15, w1
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x0a0f2190       // and	w16, w12, w15, lsl #8
	WORD $0x0a4f21af       // and	w15, w13, w15, lsr #8
	WORD $0x2a0f020f       // orr	w15, w16, w15
	WORD $0x13914230       // ror	w16, w17, #16
	WORD $0x5ac009ce       // rev	w14, w14
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x4a0e0210       // eor	w16, w16, w14
	WORD $0x29460c51       // ldp	w17, w3, [x2, #48]
	WORD $0x4a010063       // eor	w3, w3, w1
	WORD $0x4a100063       // eor	w3, w3, w16
	WORD $0x29471444       // ldp	w4, w5, [x2, #56]
	WORD $0x4a040210       // eor	w16, w16, w4
	WORD $0x4a0101e1       // eor	w1, w15, w1
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x4a010210       // eor	w16, w16, w1
	WORD $0x53187e21       // lsr	w1, w17, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x4a0e00ae       // eor	w14, w5, w14
	WORD $0x53105e24       // ubfx	w4, w17, #16, #8
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x91010042       // add	x2, x2, #64
	WORD $0xb864594f       // ldr	w15, [x10, w4, uxtw #2]
	WORD $0x53083e24       // ubfx	w4, w17, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x12001e31       // and	w17, w17, #0xff
	WORD $0xb8715911       // ldr	w17, [x8, w17, uxtw #2]
	WORD $0x4a0101ef       // eor	w15, w15, w1
	WORD $0x4a110091       // eor	w17, w4, w17
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x53187c71       // lsr	w17, w3, #24
	WORD $0xb8715971       // ldr	w17, [x11, w17, uxtw #2]
	WORD $0x53105c61       // ubfx	w1, w3, #16, #8
	WORD $0xb8615941       // ldr	w1, [x10, w1, uxtw #2]
	WORD $0x53083c64       // ubfx	w4, w3, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x12001c61       // and	w1, w3, #0xff
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105e03       // ubfx	w3, w16, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x53083e04       // ubfx	w4, w16, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705910       // ldr	w16, [x8, w16, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x4a100090       // eor	w16, w4, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105dc3       // ubfx	w3, w14, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x53083dc4       // ubfx	w4, w14, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e590e       // ldr	w14, [x8, w14, uxtw #2]
	WORD $0x4a0e008e       // eor	w14, w4, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a100231       // eor	w17, w17, w16
	WORD $0x4a1001d0       // eor	w16, w14, w16
	WORD $0x4a0f0221       // eor	w1, w17, w15
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0f020f       // eor	w15, w16, w15
	WORD $0x0a0e2190       // and	w16, w12, w14, lsl #8
	WORD $0x0a4e21ae       // and	w14, w13, w14, lsr #8
	WORD $0x2a0e020e       // orr	w14, w16, w14
	WORD $0x13814021       // ror	w1, w1, #16
	WORD $0x5ac009ef       // rev	w15, w15
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a1101d1       // eor	w17, w14, w17
	WORD $0x4a0101f0       // eor	w16, w15, w1
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x4a10022f       // eor	w15, w17, w16
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x14000002       // b	LBB2_4
	WORD $0x91008042       // add	x2, x2, #32
	WORD $0x29400c41       // ldp	w1, w3, [x2]
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x4a110071       // eor	w17, w3, w17
	WORD $0x29410c41       // ldp	w1, w3, [x2, #8]
	WORD $0x4a0f002f       // eor	w15, w1, w15
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e03       // ubfx	w3, w16, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083e03       // ubfx	w3, w16, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705950       // ldr	w16, [x10, w16, uxtw #2]
	WORD $0x4a100070       // eor	w16, w3, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187e21       // lsr	w1, w17, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e23       // ubfx	w3, w17, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083e23       // ubfx	w3, w17, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001e31       // and	w17, w17, #0xff
	WORD $0xb8715951       // ldr	w17, [x10, w17, uxtw #2]
	WORD $0x4a110071       // eor	w17, w3, w17
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x53187de1       // lsr	w1, w15, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105de3       // ubfx	w3, w15, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083de3       // ubfx	w3, w15, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001def       // and	w15, w15, #0xff
	WORD $0xb86f594f       // ldr	w15, [x10, w15, uxtw #2]
	WORD $0x4a0f006f       // eor	w15, w3, w15
	WORD $0x4a0f002f       // eor	w15, w1, w15
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105dc3       // ubfx	w3, w14, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083dc3       // ubfx	w3, w14, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e594e       // ldr	w14, [x10, w14, uxtw #2]
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a0f0231       // eor	w17, w17, w15
	WORD $0x4a0f01cf       // eor	w15, w14, w15
	WORD $0x4a100221       // eor	w1, w17, w16
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a0101f1       // eor	w17, w15, w1
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x0a0f2190       // and	w16, w12, w15, lsl #8
	WORD $0x0a4f21af       // and	w15, w13, w15, lsr #8
	WORD $0x13914231       // ror	w17, w17, #16
	WORD $0x2a0f020f       // orr	w15, w16, w15
	WORD $0x5ac009ce       // rev	w14, w14
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a0e0230       // eor	w16, w17, w14
	WORD $0x4a0101f1       // eor	w17, w15, w1
	WORD $0x29421043       // ldp	w3, w4, [x2, #16]
	WORD $0x4a030223       // eor	w3, w17, w3
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a100021       // eor	w1, w1, w16
	WORD $0x29431444       // ldp	w4, w5, [x2, #24]
	WORD $0x4a040210       // eor	w16, w16, w4
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x4a0e00ae       // eor	w14, w5, w14
	WORD $0x53187c71       // lsr	w17, w3, #24
	WORD $0xb8715971       // ldr	w17, [x11, w17, uxtw #2]
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x53105c6f       // ubfx	w15, w3, #16, #8
	WORD $0xb86f594f       // ldr	w15, [x10, w15, uxtw #2]
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x53083c71       // ubfx	w17, w3, #8, #8
	WORD $0xb8715931       // ldr	w17, [x9, w17, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a030231       // eor	w17, w17, w3
	WORD $0x53187c23       // lsr	w3, w1, #24
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x53105c24       // ubfx	w4, w1, #16, #8
	WORD $0xb8645944       // ldr	w4, [x10, w4, uxtw #2]
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a030091       // eor	w17, w4, w3
	WORD $0x53083c23       // ubfx	w3, w1, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001c21       // and	w1, w1, #0xff
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53187e03       // lsr	w3, w16, #24
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x53105e01       // ubfx	w1, w16, #16, #8
	WORD $0xb8615941       // ldr	w1, [x10, w1, uxtw #2]
	WORD $0x4a030021       // eor	w1, w1, w3
	WORD $0x53083e03       // ubfx	w3, w16, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705910       // ldr	w16, [x8, w16, uxtw #2]
	WORD $0x4a100070       // eor	w16, w3, w16
	WORD $0x53187dc3       // lsr	w3, w14, #24
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x53105dc4       // ubfx	w4, w14, #16, #8
	WORD $0xb8645944       // ldr	w4, [x10, w4, uxtw #2]
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x4a030081       // eor	w1, w4, w3
	WORD $0x53083dc3       // ubfx	w3, w14, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e590e       // ldr	w14, [x8, w14, uxtw #2]
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a100231       // eor	w17, w17, w16
	WORD $0x4a1001d0       // eor	w16, w14, w16
	WORD $0x4a0f0221       // eor	w1, w17, w15
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0f020f       // eor	w15, w16, w15
	WORD $0x0a0e2190       // and	w16, w12, w14, lsl #8
	WORD $0x0a4e21ae       // and	w14, w13, w14, lsr #8
	WORD $0x2a0e020e       // orr	w14, w16, w14
	WORD $0x13814030       // ror	w16, w1, #16
	WORD $0x5ac009ef       // rev	w15, w15
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a1101d1       // eor	w17, w14, w17
	WORD $0x4a1001e1       // eor	w1, w15, w16
	WORD $0x29441043       // ldp	w3, w4, [x2, #32]
	WORD $0x4a030023       // eor	w3, w1, w3
	WORD $0x4a100090       // eor	w16, w4, w16
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x29451444       // ldp	w4, w5, [x2, #40]
	WORD $0x4a040021       // eor	w1, w1, w4
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x4a0501ef       // eor	w15, w15, w5
	WORD $0x4a0e01ee       // eor	w14, w15, w14
	WORD $0x53187c6f       // lsr	w15, w3, #24
	WORD $0xb86f592f       // ldr	w15, [x9, w15, uxtw #2]
	WORD $0x53105c61       // ubfx	w1, w3, #16, #8
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x53083c64       // ubfx	w4, w3, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a0f002f       // eor	w15, w1, w15
	WORD $0x4a030081       // eor	w1, w4, w3
	WORD $0x4a0101ef       // eor	w15, w15, w1
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e03       // ubfx	w3, w16, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083e04       // ubfx	w4, w16, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705950       // ldr	w16, [x10, w16, uxtw #2]
	WORD $0x4a100090       // eor	w16, w4, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187e21       // lsr	w1, w17, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e23       // ubfx	w3, w17, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083e24       // ubfx	w4, w17, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x12001e31       // and	w17, w17, #0xff
	WORD $0xb8715951       // ldr	w17, [x10, w17, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x4a110091       // eor	w17, w4, w17
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105dc3       // ubfx	w3, w14, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083dc4       // ubfx	w4, w14, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e594e       // ldr	w14, [x10, w14, uxtw #2]
	WORD $0x4a0e008e       // eor	w14, w4, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x4a1101d1       // eor	w17, w14, w17
	WORD $0x4a0f0201       // eor	w1, w16, w15
	WORD $0x4a1001ce       // eor	w14, w14, w16
	WORD $0x4a010230       // eor	w16, w17, w1
	WORD $0x4a0f022f       // eor	w15, w17, w15
	WORD $0x0a0f2191       // and	w17, w12, w15, lsl #8
	WORD $0x0a4f21af       // and	w15, w13, w15, lsr #8
	WORD $0x2a0f022f       // orr	w15, w17, w15
	WORD $0x13904210       // ror	w16, w16, #16
	WORD $0x5ac009ce       // rev	w14, w14
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x4a0e0210       // eor	w16, w16, w14
	WORD $0x4a0101f1       // eor	w17, w15, w1
	WORD $0x29461043       // ldp	w3, w4, [x2, #48]
	WORD $0x4a030223       // eor	w3, w17, w3
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a100021       // eor	w1, w1, w16
	WORD $0x29471444       // ldp	w4, w5, [x2, #56]
	WORD $0x4a040210       // eor	w16, w16, w4
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x4a0e00ae       // eor	w14, w5, w14
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x53187c6f       // lsr	w15, w3, #24
	WORD $0xb86f596f       // ldr	w15, [x11, w15, uxtw #2]
	WORD $0x53105c71       // ubfx	w17, w3, #16, #8
	WORD $0xb8715951       // ldr	w17, [x10, w17, uxtw #2]
	WORD $0x4a0f022f       // eor	w15, w17, w15
	WORD $0x53083c71       // ubfx	w17, w3, #8, #8
	WORD $0xb8715931       // ldr	w17, [x9, w17, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a030231       // eor	w17, w17, w3
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x53187c31       // lsr	w17, w1, #24
	WORD $0xb8715971       // ldr	w17, [x11, w17, uxtw #2]
	WORD $0x53105c23       // ubfx	w3, w1, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a110071       // eor	w17, w3, w17
	WORD $0x53083c23       // ubfx	w3, w1, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001c21       // and	w1, w1, #0xff
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105e03       // ubfx	w3, w16, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083e03       // ubfx	w3, w16, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705910       // ldr	w16, [x8, w16, uxtw #2]
	WORD $0x4a100070       // eor	w16, w3, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105dc3       // ubfx	w3, w14, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083dc3       // ubfx	w3, w14, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e590e       // ldr	w14, [x8, w14, uxtw #2]
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a100231       // eor	w17, w17, w16
	WORD $0x4a1001d0       // eor	w16, w14, w16
	WORD $0x4a0f0221       // eor	w1, w17, w15
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0f020f       // eor	w15, w16, w15
	WORD $0x0a0e2190       // and	w16, w12, w14, lsl #8
	WORD $0x0a4e21ae       // and	w14, w13, w14, lsr #8
	WORD $0x13814021       // ror	w1, w1, #16
	WORD $0x2a0e020e       // orr	w14, w16, w14
	WORD $0x5ac009ef       // rev	w15, w15
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a1101d0       // eor	w16, w14, w17
	WORD $0x4a0101f1       // eor	w17, w15, w1
	WORD $0x29481043       // ldp	w3, w4, [x2, #64]
	WORD $0x4a030223       // eor	w3, w17, w3
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a100021       // eor	w1, w1, w16
	WORD $0x29491444       // ldp	w4, w5, [x2, #72]
	WORD $0x4a040231       // eor	w17, w17, w4
	WORD $0x4a100230       // eor	w16, w17, w16
	WORD $0x4a0501ef       // eor	w15, w15, w5
	WORD $0x53187c71       // lsr	w17, w3, #24
	WORD $0xb8715931       // ldr	w17, [x9, w17, uxtw #2]
	WORD $0x4a0e01ee       // eor	w14, w15, w14
	WORD $0x53105c6f       // ubfx	w15, w3, #16, #8
	WORD $0xb86f590f       // ldr	w15, [x8, w15, uxtw #2]
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x53083c71       // ubfx	w17, w3, #8, #8
	WORD $0xb8715971       // ldr	w17, [x11, w17, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a030231       // eor	w17, w17, w3
	WORD $0x53187c23       // lsr	w3, w1, #24
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x53105c24       // ubfx	w4, w1, #16, #8
	WORD $0xb8645904       // ldr	w4, [x8, w4, uxtw #2]
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a030091       // eor	w17, w4, w3
	WORD $0x53083c23       // ubfx	w3, w1, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001c21       // and	w1, w1, #0xff
	WORD $0xb8615941       // ldr	w1, [x10, w1, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53187e03       // lsr	w3, w16, #24
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x53105e01       // ubfx	w1, w16, #16, #8
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x4a030021       // eor	w1, w1, w3
	WORD $0x53083e03       // ubfx	w3, w16, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705950       // ldr	w16, [x10, w16, uxtw #2]
	WORD $0x4a100070       // eor	w16, w3, w16
	WORD $0x53187dc3       // lsr	w3, w14, #24
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x53105dc4       // ubfx	w4, w14, #16, #8
	WORD $0xb8645904       // ldr	w4, [x8, w4, uxtw #2]
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x4a030081       // eor	w1, w4, w3
	WORD $0x53083dc3       // ubfx	w3, w14, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e594e       // ldr	w14, [x10, w14, uxtw #2]
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a100231       // eor	w17, w17, w16
	WORD $0x4a1001d0       // eor	w16, w14, w16
	WORD $0x4a0f0221       // eor	w1, w17, w15
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0f020f       // eor	w15, w16, w15
	WORD $0x0a0f2190       // and	w16, w12, w15, lsl #8
	WORD $0x0a4f21af       // and	w15, w13, w15, lsr #8
	WORD $0x2a0f020f       // orr	w15, w16, w15
	WORD $0x13914230       // ror	w16, w17, #16
	WORD $0x5ac009ce       // rev	w14, w14
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x4a0e0210       // eor	w16, w16, w14
	WORD $0x4a0101f1       // eor	w17, w15, w1
	WORD $0x294a1043       // ldp	w3, w4, [x2, #80]
	WORD $0x4a030223       // eor	w3, w17, w3
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a100021       // eor	w1, w1, w16
	WORD $0x294b1444       // ldp	w4, w5, [x2, #88]
	WORD $0x4a040210       // eor	w16, w16, w4
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x4a0e00ae       // eor	w14, w5, w14
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x53187c6f       // lsr	w15, w3, #24
	WORD $0xb86f596f       // ldr	w15, [x11, w15, uxtw #2]
	WORD $0x53105c71       // ubfx	w17, w3, #16, #8
	WORD $0xb8715951       // ldr	w17, [x10, w17, uxtw #2]
	WORD $0x53083c64       // ubfx	w4, w3, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a0f022f       // eor	w15, w17, w15
	WORD $0x4a030091       // eor	w17, w4, w3
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x53187c31       // lsr	w17, w1, #24
	WORD $0xb8715971       // ldr	w17, [x11, w17, uxtw #2]
	WORD $0x53105c23       // ubfx	w3, w1, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x53083c24       // ubfx	w4, w1, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x4a110071       // eor	w17, w3, w17
	WORD $0x12001c21       // and	w1, w1, #0xff
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105e03       // ubfx	w3, w16, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x53083e04       // ubfx	w4, w16, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705910       // ldr	w16, [x8, w16, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x4a100090       // eor	w16, w4, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105dc3       // ubfx	w3, w14, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x53083dc4       // ubfx	w4, w14, #8, #8
	WORD $0xb8645924       // ldr	w4, [x9, w4, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e590e       // ldr	w14, [x8, w14, uxtw #2]
	WORD $0x4a0e008e       // eor	w14, w4, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a100231       // eor	w17, w17, w16
	WORD $0x4a1001d0       // eor	w16, w14, w16
	WORD $0x4a0f0221       // eor	w1, w17, w15
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0f020f       // eor	w15, w16, w15
	WORD $0x0a0e2190       // and	w16, w12, w14, lsl #8
	WORD $0x0a4e21ae       // and	w14, w13, w14, lsr #8
	WORD $0x2a0e020e       // orr	w14, w16, w14
	WORD $0x13814030       // ror	w16, w1, #16
	WORD $0x5ac009ef       // rev	w15, w15
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a1101d1       // eor	w17, w14, w17
	WORD $0x4a1001e1       // eor	w1, w15, w16
	WORD $0x294c1043       // ldp	w3, w4, [x2, #96]
	WORD $0x4a030023       // eor	w3, w1, w3
	WORD $0x4a100090       // eor	w16, w4, w16
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x294d1444       // ldp	w4, w5, [x2, #104]
	WORD $0x4a040021       // eor	w1, w1, w4
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x4a0501ef       // eor	w15, w15, w5
	WORD $0x4a0e01ee       // eor	w14, w15, w14
	WORD $0x53187c6f       // lsr	w15, w3, #24
	WORD $0xb86f592f       // ldr	w15, [x9, w15, uxtw #2]
	WORD $0x53105c61       // ubfx	w1, w3, #16, #8
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x4a0f002f       // eor	w15, w1, w15
	WORD $0x53083c61       // ubfx	w1, w3, #8, #8
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a030021       // eor	w1, w1, w3
	WORD $0x4a0101ef       // eor	w15, w15, w1
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e03       // ubfx	w3, w16, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083e03       // ubfx	w3, w16, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705950       // ldr	w16, [x10, w16, uxtw #2]
	WORD $0x4a100070       // eor	w16, w3, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187e21       // lsr	w1, w17, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e23       // ubfx	w3, w17, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083e23       // ubfx	w3, w17, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001e31       // and	w17, w17, #0xff
	WORD $0xb8715951       // ldr	w17, [x10, w17, uxtw #2]
	WORD $0x4a110071       // eor	w17, w3, w17
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105dc3       // ubfx	w3, w14, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083dc3       // ubfx	w3, w14, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e594e       // ldr	w14, [x10, w14, uxtw #2]
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x4a1101d1       // eor	w17, w14, w17
	WORD $0x4a0f0201       // eor	w1, w16, w15
	WORD $0x4a1001ce       // eor	w14, w14, w16
	WORD $0x4a010230       // eor	w16, w17, w1
	WORD $0x4a0f022f       // eor	w15, w17, w15
	WORD $0x0a0f2191       // and	w17, w12, w15, lsl #8
	WORD $0x0a4f21af       // and	w15, w13, w15, lsr #8
	WORD $0x13904210       // ror	w16, w16, #16
	WORD $0x2a0f022f       // orr	w15, w17, w15
	WORD $0x5ac009ce       // rev	w14, w14
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x4a0e0210       // eor	w16, w16, w14
	WORD $0x4a0101f1       // eor	w17, w15, w1
	WORD $0x294e1043       // ldp	w3, w4, [x2, #112]
	WORD $0x4a030223       // eor	w3, w17, w3
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a100021       // eor	w1, w1, w16
	WORD $0x294f1444       // ldp	w4, w5, [x2, #120]
	WORD $0x4a040210       // eor	w16, w16, w4
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x4a0e00ae       // eor	w14, w5, w14
	WORD $0x53187c71       // lsr	w17, w3, #24
	WORD $0xb8715971       // ldr	w17, [x11, w17, uxtw #2]
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x53105c6f       // ubfx	w15, w3, #16, #8
	WORD $0xb86f594f       // ldr	w15, [x10, w15, uxtw #2]
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x53083c71       // ubfx	w17, w3, #8, #8
	WORD $0xb8715931       // ldr	w17, [x9, w17, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a030231       // eor	w17, w17, w3
	WORD $0x53187c23       // lsr	w3, w1, #24
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x53105c24       // ubfx	w4, w1, #16, #8
	WORD $0xb8645944       // ldr	w4, [x10, w4, uxtw #2]
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a030091       // eor	w17, w4, w3
	WORD $0x53083c23       // ubfx	w3, w1, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001c21       // and	w1, w1, #0xff
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53187e03       // lsr	w3, w16, #24
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x53105e01       // ubfx	w1, w16, #16, #8
	WORD $0xb8615941       // ldr	w1, [x10, w1, uxtw #2]
	WORD $0x4a030021       // eor	w1, w1, w3
	WORD $0x53083e03       // ubfx	w3, w16, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705910       // ldr	w16, [x8, w16, uxtw #2]
	WORD $0x4a100070       // eor	w16, w3, w16
	WORD $0x53187dc3       // lsr	w3, w14, #24
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x53105dc4       // ubfx	w4, w14, #16, #8
	WORD $0xb8645944       // ldr	w4, [x10, w4, uxtw #2]
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x4a030081       // eor	w1, w4, w3
	WORD $0x53083dc3       // ubfx	w3, w14, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e590e       // ldr	w14, [x8, w14, uxtw #2]
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a100231       // eor	w17, w17, w16
	WORD $0x4a1001d0       // eor	w16, w14, w16
	WORD $0x4a0f0221       // eor	w1, w17, w15
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0f020f       // eor	w15, w16, w15
	WORD $0x0a0e2190       // and	w16, w12, w14, lsl #8
	WORD $0x0a4e21ae       // and	w14, w13, w14, lsr #8
	WORD $0x2a0e020e       // orr	w14, w16, w14
	WORD $0x13814030       // ror	w16, w1, #16
	WORD $0x5ac009ef       // rev	w15, w15
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a1101d1       // eor	w17, w14, w17
	WORD $0x4a1001e1       // eor	w1, w15, w16
	WORD $0x29501043       // ldp	w3, w4, [x2, #128]
	WORD $0x4a030023       // eor	w3, w1, w3
	WORD $0x4a100090       // eor	w16, w4, w16
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x29511444       // ldp	w4, w5, [x2, #136]
	WORD $0x4a040021       // eor	w1, w1, w4
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x4a0501ef       // eor	w15, w15, w5
	WORD $0x4a0e01ee       // eor	w14, w15, w14
	WORD $0x53187c6f       // lsr	w15, w3, #24
	WORD $0xb86f592f       // ldr	w15, [x9, w15, uxtw #2]
	WORD $0x53105c61       // ubfx	w1, w3, #16, #8
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x53083c64       // ubfx	w4, w3, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a0f002f       // eor	w15, w1, w15
	WORD $0x4a030081       // eor	w1, w4, w3
	WORD $0x4a0101ef       // eor	w15, w15, w1
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e03       // ubfx	w3, w16, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083e04       // ubfx	w4, w16, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705950       // ldr	w16, [x10, w16, uxtw #2]
	WORD $0x4a100090       // eor	w16, w4, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187e21       // lsr	w1, w17, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105e23       // ubfx	w3, w17, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083e24       // ubfx	w4, w17, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x12001e31       // and	w17, w17, #0xff
	WORD $0xb8715951       // ldr	w17, [x10, w17, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x4a110091       // eor	w17, w4, w17
	WORD $0x4a110031       // eor	w17, w1, w17
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x53105dc3       // ubfx	w3, w14, #16, #8
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x53083dc4       // ubfx	w4, w14, #8, #8
	WORD $0xb8645964       // ldr	w4, [x11, w4, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e594e       // ldr	w14, [x10, w14, uxtw #2]
	WORD $0x4a0e008e       // eor	w14, w4, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x4a1101d1       // eor	w17, w14, w17
	WORD $0x4a0f0201       // eor	w1, w16, w15
	WORD $0x4a1001ce       // eor	w14, w14, w16
	WORD $0x4a010230       // eor	w16, w17, w1
	WORD $0x4a0f022f       // eor	w15, w17, w15
	WORD $0x0a0f2191       // and	w17, w12, w15, lsl #8
	WORD $0x0a4f21af       // and	w15, w13, w15, lsr #8
	WORD $0x2a0f022f       // orr	w15, w17, w15
	WORD $0x13904210       // ror	w16, w16, #16
	WORD $0x5ac009ce       // rev	w14, w14
	WORD $0x4a1001ef       // eor	w15, w15, w16
	WORD $0x4a0e0210       // eor	w16, w16, w14
	WORD $0x4a0101f1       // eor	w17, w15, w1
	WORD $0x29521043       // ldp	w3, w4, [x2, #144]
	WORD $0x4a030223       // eor	w3, w17, w3
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x4a100021       // eor	w1, w1, w16
	WORD $0x29531444       // ldp	w4, w5, [x2, #152]
	WORD $0x4a040210       // eor	w16, w16, w4
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x4a0e00ae       // eor	w14, w5, w14
	WORD $0x4a0f01ce       // eor	w14, w14, w15
	WORD $0x53187c6f       // lsr	w15, w3, #24
	WORD $0xb86f596f       // ldr	w15, [x11, w15, uxtw #2]
	WORD $0x53105c71       // ubfx	w17, w3, #16, #8
	WORD $0xb8715951       // ldr	w17, [x10, w17, uxtw #2]
	WORD $0x4a0f022f       // eor	w15, w17, w15
	WORD $0x53083c71       // ubfx	w17, w3, #8, #8
	WORD $0xb8715931       // ldr	w17, [x9, w17, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635903       // ldr	w3, [x8, w3, uxtw #2]
	WORD $0x4a030231       // eor	w17, w17, w3
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x53187c31       // lsr	w17, w1, #24
	WORD $0xb8715971       // ldr	w17, [x11, w17, uxtw #2]
	WORD $0x53105c23       // ubfx	w3, w1, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a110071       // eor	w17, w3, w17
	WORD $0x53083c23       // ubfx	w3, w1, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001c21       // and	w1, w1, #0xff
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x53187e01       // lsr	w1, w16, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105e03       // ubfx	w3, w16, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083e03       // ubfx	w3, w16, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705910       // ldr	w16, [x8, w16, uxtw #2]
	WORD $0x4a100070       // eor	w16, w3, w16
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x53187dc1       // lsr	w1, w14, #24
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x53105dc3       // ubfx	w3, w14, #16, #8
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53083dc3       // ubfx	w3, w14, #8, #8
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e590e       // ldr	w14, [x8, w14, uxtw #2]
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a100231       // eor	w17, w17, w16
	WORD $0x4a1001d0       // eor	w16, w14, w16
	WORD $0x4a0f0221       // eor	w1, w17, w15
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0f020f       // eor	w15, w16, w15
	WORD $0x0a0e2190       // and	w16, w12, w14, lsl #8
	WORD $0x0a4e21ae       // and	w14, w13, w14, lsr #8
	WORD $0x13814021       // ror	w1, w1, #16
	WORD $0x2a0e020e       // orr	w14, w16, w14
	WORD $0x5ac009ef       // rev	w15, w15
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a0101f0       // eor	w16, w15, w1
	WORD $0x29541043       // ldp	w3, w4, [x2, #160]
	WORD $0x4a030203       // eor	w3, w16, w3
	WORD $0x4a010081       // eor	w1, w4, w1
	WORD $0x29551444       // ldp	w4, w5, [x2, #168]
	WORD $0x4a040210       // eor	w16, w16, w4
	WORD $0x4a1101d1       // eor	w17, w14, w17
	WORD $0x4a110021       // eor	w1, w1, w17
	WORD $0x4a110210       // eor	w16, w16, w17
	WORD $0x4a0501ef       // eor	w15, w15, w5
	WORD $0x53187c71       // lsr	w17, w3, #24
	WORD $0xb8715931       // ldr	w17, [x9, w17, uxtw #2]
	WORD $0x4a0e01ee       // eor	w14, w15, w14
	WORD $0x53105c6f       // ubfx	w15, w3, #16, #8
	WORD $0xb86f590f       // ldr	w15, [x8, w15, uxtw #2]
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x53083c71       // ubfx	w17, w3, #8, #8
	WORD $0xb8715971       // ldr	w17, [x11, w17, uxtw #2]
	WORD $0x12001c63       // and	w3, w3, #0xff
	WORD $0xb8635943       // ldr	w3, [x10, w3, uxtw #2]
	WORD $0x4a030231       // eor	w17, w17, w3
	WORD $0x53187c23       // lsr	w3, w1, #24
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x53105c24       // ubfx	w4, w1, #16, #8
	WORD $0xb8645904       // ldr	w4, [x8, w4, uxtw #2]
	WORD $0x4a1101ef       // eor	w15, w15, w17
	WORD $0x4a030091       // eor	w17, w4, w3
	WORD $0x53083c23       // ubfx	w3, w1, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001c21       // and	w1, w1, #0xff
	WORD $0xb8615941       // ldr	w1, [x10, w1, uxtw #2]
	WORD $0x4a010061       // eor	w1, w3, w1
	WORD $0x53187e03       // lsr	w3, w16, #24
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x53105e01       // ubfx	w1, w16, #16, #8
	WORD $0xb8615901       // ldr	w1, [x8, w1, uxtw #2]
	WORD $0x4a030021       // eor	w1, w1, w3
	WORD $0x53083e03       // ubfx	w3, w16, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705950       // ldr	w16, [x10, w16, uxtw #2]
	WORD $0x4a100070       // eor	w16, w3, w16
	WORD $0x53187dc3       // lsr	w3, w14, #24
	WORD $0xb8635923       // ldr	w3, [x9, w3, uxtw #2]
	WORD $0x53105dc4       // ubfx	w4, w14, #16, #8
	WORD $0xb8645904       // ldr	w4, [x8, w4, uxtw #2]
	WORD $0x4a100030       // eor	w16, w1, w16
	WORD $0x4a030081       // eor	w1, w4, w3
	WORD $0x53083dc3       // ubfx	w3, w14, #8, #8
	WORD $0xb8635963       // ldr	w3, [x11, w3, uxtw #2]
	WORD $0x12001dce       // and	w14, w14, #0xff
	WORD $0xb86e594e       // ldr	w14, [x10, w14, uxtw #2]
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x4a0e002e       // eor	w14, w1, w14
	WORD $0x4a100231       // eor	w17, w17, w16
	WORD $0x4a1001d0       // eor	w16, w14, w16
	WORD $0x4a0f0221       // eor	w1, w17, w15
	WORD $0x4a1101ce       // eor	w14, w14, w17
	WORD $0x4a010211       // eor	w17, w16, w1
	WORD $0x4a0f020f       // eor	w15, w16, w15
	WORD $0x0a0f218c       // and	w12, w12, w15, lsl #8
	WORD $0x0a4f21ad       // and	w13, w13, w15, lsr #8
	WORD $0x2a0d018c       // orr	w12, w12, w13
	WORD $0x53107e2d       // lsr	w13, w17, #16
	WORD $0x5ac009ce       // rev	w14, w14
	WORD $0x4a0d018c       // eor	w12, w12, w13
	WORD $0x4a0e01ad       // eor	w13, w13, w14
	WORD $0x4a01018f       // eor	w15, w12, w1
	WORD $0x29564450       // ldp	w16, w17, [x2, #176]
	WORD $0x4a1001f0       // eor	w16, w15, w16
	WORD $0x4a010231       // eor	w17, w17, w1
	WORD $0x4a0d0231       // eor	w17, w17, w13
	WORD $0x29570c41       // ldp	w1, w3, [x2, #184]
	WORD $0x4a0101ad       // eor	w13, w13, w1
	WORD $0x53032a01       // ubfx	w1, w16, #3, #8
	WORD $0xb8615961       // ldr	w1, [x11, w1, uxtw #2]
	WORD $0x39000001       // strb	w1, [x0]
	WORD $0x53022601       // ubfx	w1, w16, #2, #8
	WORD $0xb8615941       // ldr	w1, [x10, w1, uxtw #2]
	WORD $0x53087c21       // lsr	w1, w1, #8
	WORD $0x39000401       // strb	w1, [x0, #1]
	WORD $0x53012201       // ubfx	w1, w16, #1, #8
	WORD $0xb8615921       // ldr	w1, [x9, w1, uxtw #2]
	WORD $0x39000801       // strb	w1, [x0, #2]
	WORD $0x12001e10       // and	w16, w16, #0xff
	WORD $0xb8705910       // ldr	w16, [x8, w16, uxtw #2]
	WORD $0x4a0f01ad       // eor	w13, w13, w15
	WORD $0x39000c10       // strb	w16, [x0, #3]
	WORD $0x53032a2f       // ubfx	w15, w17, #3, #8
	WORD $0xb86f596f       // ldr	w15, [x11, w15, uxtw #2]
	WORD $0x3900100f       // strb	w15, [x0, #4]
	WORD $0x5302262f       // ubfx	w15, w17, #2, #8
	WORD $0xb86f594f       // ldr	w15, [x10, w15, uxtw #2]
	WORD $0x53087def       // lsr	w15, w15, #8
	WORD $0x3900140f       // strb	w15, [x0, #5]
	WORD $0x5301222f       // ubfx	w15, w17, #1, #8
	WORD $0xb86f592f       // ldr	w15, [x9, w15, uxtw #2]
	WORD $0x3900180f       // strb	w15, [x0, #6]
	WORD $0x12001e2f       // and	w15, w17, #0xff
	WORD $0xb86f590f       // ldr	w15, [x8, w15, uxtw #2]
	WORD $0x4a0e006e       // eor	w14, w3, w14
	WORD $0x39001c0f       // strb	w15, [x0, #7]
	WORD $0x530329af       // ubfx	w15, w13, #3, #8
	WORD $0xb86f596f       // ldr	w15, [x11, w15, uxtw #2]
	WORD $0x3900200f       // strb	w15, [x0, #8]
	WORD $0x530225af       // ubfx	w15, w13, #2, #8
	WORD $0xb86f594f       // ldr	w15, [x10, w15, uxtw #2]
	WORD $0x53087def       // lsr	w15, w15, #8
	WORD $0x3900240f       // strb	w15, [x0, #9]
	WORD $0x530121af       // ubfx	w15, w13, #1, #8
	WORD $0xb86f592f       // ldr	w15, [x9, w15, uxtw #2]
	WORD $0x3900280f       // strb	w15, [x0, #10]
	WORD $0x12001dad       // and	w13, w13, #0xff
	WORD $0xb86d590d       // ldr	w13, [x8, w13, uxtw #2]
	WORD $0x4a0c01cc       // eor	w12, w14, w12
	WORD $0x39002c0d       // strb	w13, [x0, #11]
	WORD $0x5303298d       // ubfx	w13, w12, #3, #8
	WORD $0xb86d596b       // ldr	w11, [x11, w13, uxtw #2]
	WORD $0x3900300b       // strb	w11, [x0, #12]
	WORD $0x5302258b       // ubfx	w11, w12, #2, #8
	WORD $0xb86b594a       // ldr	w10, [x10, w11, uxtw #2]
	WORD $0x53087d4a       // lsr	w10, w10, #8
	WORD $0x3900340a       // strb	w10, [x0, #13]
	WORD $0x5301218a       // ubfx	w10, w12, #1, #8
	WORD $0xb86a5929       // ldr	w9, [x9, w10, uxtw #2]
	WORD $0x39003809       // strb	w9, [x0, #14]
	WORD $0x12001d89       // and	w9, w12, #0xff
	WORD $0xb8695908       // ldr	w8, [x8, w9, uxtw #2]
	WORD $0x39003c08       // strb	w8, [x0, #15]
	WORD $0x3dc00000       // ldr	q0, [x0]
	WORD $0x3dc03041       // ldr	q1, [x2, #192]
	WORD $0x6e200821       // rev32.16b	v1, v1
	WORD $0x6e201c20       // eor.16b	v0, v1, v0
	WORD $0x3d800000       // str	q0, [x0]
	WORD $0xa8c17bfd       // ldp	x29, x30, [sp], #16             ; 16-byte Folded Reload
	WORD $0xd65f03c0       // ret
