name: cross-arch-test

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  cross-arch-test:
    strategy:
      matrix:
        include:
        - image: arm32v6/golang:1.15-alpine
          platform: linux/arm/v6
        - image: arm32v6/golang:1.16-alpine
          platform: linux/arm/v6
        - image: arm32v6/golang:1.17-alpine
          platform: linux/arm/v6
        - image: arm32v6/golang:1.18-alpine
          platform: linux/arm/v6
        - image: arm32v6/golang:1.19-alpine
          platform: linux/arm/v6
        - image: arm32v6/golang:1.20-alpine
          platform: linux/arm/v6
        - image: arm32v6/golang:1.21-alpine
          platform: linux/arm/v6
        - image: arm32v6/golang:1.22-alpine
          platform: linux/arm/v6
        - image: arm32v6/golang:1.23-alpine
          platform: linux/arm/v6
        - image: arm32v7/golang:1.15-alpine
          platform: linux/arm/v7
        - image: arm32v7/golang:1.16-alpine
          platform: linux/arm/v7
        - image: arm32v7/golang:1.17-alpine
          platform: linux/arm/v7
        - image: arm32v7/golang:1.18-alpine
          platform: linux/arm/v7
        - image: arm32v7/golang:1.19-alpine
          platform: linux/arm/v7
        - image: arm32v7/golang:1.20-alpine
          platform: linux/arm/v7
        - image: arm32v7/golang:1.21-alpine
          platform: linux/arm/v7
        - image: arm32v7/golang:1.22-alpine
          platform: linux/arm/v7
        - image: arm32v7/golang:1.23-alpine
          platform: linux/arm/v7
        - image: arm64v8/golang:1.15-alpine
          platform: linux/arm64
        - image: arm64v8/golang:1.16-alpine
          platform: linux/arm64
        - image: arm64v8/golang:1.17-alpine
          platform: linux/arm64
        - image: arm64v8/golang:1.18-alpine
          platform: linux/arm64
        - image: arm64v8/golang:1.19-alpine
          platform: linux/arm64
        - image: arm64v8/golang:1.20-alpine
          platform: linux/arm64
        - image: arm64v8/golang:1.21-alpine
          platform: linux/arm64
        - image: arm64v8/golang:1.22-alpine
          platform: linux/arm64
        - image: arm64v8/golang:1.23-alpine
          platform: linux/arm64
        - image: amd64/golang:1.15-alpine
          platform: linux/amd64
        - image: amd64/golang:1.16-alpine
          platform: linux/amd64
        - image: amd64/golang:1.17-alpine
          platform: linux/amd64
        - image: amd64/golang:1.18-alpine
          platform: linux/amd64
        - image: amd64/golang:1.19-alpine
          platform: linux/amd64
        - image: amd64/golang:1.20-alpine
          platform: linux/amd64
        - image: amd64/golang:1.21-alpine
          platform: linux/amd64
        - image: amd64/golang:1.22-alpine
          platform: linux/amd64
        - image: amd64/golang:1.23-alpine
          platform: linux/amd64
        - image: amd64/golang:1.15-alpine
          platform: linux/amd64/v2
        - image: amd64/golang:1.16-alpine
          platform: linux/amd64/v2
        - image: amd64/golang:1.17-alpine
          platform: linux/amd64/v2
        - image: amd64/golang:1.18-alpine
          platform: linux/amd64/v2
        - image: amd64/golang:1.19-alpine
          platform: linux/amd64/v2
        - image: amd64/golang:1.20-alpine
          platform: linux/amd64/v2
        - image: amd64/golang:1.21-alpine
          platform: linux/amd64/v2
        - image: amd64/golang:1.22-alpine
          platform: linux/amd64/v2
        - image: amd64/golang:1.23-alpine
          platform: linux/amd64/v2
        - image: amd64/golang:1.15-alpine
          platform: linux/amd64/v3
        - image: amd64/golang:1.16-alpine
          platform: linux/amd64/v3
        - image: amd64/golang:1.17-alpine
          platform: linux/amd64/v3
        - image: amd64/golang:1.18-alpine
          platform: linux/amd64/v3
        - image: amd64/golang:1.19-alpine
          platform: linux/amd64/v3
        - image: amd64/golang:1.20-alpine
          platform: linux/amd64/v3
        - image: amd64/golang:1.21-alpine
          platform: linux/amd64/v3
        - image: amd64/golang:1.22-alpine
          platform: linux/amd64/v3
        - image: amd64/golang:1.23-alpine
          platform: linux/amd64/v3
        - image: ppc64le/golang:1.21-alpine
          platform: linux/ppc64le
        - image: ppc64le/golang:1.22-alpine
          platform: linux/ppc64le
        - image: ppc64le/golang:1.23-alpine
          platform: linux/ppc64le
        - image: s390x/golang:1.21-alpine
          platform: linux/s390x
        - image: s390x/golang:1.22-alpine
          platform: linux/s390x
        - image: s390x/golang:1.23-alpine
          platform: linux/s390x
        - image: mips64le/golang:1.15-buster
          platform: linux/mips64le
        - image: mips64le/golang:1.16-bullseye
          platform: linux/mips64le
        - image: mips64le/golang:1.17-bullseye
          platform: linux/mips64le
        - image: mips64le/golang:1.18-bullseye
          platform: linux/mips64le
        - image: mips64le/golang:1.19-bookworm
          platform: linux/mips64le
        - image: mips64le/golang:1.20-bookworm
          platform: linux/mips64le
        - image: mips64le/golang:1.21-bookworm
          platform: linux/mips64le
        - image: mips64le/golang:1.22-bookworm
          platform: linux/mips64le
        - image: mips64le/golang:1.23-bookworm
          platform: linux/mips64le
        - image: riscv64/golang:1.21-alpine
          platform: linux/riscv64
        - image: riscv64/golang:1.22-alpine
          platform: linux/riscv64
        - image: riscv64/golang:1.23-alpine
          platform: linux/riscv64
        - image: i386/golang:1.15-alpine
          platform: linux/386
        - image: i386/golang:1.16-alpine
          platform: linux/386
        - image: i386/golang:1.17-alpine
          platform: linux/386
        - image: i386/golang:1.18-alpine
          platform: linux/386
        - image: i386/golang:1.19-alpine
          platform: linux/386
        - image: i386/golang:1.20-alpine
          platform: linux/386
        - image: i386/golang:1.21-alpine
          platform: linux/386
        - image: i386/golang:1.22-alpine
          platform: linux/386
        - image: i386/golang:1.23-alpine
          platform: linux/386

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set git to use LF
        run: |
          git config core.autocrlf false
          git rm --cached -r .
          git reset --hard

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Test (purego)
        run: |
          docker run                                  \
            --rm                                      \
            --volume    ${{ github.workspace }}:/src  \
            --workdir   /src                          \
            --platform  ${{ matrix.platform }}        \
            ${{ matrix.image }}                       \
            go test --tags=purego ./...

      - name: Test
        run: |
          docker run                                  \
            --rm                                      \
            --volume    ${{ github.workspace }}:/src  \
            --workdir   /src                          \
            --platform  ${{ matrix.platform }}        \
            ${{ matrix.image }}                       \
            go test -v ./...
