name: Go Test

on:
  workflow_run:
    workflows: [ 'Lint' ]
    branches:
      - master
    types:
      - completed

jobs:
  go-test:
    strategy:
      matrix:
        go-version:
          - '1.15'
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'

        runs-on:
          - ubuntu-latest
          - [ 'macOS', 'self-hosted' ]
          - windows-latest

        exclude:
          - runs-on: [ 'macOS', 'self-hosted' ]
            go-version: '1.15'

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - name: Set git to use LF
        run: |
          git config core.autocrlf false
          git rm --cached -r .
          git reset --hard

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: |
          go get .
          go get github.com/RyuaNerin/elliptic2@v1.0.0

      - name: Build
        run: go build -v ./...

      - name: Test (purego)
        run: go test --tags=purego ./...
        # run: go test -test.short --tags=purego ./...

      - name: Test
        run: go test ./...
        # run: go test -test.short ./...
