name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci-lint:
    strategy:
      matrix:
        go-version:
          - '1.15'
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'

        runs-on:
          - ubuntu-latest
          - [ 'macOS', 'self-hosted' ]
          - windows-latest

        exclude:
          - runs-on: [ 'macOS', 'self-hosted' ]
            go-version: '1.15'

    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          skip-go-installation: true
          version: v1.59.0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          skip-go-installation: true
          version: v1.59.0
          args: --build-tags purego
